export const CHT_AREA = 'AREA'
, CHT_SPLINE = 'SPLINE'
, CHT_LINE = 'LINE'
, CHT_COLUMN = 'COLUMN'

export const CHT_BAR_CLUSTER = "BAR_CLUSTER"
, CHT_BAR_SET = "BAR_SET"
, CHT_BAR_WITH_LABELS = "BAR_WITH_LABELS"
, CHT_COLUMN_SET = "COLUMN_SET"
, CHT_COLUMN_CLUSTER = "COLUMN_CLUSTER"
, CHT_TREE_MAP = "TREE_MAP"
, CHT_TREE_MAP_CLUSTER = "TREE_MAP_CLUSTER"
, CHT_TREE_MAP_2 = "TREE_MAP_2"
, CHT_TREE_MAP_2_CLUSTER = "TREE_MAP_2_CLUSTER"

export const CHT_MAP = 'MAP'
, CHT_DOT_SET = 'DOT_SET'

export const CHT_SEMI_DONUT = 'SEMI_DONUT'
export const CHT_STACKED_AREA = 'STACKED_AREA'
export const CHT_STACKED_AREA_PERCENT = 'STACKED_AREA_PERCENT'
export const CHT_STACKED_COLUMN = 'STACKED_COLUMN'
export const CHT_STACKED_COLUMN_PERCENT = 'STACKED_COLUMN_PERCENT'

export const CHT_YEARLY = 'YEARLY'
export const CHT_AREA_YEARLY = 'AREA_YEARLY'

export const CHT_SCATTER = 'SCATTER'
export const CHT_SCATTER_UP = 'SCATTER_UP'
export const CHT_SCATTER_DOWN = 'SCATTER_DOWN'
