export const ChartType = {
  AREA: 'AREA',
  SEMI_DONUT: 'SEMI_DONUT',
  STACKED_AREA: 'STACKED_AREA',
  STACKED_AREA_PERCENT: 'STACKED_AREA_PERCENT',
  STACKED_COLUMN: 'STACKED_COLUMN',
  STACKED_COLUMN_PERCENT: 'STACKED_COLUMN_PERCENT',
  TREE_MAP: 'TREE_MAP',
  YEARLY: 'YEARLY',
  SCATTER: 'SCATTER',
  SCATTER_UP: 'SCATTER_UP',
  SCATTER_DOWN: 'SCATTER_DOWN'
}

export const LoadType = {
  Q: 'Q',
  AL: 'AL',
  IEX: 'IEX',
  FMP: 'FMP',
  TW: 'TW',
  QCT: 'QCT',
  DBN: 'DBN',
  EU_STAT: 'EU_STAT',
  FS: 'FS',
  UKS: 'UKS',
  NST: 'NST',
  NST_2: 'NST_2',
  SWS: 'SWS',
  SFL: 'SFL',
  SDN: 'SDN',
  SIR: 'SIR',
  UN: 'UN',
  FAO: 'FAO',
  WB: 'WB',
  BEA: 'BEA',
  BLS: 'BLS',
  EIA: 'EIA',
  INTR: 'INTR',
  CRC: 'CRC',
  CG: 'CG',
  CM: 'CM',
  CP: 'CP',
  CL: 'CL',
  BN: 'BN',
  BF: 'BF',
  BT: 'BT',
  WL: 'WL',
  WATCH_LIST: 'WL_WATCH_LIST'
}
