"use strict";

exports.__esModule = true;
exports.CHT_YEARLY = exports.CHT_TREE_MAP = exports.CHT_STACKED_COLUMN_PERCENT = exports.CHT_STACKED_COLUMN = exports.CHT_STACKED_AREA_PERCENT = exports.CHT_STACKED_AREA = exports.CHT_SPLINE = exports.CHT_SEMI_DONUT = exports.CHT_SCATTER_UP = exports.CHT_SCATTER_DOWN = exports.CHT_SCATTER = exports.CHT_LINE = exports.CHT_COLUMN = exports.CHT_AREA_YEARLY = exports.CHT_AREA = void 0;
const CHT_AREA = exports.CHT_AREA = 'AREA',
  CHT_SPLINE = exports.CHT_SPLINE = 'SPLINE',
  CHT_LINE = exports.CHT_LINE = 'LINE',
  CHT_COLUMN = exports.CHT_COLUMN = 'COLUMN';
const CHT_SEMI_DONUT = exports.CHT_SEMI_DONUT = 'SEMI_DONUT';
const CHT_STACKED_AREA = exports.CHT_STACKED_AREA = 'STACKED_AREA';
const CHT_STACKED_AREA_PERCENT = exports.CHT_STACKED_AREA_PERCENT = 'STACKED_AREA_PERCENT';
const CHT_STACKED_COLUMN = exports.CHT_STACKED_COLUMN = 'STACKED_COLUMN';
const CHT_STACKED_COLUMN_PERCENT = exports.CHT_STACKED_COLUMN_PERCENT = 'STACKED_COLUMN_PERCENT';
const CHT_TREE_MAP = exports.CHT_TREE_MAP = 'TREE_MAP';
const CHT_YEARLY = exports.CHT_YEARLY = 'YEARLY';
const CHT_AREA_YEARLY = exports.CHT_AREA_YEARLY = 'AREA_YEARLY';
const CHT_SCATTER = exports.CHT_SCATTER = 'SCATTER';
const CHT_SCATTER_UP = exports.CHT_SCATTER_UP = 'SCATTER_UP';
const CHT_SCATTER_DOWN = exports.CHT_SCATTER_DOWN = 'SCATTER_DOWN';
//# sourceMappingURL=ChartType.js.map