"use strict";

exports.__esModule = true;
exports.CHT_YEARLY = exports.CHT_TREE_MAP_CLUSTER = exports.CHT_TREE_MAP_2_CLUSTER = exports.CHT_TREE_MAP_2 = exports.CHT_TREE_MAP = exports.CHT_STACKED_COLUMN_PERCENT = exports.CHT_STACKED_COLUMN = exports.CHT_STACKED_AREA_PERCENT = exports.CHT_STACKED_AREA = exports.CHT_SPLINE = exports.CHT_SEMI_DONUT = exports.CHT_SCATTER_UP = exports.CHT_SCATTER_DOWN = exports.CHT_SCATTER = exports.CHT_MAP = exports.CHT_LINE = exports.CHT_DOT_SET = exports.CHT_COLUMN_SET = exports.CHT_COLUMN_CLUSTER = exports.CHT_COLUMN = exports.CHT_BAR_WITH_LABELS = exports.CHT_BAR_SET = exports.CHT_BAR_CLUSTER = exports.CHT_AREA_YEARLY = exports.CHT_AREA = void 0;
const CHT_AREA = exports.CHT_AREA = 'AREA',
  CHT_SPLINE = exports.CHT_SPLINE = 'SPLINE',
  CHT_LINE = exports.CHT_LINE = 'LINE',
  CHT_COLUMN = exports.CHT_COLUMN = 'COLUMN';
const CHT_BAR_CLUSTER = exports.CHT_BAR_CLUSTER = "BAR_CLUSTER",
  CHT_BAR_SET = exports.CHT_BAR_SET = "BAR_SET",
  CHT_BAR_WITH_LABELS = exports.CHT_BAR_WITH_LABELS = "BAR_WITH_LABELS",
  CHT_COLUMN_SET = exports.CHT_COLUMN_SET = "COLUMN_SET",
  CHT_COLUMN_CLUSTER = exports.CHT_COLUMN_CLUSTER = "COLUMN_CLUSTER",
  CHT_TREE_MAP = exports.CHT_TREE_MAP = "TREE_MAP",
  CHT_TREE_MAP_CLUSTER = exports.CHT_TREE_MAP_CLUSTER = "TREE_MAP_CLUSTER",
  CHT_TREE_MAP_2 = exports.CHT_TREE_MAP_2 = "TREE_MAP_2",
  CHT_TREE_MAP_2_CLUSTER = exports.CHT_TREE_MAP_2_CLUSTER = "TREE_MAP_2_CLUSTER";
const CHT_MAP = exports.CHT_MAP = 'MAP',
  CHT_DOT_SET = exports.CHT_DOT_SET = 'DOT_SET';
const CHT_SEMI_DONUT = exports.CHT_SEMI_DONUT = 'SEMI_DONUT';
const CHT_STACKED_AREA = exports.CHT_STACKED_AREA = 'STACKED_AREA';
const CHT_STACKED_AREA_PERCENT = exports.CHT_STACKED_AREA_PERCENT = 'STACKED_AREA_PERCENT';
const CHT_STACKED_COLUMN = exports.CHT_STACKED_COLUMN = 'STACKED_COLUMN';
const CHT_STACKED_COLUMN_PERCENT = exports.CHT_STACKED_COLUMN_PERCENT = 'STACKED_COLUMN_PERCENT';
const CHT_YEARLY = exports.CHT_YEARLY = 'YEARLY';
const CHT_AREA_YEARLY = exports.CHT_AREA_YEARLY = 'AREA_YEARLY';
const CHT_SCATTER = exports.CHT_SCATTER = 'SCATTER';
const CHT_SCATTER_UP = exports.CHT_SCATTER_UP = 'SCATTER_UP';
const CHT_SCATTER_DOWN = exports.CHT_SCATTER_DOWN = 'SCATTER_DOWN';
//# sourceMappingURL=ChartType.js.map