"use strict";

exports.__esModule = true;
exports.CHT_YEARLY = exports.CHT_TREE_MAP = exports.CHT_STACKED_COLUMN_PERCENT = exports.CHT_STACKED_COLUMN = exports.CHT_STACKED_AREA_PERCENT = exports.CHT_STACKED_AREA = exports.CHT_SEMI_DONUT = exports.CHT_SCATTER_UP = exports.CHT_SCATTER_DOWN = exports.CHT_SCATTER = exports.CHT_AREA = void 0;
const CHT_AREA = 'AREA';
exports.CHT_AREA = CHT_AREA;
const CHT_SEMI_DONUT = 'SEMI_DONUT';
exports.CHT_SEMI_DONUT = CHT_SEMI_DONUT;
const CHT_STACKED_AREA = 'STACKED_AREA';
exports.CHT_STACKED_AREA = CHT_STACKED_AREA;
const CHT_STACKED_AREA_PERCENT = 'STACKED_AREA_PERCENT';
exports.CHT_STACKED_AREA_PERCENT = CHT_STACKED_AREA_PERCENT;
const CHT_STACKED_COLUMN = 'STACKED_COLUMN';
exports.CHT_STACKED_COLUMN = CHT_STACKED_COLUMN;
const CHT_STACKED_COLUMN_PERCENT = 'STACKED_COLUMN_PERCENT';
exports.CHT_STACKED_COLUMN_PERCENT = CHT_STACKED_COLUMN_PERCENT;
const CHT_TREE_MAP = 'TREE_MAP';
exports.CHT_TREE_MAP = CHT_TREE_MAP;
const CHT_YEARLY = 'YEARLY';
exports.CHT_YEARLY = CHT_YEARLY;
const CHT_SCATTER = 'SCATTER';
exports.CHT_SCATTER = CHT_SCATTER;
const CHT_SCATTER_UP = 'SCATTER_UP';
exports.CHT_SCATTER_UP = CHT_SCATTER_UP;
const CHT_SCATTER_DOWN = 'SCATTER_DOWN';
exports.CHT_SCATTER_DOWN = CHT_SCATTER_DOWN;
//# sourceMappingURL=ChartType.js.map