"use strict";

exports.__esModule = true;
exports.isEstat = exports.isEmber = exports.LT_WL = exports.LT_WB = exports.LT_WATCH_LIST = exports.LT_UN = exports.LT_UKS = exports.LT_TW = exports.LT_SWS = exports.LT_SIR = exports.LT_SFL = exports.LT_SDN = exports.LT_QCT = exports.LT_Q = exports.LT_NST_2 = exports.LT_NST = exports.LT_KR = exports.LT_KC = exports.LT_IRE = exports.LT_INTR = exports.LT_IEX = exports.LT_GT = exports.LT_FS = exports.LT_FMP = exports.LT_FAO = exports.LT_EU_STAT = exports.LT_EMB = exports.LT_EIA = exports.LT_EI = exports.LT_DBN = exports.LT_CRC = exports.LT_CP = exports.LT_CM = exports.LT_CL = exports.LT_CG = exports.LT_BT = exports.LT_BN = exports.LT_BLS = exports.LT_BF = exports.LT_BEA = exports.LT_AL = void 0;
const LT_Q = exports.LT_Q = 'Q';
const LT_QCT = exports.LT_QCT = 'QCT';
const LT_AL = exports.LT_AL = 'AL';
const LT_IEX = exports.LT_IEX = 'IEX';
const LT_FMP = exports.LT_FMP = 'FMP';
const LT_TW = exports.LT_TW = 'TW';
const LT_DBN = exports.LT_DBN = 'DBN';
const LT_EI = exports.LT_EI = 'EI';
const LT_EMB = exports.LT_EMB = 'EMB';
const LT_IRE = exports.LT_IRE = 'IRE';
const LT_EU_STAT = exports.LT_EU_STAT = 'EU_STAT';
const LT_FS = exports.LT_FS = 'FS';
const LT_UKS = exports.LT_UKS = 'UKS';
const LT_NST = exports.LT_NST = 'NST';
const LT_NST_2 = exports.LT_NST_2 = 'NST_2';
const LT_SWS = exports.LT_SWS = 'SWS';
const LT_SFL = exports.LT_SFL = 'SFL';
const LT_SDN = exports.LT_SDN = 'SDN';
const LT_SIR = exports.LT_SIR = 'SIR';
const LT_UN = exports.LT_UN = 'UN';
const LT_FAO = exports.LT_FAO = 'FAO';
const LT_WB = exports.LT_WB = 'WB';
const LT_BEA = exports.LT_BEA = 'BEA';
const LT_BLS = exports.LT_BLS = 'BLS';
const LT_EIA = exports.LT_EIA = 'EIA';
const LT_INTR = exports.LT_INTR = 'INTR';
const LT_CRC = exports.LT_CRC = 'CRC';
const LT_CG = exports.LT_CG = 'CG';
const LT_CM = exports.LT_CM = 'CM';
const LT_CP = exports.LT_CP = 'CP';
const LT_CL = exports.LT_CL = 'CL';
const LT_BN = exports.LT_BN = 'BN';
const LT_BF = exports.LT_BF = 'BF';
const LT_BT = exports.LT_BT = 'BT';
const LT_KR = exports.LT_KR = 'KR';
const LT_KC = exports.LT_KC = 'KC';
const LT_GT = exports.LT_GT = 'GT';
const LT_WL = exports.LT_WL = 'WL';
const LT_WATCH_LIST = exports.LT_WATCH_LIST = 'WL_WATCH_LIST';
const isEstat = loadId => loadId === LT_EU_STAT;
exports.isEstat = isEstat;
const isEmber = loadId => loadId === LT_EMB;
exports.isEmber = isEmber;
//# sourceMappingURL=LoadType.js.map