"use strict";

exports.__esModule = true;
exports.MDT_ZOOM = exports.MDT_STOCKS_BY_SECTOR = exports.MDT_SETTINGS = exports.MDT_RELOAD = exports.MDT_PASTE_TO = exports.MDT_LOAD_ITEM = exports.MDT_INFO = exports.MDT_EDIT_WATCH_LIST = exports.MDT_EDIT_WATCH_GROUP = exports.MDT_DESCRIPTION = exports.MDT_CUSTOMIZE_EXPORT = exports.MDT_COLUMN_RANGE = exports.MDT_ASK = exports.MDT_ALERT = exports.MDT_ADD_TO_WATCH = void 0;
const MDT_ASK = 'ASK';
exports.MDT_ASK = MDT_ASK;
const MDT_RELOAD = 'RELOAD';
exports.MDT_RELOAD = MDT_RELOAD;
const MDT_INFO = 'info';
exports.MDT_INFO = MDT_INFO;
const MDT_ALERT = 'alert';
exports.MDT_ALERT = MDT_ALERT;
const MDT_DESCRIPTION = 'DESCRIPTION';
exports.MDT_DESCRIPTION = MDT_DESCRIPTION;
const MDT_SETTINGS = 'settings';
exports.MDT_SETTINGS = MDT_SETTINGS;
const MDT_CUSTOMIZE_EXPORT = 'CUSTOMIZE_EXPORT';
exports.MDT_CUSTOMIZE_EXPORT = MDT_CUSTOMIZE_EXPORT;
const MDT_COLUMN_RANGE = 'COLUMN_RANGE';
exports.MDT_COLUMN_RANGE = MDT_COLUMN_RANGE;
const MDT_ADD_TO_WATCH = 'addToWatch';
exports.MDT_ADD_TO_WATCH = MDT_ADD_TO_WATCH;
const MDT_LOAD_ITEM = 'loadItem';
exports.MDT_LOAD_ITEM = MDT_LOAD_ITEM;
const MDT_STOCKS_BY_SECTOR = 'STOCKS_BY_SECTOR';
exports.MDT_STOCKS_BY_SECTOR = MDT_STOCKS_BY_SECTOR;
const MDT_EDIT_WATCH_GROUP = 'editWatchGroup';
exports.MDT_EDIT_WATCH_GROUP = MDT_EDIT_WATCH_GROUP;
const MDT_EDIT_WATCH_LIST = 'editWatchList';
exports.MDT_EDIT_WATCH_LIST = MDT_EDIT_WATCH_LIST;
const MDT_PASTE_TO = 'pasteTo';
exports.MDT_PASTE_TO = MDT_PASTE_TO;
const MDT_ZOOM = 'zoom';
exports.MDT_ZOOM = MDT_ZOOM;
//# sourceMappingURL=ModalDialogType.js.map