const C_GROUP_OPEN = '#1b2836'
, C_LIST_OPEN = '#80c040'
, DRAG = {
  GROUP: 'GROUP',
  C_GROUP_ENTER: C_GROUP_OPEN,
  LIST: 'LIST',
  C_LIST_ENTER: C_LIST_OPEN,
  ITEM: 'ITEM'
};

export default DRAG
