
const YahooStockholm = {};

const tickets = [
  { ticket:"203", value:"YAHOO/ST_203", caption:"203 WEB GROUP (203)" },
  { ticket:"2E", value:"YAHOO/ST_2E", caption:"2E GROUP (2E)" },
  { ticket:"A1M", value:"YAHOO/ST_A1M", caption:"A1M PHARMA (A1M)" },
  { ticket:"AAK", value:"YAHOO/ST_AAK", caption:"AARHUSKARLSHAMN (AAK)" },
  { ticket:"ABB", value:"YAHOO/ST_ABB", caption:"ABB N (ABB)" },
  { ticket:"ABE", value:"YAHOO/ST_ABE", caption:"ABELCO (ABE)" },
  { ticket:"ACTI", value:"YAHOO/ST_ACTI", caption:"ACTIVE BIOTECH (ACTI)" },
  { ticket:"ANODB", value:"YAHOO/ST_ANODB", caption:"ADDNODE GROUP -B- (ANODB)" },
  { ticket:"ADDV", value:"YAHOO/ST_ADDV", caption:"ADDVISE LAB SOLUTIO (ADDV)" },
  { ticket:"AOI", value:"YAHOO/ST_AOI", caption:"AFRICA OIL (AOI)" },
  { ticket:"AGIS", value:"YAHOO/ST_AGIS", caption:"AGELLIS GROUP (AGIS)" },
  { ticket:"AGRA", value:"YAHOO/ST_AGRA", caption:"AGROKULTURA (AGRA)" },
  { ticket:"ALFA", value:"YAHOO/ST_ALFA", caption:"ALFA LAVAL (ALFA)" },
  { ticket:"ALNX", value:"YAHOO/ST_ALNX", caption:"ALLENEX -B- (ALNX)" },
  { ticket:"ALM", value:"YAHOO/ST_ALM", caption:"ALM EQUITY -A- (ALM)" },
  { ticket:"ALPH", value:"YAHOO/ST_ALPH", caption:"ALPHAHELIX MOLE DIA (ALPH)" },
  { ticket:"AMAST", value:"YAHOO/ST_AMAST", caption:"AMASTEN (AMAST)" },
  { ticket:"ANGL", value:"YAHOO/ST_ANGL", caption:"ANGLER GAMING (ANGL)" },
  { ticket:"ANOT", value:"YAHOO/ST_ANOT", caption:"ANOTO GROUP (ANOT)" },
  { ticket:"AQ", value:"YAHOO/ST_AQ", caption:"AQ GROUP (AQ)" },
  { ticket:"AQER", value:"YAHOO/ST_AQER", caption:"AQERI HOLDING (AQER)" },
  { ticket:"ARCM", value:"YAHOO/ST_ARCM", caption:"ARCAM (ARCM)" },
  { ticket:"ARCT", value:"YAHOO/ST_ARCT", caption:"ARCTIC GOLD (ARCT)" },
  { ticket:"ARP", value:"YAHOO/ST_ARP", caption:"ARCTIC PAPER (ARP)" },
  { ticket:"ARISE", value:"YAHOO/ST_ARISE", caption:"ARISE (ARISE)" },
  { ticket:"AROC", value:"YAHOO/ST_AROC", caption:"AROCELL (AROC)" },
  { ticket:"ASP", value:"YAHOO/ST_ASP", caption:"ASPIRO INFORMATION (ASP)" },
  { ticket:"AZN", value:"YAHOO/ST_AZN", caption:"ASTRAZENECA (AZN)" },
  { ticket:"AUR", value:"YAHOO/ST_AUR", caption:"AURIANT MINING (AUR)" },
  { ticket:"AZA", value:"YAHOO/ST_AZA", caption:"AVANZA BANK HLDG (AZA)" },
  { ticket:"AXFO", value:"YAHOO/ST_AXFO", caption:"AXFOOD  (AXFO)" },
  { ticket:"AXIS", value:"YAHOO/ST_AXIS", caption:"AXIS  (AXIS)" },
  { ticket:"BCS", value:"YAHOO/ST_BCS", caption:"BCS (BCS)" },
  { ticket:"BEGR", value:"YAHOO/ST_BEGR", caption:"BE GROUP (BEGR)" },
  { ticket:"BELE", value:"YAHOO/ST_BELE", caption:"BEIJER ELECTRONICS  (BELE)" },
  { ticket:"BETT", value:"YAHOO/ST_BETT", caption:"BETTING PROMOTION S (BETT)" },
  { ticket:"BILL", value:"YAHOO/ST_BILL", caption:"BILLERUDKORSNAS (BILL)" },
  { ticket:"BINV", value:"YAHOO/ST_BINV", caption:"BIOINVENT (BINV)" },
  { ticket:"BIOT", value:"YAHOO/ST_BIOT", caption:"BIOTAGE (BIOT)" },
  { ticket:"BORG", value:"YAHOO/ST_BORG", caption:"BJORN BORG (BORG)" },
  { ticket:"BOL", value:"YAHOO/ST_BOL", caption:"BOLIDEN (BOL)" },
  { ticket:"BONG", value:"YAHOO/ST_BONG", caption:"BONG (BONG)" },
  { ticket:"BOTX", value:"YAHOO/ST_BOTX", caption:"BOTNIA EXPLOR HOLD (BOTX)" },
  { ticket:"BOUL", value:"YAHOO/ST_BOUL", caption:"BOULE DIAGNOSTICS (BOUL)" },
  { ticket:"BRE2", value:"YAHOO/ST_BRE2", caption:"BREDBAND2 I SKANDI (BRE2)" },
  { ticket:"BRIG", value:"YAHOO/ST_BRIG", caption:"BRIGHTER (BRIG)" },
  { ticket:"BWL", value:"YAHOO/ST_BWL", caption:"BRINGWELL (BWL)" },
  { ticket:"BURE", value:"YAHOO/ST_BURE", caption:"BURE EQUITY (BURE)" },
  { ticket:"BMAX", value:"YAHOO/ST_BMAX", caption:"BYGGMAX GROUP (BMAX)" },
  { ticket:"CAPE", value:"YAHOO/ST_CAPE", caption:"CAPERIO HOLDING (CAPE)" },
  { ticket:"CASO", value:"YAHOO/ST_CASO", caption:"CASSANDRA OIL (CASO)" },
  { ticket:"CAST", value:"YAHOO/ST_CAST", caption:"CASTELLUM (CAST)" },
  { ticket:"CATE", value:"YAHOO/ST_CATE", caption:"CATENA (CATE)" },
  { ticket:"CAOI", value:"YAHOO/ST_CAOI", caption:"CAUCASUS OIL (CAOI)" },
  { ticket:"CCC", value:"YAHOO/ST_CCC", caption:"CAVOTEC N (CCC)" },
  { ticket:"CDON", value:"YAHOO/ST_CDON", caption:"CDON GROUP (CDON)" },
  { ticket:"CEVI", value:"YAHOO/ST_CEVI", caption:"CELLAVISION (CEVI)" },
  { ticket:"CPNT", value:"YAHOO/ST_CPNT", caption:"CELLPOINT CONNECT (CPNT)" },
  { ticket:"CTEC", value:"YAHOO/ST_CTEC", caption:"CHRONTECH PHARMA (CTEC)" },
  { ticket:"CSN", value:"YAHOO/ST_CSN", caption:"CISION (CSN)" },
  { ticket:"CWS", value:"YAHOO/ST_CWS", caption:"COMFORT WINDOWS (CWS)" },
  { ticket:"CEAB", value:"YAHOO/ST_CEAB", caption:"COMM ENT SVENSKA (CEAB)" },
  { ticket:"COMQ", value:"YAHOO/ST_COMQ", caption:"COMMODITY QUEST (COMQ)" },
  { ticket:"COIC", value:"YAHOO/ST_COIC", caption:"CONCENTRIC  (COIC)" },
  { ticket:"CNTA", value:"YAHOO/ST_CNTA", caption:"CONNECTA (CNTA)" },
  { ticket:"CORE", value:"YAHOO/ST_CORE", caption:"COREM PROPERTY (CORE)" },
  { ticket:"CE", value:"YAHOO/ST_CE", caption:"CORTUS ENERGY (CE)" },
  { ticket:"CTT", value:"YAHOO/ST_CTT", caption:"CTT SYSTEMS (CTT)" },
  { ticket:"CBA", value:"YAHOO/ST_CBA", caption:"CYBAERO (CBA)" },
  { ticket:"CYBE", value:"YAHOO/ST_CYBE", caption:"CYBERCOM GROUP (CYBE)" },
  { ticket:"DEDI", value:"YAHOO/ST_DEDI", caption:"DEDICARE -B- (DEDI)" },
  { ticket:"DELT", value:"YAHOO/ST_DELT", caption:"DELTACO (DELT)" },
  { ticket:"DGC", value:"YAHOO/ST_DGC", caption:"DGCONE (DGC)" },
  { ticket:"DIAH", value:"YAHOO/ST_DIAH", caption:"DIADROM HOLDING (DIAH)" },
  { ticket:"DIBS", value:"YAHOO/ST_DIBS", caption:"DIBS PAYMENT SERV (DIBS)" },
  { ticket:"DIGN", value:"YAHOO/ST_DIGN", caption:"DIGNITANA (DIGN)" },
  { ticket:"DIOS", value:"YAHOO/ST_DIOS", caption:"DIOS FASTIGHETER (DIOS)" },
  { ticket:"DORO", value:"YAHOO/ST_DORO", caption:"DORO (DORO)" },
  { ticket:"DRIL", value:"YAHOO/ST_DRIL", caption:"DRILLCON (DRIL)" },
  { ticket:"DUNI", value:"YAHOO/ST_DUNI", caption:"DUNI (DUNI)" },
  { ticket:"ECEX", value:"YAHOO/ST_ECEX", caption:"EAST CAPITAL EXPLOR (ECEX)" },
  { ticket:"BLIT", value:"YAHOO/ST_BLIT", caption:"ECO BYGGOLIT (BLIT)" },
  { ticket:"ECOM", value:"YAHOO/ST_ECOM", caption:"ECOM (ECOM)" },
  { ticket:"ELEC", value:"YAHOO/ST_ELEC", caption:"ELECTRA GRUPPEN (ELEC)" },
  { ticket:"ELN", value:"YAHOO/ST_ELN", caption:"ELLEN (ELN)" },
  { ticket:"ELV", value:"YAHOO/ST_ELV", caption:"ELVERKET VALLENTUNA (ELV)" },
  { ticket:"EMOT", value:"YAHOO/ST_EMOT", caption:"EMOTRA (EMOT)" },
  { ticket:"ENDO", value:"YAHOO/ST_ENDO", caption:"ENDOMINES (ENDO)" },
  { ticket:"ENEA", value:"YAHOO/ST_ENEA", caption:"ENEA (ENEA)" },
  { ticket:"ENRO", value:"YAHOO/ST_ENRO", caption:"ENIRO (ENRO)" },
  { ticket:"ENQ", value:"YAHOO/ST_ENQ", caption:"ENQUEST (ENQ)" },
  { ticket:"ENZY", value:"YAHOO/ST_ENZY", caption:"ENZYMATICA (ENZY)" },
  { ticket:"ETX", value:"YAHOO/ST_ETX", caption:"ETRION (ETX)" },
  { ticket:"EUCI", value:"YAHOO/ST_EUCI", caption:"EUROCINE VACCINES (EUCI)" },
  { ticket:"EURO", value:"YAHOO/ST_EURO", caption:"EUROCON CONSULTING (EURO)" },
  { ticket:"EWRK", value:"YAHOO/ST_EWRK", caption:"EWORK SCANDINAVIA (EWRK)" },
  { ticket:"FABG", value:"YAHOO/ST_FABG", caption:"FABEGE (FABG)" },
  { ticket:"FAG", value:"YAHOO/ST_FAG", caption:"FAGERHULT (FAG)" },
  { ticket:"FPAR", value:"YAHOO/ST_FPAR", caption:"FASTPARTNER (FPAR)" },
  { ticket:"FDT", value:"YAHOO/ST_FDT", caption:"FDT SYSTEM HOLD (FDT)" },
  { ticket:"FEEL", value:"YAHOO/ST_FEEL", caption:"FEELGOOD SVENSKA (FEEL)" },
  { ticket:"FBAB", value:"YAHOO/ST_FBAB", caption:"FINNVEDENBULTEN (FBAB)" },
  { ticket:"FIRE", value:"YAHOO/ST_FIRE", caption:"FIREFLY (FIRE)" },
  { ticket:"FORE", value:"YAHOO/ST_FORE", caption:"FORESTLIGHT ENT (FORE)" },
  { ticket:"FPIP", value:"YAHOO/ST_FPIP", caption:"FORMPIPE SOFTWARE (FPIP)" },
  { ticket:"G5EN", value:"YAHOO/ST_G5EN", caption:"G5 ENTERTAINMENT (G5EN)" },
  { ticket:"GENI", value:"YAHOO/ST_GENI", caption:"GENERIC SWEDEN (GENI)" },
  { ticket:"GENE", value:"YAHOO/ST_GENE", caption:"GENESIS-IT  (GENE)" },
  { ticket:"GENO", value:"YAHOO/ST_GENO", caption:"GENOVIS (GENO)" },
  { ticket:"GOIL", value:"YAHOO/ST_GOIL", caption:"GINGER OIL (GOIL)" },
  { ticket:"GHP", value:"YAHOO/ST_GHP", caption:"GLOB HEALTH PARTNER (GHP)" },
  { ticket:"GOG", value:"YAHOO/ST_GOG", caption:"GRIPEN OIL&GAS (GOG)" },
  { ticket:"GULA", value:"YAHOO/ST_GULA", caption:"GULDADAM HOLD (GULA)" },
  { ticket:"GJAB", value:"YAHOO/ST_GJAB", caption:"GULLBERG & JANS (GJAB)" },
  { ticket:"GUNN", value:"YAHOO/ST_GUNN", caption:"GUNNEBO (GUNN)" },
  { ticket:"HLDX", value:"YAHOO/ST_HLDX", caption:"HALDEX (HLDX)" },
  { ticket:"HMED", value:"YAHOO/ST_HMED", caption:"HANSA MEDICAL (HMED)" },
  { ticket:"HCH", value:"YAHOO/ST_HCH", caption:"HEAD COMP SWEDEN HO (HCH)" },
  { ticket:"HEDS", value:"YAHOO/ST_HEDS", caption:"HEDSON TECH INTERNA (HEDS)" },
  { ticket:"HEMX", value:"YAHOO/ST_HEMX", caption:"HEMTEX (HEMX)" },
  { ticket:"HTRO", value:"YAHOO/ST_HTRO", caption:"HEXATRONIC SCANDIN (HTRO)" },
  { ticket:"HIQ", value:"YAHOO/ST_HIQ", caption:"HIQ INTL (HIQ)" },
  { ticket:"HMS", value:"YAHOO/ST_HMS", caption:"HMS NETWORKS (HMS)" },
  { ticket:"HQ", value:"YAHOO/ST_HQ", caption:"HQ (HQ)" },
  { ticket:"ICA", value:"YAHOO/ST_ICA", caption:"ICA GRUPPEN (ICA)" },
  { ticket:"IS", value:"YAHOO/ST_IS", caption:"IMAGE SYSTEMS (IS)" },
  { ticket:"IMNP", value:"YAHOO/ST_IMNP", caption:"IMMUNE PHARM (IMNP)" },
  { ticket:"IMMU", value:"YAHOO/ST_IMMU", caption:"IMMUNICUM (IMMU)" },
  { ticket:"IMPC", value:"YAHOO/ST_IMPC", caption:"IMPACT COATINGS (IMPC)" },
  { ticket:"INDT", value:"YAHOO/ST_INDT", caption:"INDUTRADE (INDT)" },
  { ticket:"IPL", value:"YAHOO/ST_IPL", caption:"INSPLANET (IPL)" },
  { ticket:"IJ", value:"YAHOO/ST_IJ", caption:"INTRUM JUSTITIA (IJ)" },
  { ticket:"ORES", value:"YAHOO/ST_ORES", caption:"INVESTMENT OERESUND (ORES)" },
  { ticket:"IVSO", value:"YAHOO/ST_IVSO", caption:"INVISIO COMMUNICATI (IVSO)" },
  { ticket:"INXL", value:"YAHOO/ST_INXL", caption:"INXL INNOVATION (INXL)" },
  { ticket:"JM", value:"YAHOO/ST_JM", caption:"J.M. (JM)" },
  { ticket:"JAYS", value:"YAHOO/ST_JAYS", caption:"JAYS (JAYS)" },
  { ticket:"JLT", value:"YAHOO/ST_JLT", caption:"JLT MOBILE COMPUTER (JLT)" },
  { ticket:"JOJK", value:"YAHOO/ST_JOJK", caption:"JOJKA COMMUNICATION (JOJK)" },
  { ticket:"JOSA", value:"YAHOO/ST_JOSA", caption:"JOSAB INTERNATIONAL (JOSA)" },
  { ticket:"KAN", value:"YAHOO/ST_KAN", caption:"KANCERA (KAN)" },
  { ticket:"KAHL", value:"YAHOO/ST_KAHL", caption:"KAPPAHL (KAHL)" },
  { ticket:"KARO", value:"YAHOO/ST_KARO", caption:"KARO BIO (KARO)" },
  { ticket:"KDEV", value:"YAHOO/ST_KDEV", caption:"KAROL DEVEL -B- (KDEV)" },
  { ticket:"KENH", value:"YAHOO/ST_KENH", caption:"KENTIMA HOLD -B- (KENH)" },
  { ticket:"KINVA", value:"YAHOO/ST_KINVA", caption:"KINNEVIK INV. -A- (KINVA)" },
  { ticket:"KLOV", value:"YAHOO/ST_KLOV", caption:"KLOVERN (KLOV)" },
  { ticket:"KNOW", value:"YAHOO/ST_KNOW", caption:"KNOWIT (KNOW)" },
  { ticket:"KOPY", value:"YAHOO/ST_KOPY", caption:"KOPY GOLDFIELDS (KOPY)" },
  { ticket:"KLED", value:"YAHOO/ST_KLED", caption:"KUNGSLEDEN (KLED)" },
  { ticket:"LIAB", value:"YAHOO/ST_LIAB", caption:"LINDAB INTERNAT. (LIAB)" },
  { ticket:"LOVI", value:"YAHOO/ST_LOVI", caption:"LOVISAGRUVAN (LOVI)" },
  { ticket:"LUC", value:"YAHOO/ST_LUC", caption:"LUCARA DIAMOND (LUC)" },
  { ticket:"LUCE", value:"YAHOO/ST_LUCE", caption:"LUCENT OIL (LUCE)" },
  { ticket:"LUPE", value:"YAHOO/ST_LUPE", caption:"LUNDIN PETROL (LUPE)" },
  { ticket:"LYYN", value:"YAHOO/ST_LYYN", caption:"LYYN (LYYN)" },
  { ticket:"MANG", value:"YAHOO/ST_MANG", caption:"MANGOLD (MANG)" },
  { ticket:"MAXP", value:"YAHOO/ST_MAXP", caption:"MAXPEAK (MAXP)" },
  { ticket:"MCAP", value:"YAHOO/ST_MCAP", caption:"MEDCAP (MCAP)" },
  { ticket:"MCOR", value:"YAHOO/ST_MCOR", caption:"MEDCORE (MCOR)" },
  { ticket:"MEDF", value:"YAHOO/ST_MEDF", caption:"MEDFIELD DIAGN (MEDF)" },
  { ticket:"MEPR", value:"YAHOO/ST_MEPR", caption:"MEDIAPROVIDER SCA (MEPR)" },
  { ticket:"MPEN", value:"YAHOO/ST_MPEN", caption:"MEDICPEN (MPEN)" },
  { ticket:"MEKO", value:"YAHOO/ST_MEKO", caption:"MEKONOMEN (MEKO)" },
  { ticket:"MELK", value:"YAHOO/ST_MELK", caption:"MELKER SCHORLING (MELK)" },
  { ticket:"MICR", value:"YAHOO/ST_MICR", caption:"MICRONIC MYDATA (MICR)" },
  { ticket:"MPOS", value:"YAHOO/ST_MPOS", caption:"MICROPOS MEDICAL (MPOS)" },
  { ticket:"MIND", value:"YAHOO/ST_MIND", caption:"MINDMANCER (MIND)" },
  { ticket:"MIR", value:"YAHOO/ST_MIR", caption:"MIRIS HOLDING (MIR)" },
  { ticket:"MOB", value:"YAHOO/ST_MOB", caption:"MOBERG PHARMA (MOB)" },
  { ticket:"MABI", value:"YAHOO/ST_MABI", caption:"MOBI RENT (MABI)" },
  { ticket:"MQ", value:"YAHOO/ST_MQ", caption:"MQ HOLDING (MQ)" },
  { ticket:"MRG", value:"YAHOO/ST_MRG", caption:"MR GREEN & CO (MRG)" },
  { ticket:"MULQ", value:"YAHOO/ST_MULQ", caption:"MULTIQ INTL (MULQ)" },
  { ticket:"NAXS", value:"YAHOO/ST_NAXS", caption:"NAXS NORD ACCESS FD (NAXS)" },
  { ticket:"NMAN", value:"YAHOO/ST_NMAN", caption:"NEDERMAN HOLDING (NMAN)" },
  { ticket:"NETG", value:"YAHOO/ST_NETG", caption:"NET GAMING EUR (NETG)" },
  { ticket:"NJOB", value:"YAHOO/ST_NJOB", caption:"NETJOBS GROUP (NJOB)" },
  { ticket:"NVP", value:"YAHOO/ST_NVP", caption:"NEUROVIVE PHARMA (NVP)" },
  { ticket:"NNH", value:"YAHOO/ST_NNH", caption:"NEW NORD HEALTHBRAN (NNH)" },
  { ticket:"NEXAM", value:"YAHOO/ST_NEXAM", caption:"NEXAM CHEM HOLD (NEXAM)" },
  { ticket:"NIS", value:"YAHOO/ST_NIS", caption:"NISCHER (NIS)" },
  { ticket:"NOBI", value:"YAHOO/ST_NOBI", caption:"NOBIA (NOBI)" },
  { ticket:"CAMP", value:"YAHOO/ST_CAMP", caption:"NORDIC CAMP RESOUR (CAMP)" },
  { ticket:"NOMI", value:"YAHOO/ST_NOMI", caption:"NORDIC MINES (NOMI)" },
  { ticket:"NDIQ", value:"YAHOO/ST_NDIQ", caption:"NORDIQ GOTEBORG (NDIQ)" },
  { ticket:"NORDK", value:"YAHOO/ST_NORDK", caption:"NORDKOM (NORDK)" },
  { ticket:"NOTE", value:"YAHOO/ST_NOTE", caption:"NOTE (NOTE)" },
  { ticket:"NOVE", value:"YAHOO/ST_NOVE", caption:"NOVESTRA (NOVE)" },
  { ticket:"NOVU", value:"YAHOO/ST_NOVU", caption:"NOVUS GROUP INTL (NOVU)" },
  { ticket:"OASM", value:"YAHOO/ST_OASM", caption:"OASMIA (OASM)" },
  { ticket:"ODD", value:"YAHOO/ST_ODD", caption:"ODD MOLLY INT (ODD)" },
  { ticket:"OLDM", value:"YAHOO/ST_OLDM", caption:"OLD MUTUAL (OLDM)" },
  { ticket:"ONG", value:"YAHOO/ST_ONG", caption:"ONIVAOGE (ONG)" },
  { ticket:"OBAB", value:"YAHOO/ST_OBAB", caption:"ONLINE BRANDS NORDI (OBAB)" },
  { ticket:"OPCO", value:"YAHOO/ST_OPCO", caption:"OPCON (OPCO)" },
  { ticket:"OPUS", value:"YAHOO/ST_OPUS", caption:"OPUS GROUP (OPUS)" },
  { ticket:"OS", value:"YAHOO/ST_OS", caption:"ORASOLV (OS)" },
  { ticket:"ORX", value:"YAHOO/ST_ORX", caption:"OREXO (ORX)" },
  { ticket:"PAR", value:"YAHOO/ST_PAR", caption:"PA RES (PAR)" },
  { ticket:"PDXE", value:"YAHOO/ST_PDXE", caption:"PARADOX (PDXE)" },
  { ticket:"PARA", value:"YAHOO/ST_PARA", caption:"PARANS SOLAR LIGHT (PARA)" },
  { ticket:"PART", value:"YAHOO/ST_PART", caption:"PARTNERTECH (PART)" },
  { ticket:"PETRO", value:"YAHOO/ST_PETRO", caption:"PETROGRAND (PETRO)" },
  { ticket:"PFE", value:"YAHOO/ST_PFE", caption:"PFIZER (PFE)" },
  { ticket:"PHAL", value:"YAHOO/ST_PHAL", caption:"PHARMALUNDENSIS (PHAL)" },
  { ticket:"PHON", value:"YAHOO/ST_PHON", caption:"PHONERA (PHON)" },
  { ticket:"PIL", value:"YAHOO/ST_PIL", caption:"PILUM (PIL)" },
  { ticket:"PLED", value:"YAHOO/ST_PLED", caption:"PLEDPHARMA (PLED)" },
  { ticket:"PREC", value:"YAHOO/ST_PREC", caption:"PRECISE BIOMETRICS (PREC)" },
  { ticket:"PACT", value:"YAHOO/ST_PACT", caption:"PROACT IT GROUP (PACT)" },
  { ticket:"PROB", value:"YAHOO/ST_PROB", caption:"PROBI (PROB)" },
  { ticket:"RAIL", value:"YAHOO/ST_RAIL", caption:"RAILCARE GROUP (RAIL)" },
  { ticket:"RAST", value:"YAHOO/ST_RAST", caption:"RASTA GROUP (RAST)" },
  { ticket:"RABTB", value:"YAHOO/ST_RABTB", caption:"REDERI TRANSANT -B- (RABTB)" },
  { ticket:"RESP", value:"YAHOO/ST_RESP", caption:"RESPIRATORIUS (RESP)" },
  { ticket:"REZT", value:"YAHOO/ST_REZT", caption:"REZIDOR HOTEL GR (REZT)" },
  { ticket:"RLS", value:"YAHOO/ST_RLS", caption:"RLS GLOBAL (RLS)" },
  { ticket:"RNBS", value:"YAHOO/ST_RNBS", caption:"RNB RET AND BRA (RNBS)" },
  { ticket:"RROS", value:"YAHOO/ST_RROS", caption:"ROTTNEROS (RROS)" },
  { ticket:"RUSF", value:"YAHOO/ST_RUSF", caption:"RUSFOREST (RUSF)" },
  { ticket:"SAFE", value:"YAHOO/ST_SAFE", caption:"SAFE AT SEA (SAFE)" },
  { ticket:"SAND", value:"YAHOO/ST_SAND", caption:"SANDVIK  (SAND)" },
  { ticket:"SAS", value:"YAHOO/ST_SAS", caption:"SAS (SAS)" },
  { ticket:"SBOK", value:"YAHOO/ST_SBOK", caption:"SCANDBOOK (SBOK)" },
  { ticket:"SEAM", value:"YAHOO/ST_SEAM", caption:"SEAMLESS DISTR. (SEAM)" },
  { ticket:"SOGH", value:"YAHOO/ST_SOGH", caption:"SELENA OIL & GAS (SOGH)" },
  { ticket:"SMF", value:"YAHOO/ST_SMF", caption:"SEMAFO (SMF)" },
  { ticket:"SEMC", value:"YAHOO/ST_SEMC", caption:"SEMCON (SEMC)" },
  { ticket:"SDET", value:"YAHOO/ST_SDET", caption:"SENSODETECT (SDET)" },
  { ticket:"SENS", value:"YAHOO/ST_SENS", caption:"SENSYS TRAFFIC  (SENS)" },
  { ticket:"SEZI", value:"YAHOO/ST_SEZI", caption:"SENZIME (SEZI)" },
  { ticket:"SERT", value:"YAHOO/ST_SERT", caption:"SERSTECH  (SERT)" },
  { ticket:"SNM", value:"YAHOO/ST_SNM", caption:"SHAMARAN PETROL (SNM)" },
  { ticket:"SINT", value:"YAHOO/ST_SINT", caption:"SINTERCAST (SINT)" },
  { ticket:"SIVE", value:"YAHOO/ST_SIVE", caption:"SIVERS IMA HOLDING (SIVE)" },
  { ticket:"SKMO", value:"YAHOO/ST_SKMO", caption:"SKANE-MOELLAN (SKMO)" },
  { ticket:"SMAQB", value:"YAHOO/ST_SMAQB", caption:"SMARTEQ -B- (SMAQB)" },
  { ticket:"SPAG", value:"YAHOO/ST_SPAG", caption:"SPAGO IMAGING (SPAG)" },
  { ticket:"SPOR", value:"YAHOO/ST_SPOR", caption:"SPORTAMORE (SPOR)" },
  { ticket:"STAR", value:"YAHOO/ST_STAR", caption:"STARBREEZE (STAR)" },
  { ticket:"STIL", value:"YAHOO/ST_STIL", caption:"STILLE (STIL)" },
  { ticket:"STFY", value:"YAHOO/ST_STFY", caption:"STJARNAFYRKANT (STFY)" },
  { ticket:"SVIK", value:"YAHOO/ST_SVIK", caption:"STUDSVIK (SVIK)" },
  { ticket:"SOBI", value:"YAHOO/ST_SOBI", caption:"SWE ORPHAN BIOVITRU (SOBI)" },
  { ticket:"SWMA", value:"YAHOO/ST_SWMA", caption:"SWEDISH MATCH (SWMA)" },
  { ticket:"SYSR", value:"YAHOO/ST_SYSR", caption:"SYSTEMAIR (SYSR)" },
  { ticket:"TAURB", value:"YAHOO/ST_TAURB", caption:"TAURUS ENERGY -B- (TAURB)" },
  { ticket:"TLSN", value:"YAHOO/ST_TLSN", caption:"TELIASONERA (TLSN)" },
  { ticket:"TETY", value:"YAHOO/ST_TETY", caption:"TETHYS OIL (TETY)" },
  { ticket:"TIEN", value:"YAHOO/ST_TIEN", caption:"TIETO CORPORATION (TIEN)" },
  { ticket:"TRAD", value:"YAHOO/ST_TRAD", caption:"TRADEDOUBLER (TRAD)" },
  { ticket:"TRMO", value:"YAHOO/ST_TRMO", caption:"TRANSMODE (TRMO)" },
  { ticket:"TRI", value:"YAHOO/ST_TRI", caption:"TRIBONA (TRI)" },
  { ticket:"TAGR", value:"YAHOO/ST_TAGR", caption:"TRIGON AGRI (TAGR)" },
  { ticket:"TBDY", value:"YAHOO/ST_TBDY", caption:"TRUSTBUDDY INTL (TBDY)" },
  { ticket:"UFLXB", value:"YAHOO/ST_UFLXB", caption:"UNIFLEX -B- (UFLXB)" },
  { ticket:"UMED", value:"YAHOO/ST_UMED", caption:"UNITED MEDIA SWEDEN (UMED)" },
  { ticket:"UTG", value:"YAHOO/ST_UTG", caption:"UNL TRAVEL GROUP (UTG)" },
  { ticket:"VICP", value:"YAHOO/ST_VICP", caption:"VICTORIA PARK (VICP)" },
  { ticket:"VIG", value:"YAHOO/ST_VIG", caption:"VIGMED HOLDING (VIG)" },
  { ticket:"VINO", value:"YAHOO/ST_VINO", caption:"VINOVO (VINO)" },
  { ticket:"VITR", value:"YAHOO/ST_VITR", caption:"VITROLIFE (VITR)" },
  { ticket:"VIVO", value:"YAHOO/ST_VIVO", caption:"VIVOLINE MED (VIVO)" },
  { ticket:"WESC", value:"YAHOO/ST_WESC", caption:"WESC (WESC)" },
  { ticket:"WINT", value:"YAHOO/ST_WINT", caption:"WEST INTERNATIONAL (WINT)" },
  { ticket:"WIHL", value:"YAHOO/ST_WIHL", caption:"WIHLBORGS FASTIGHET (WIHL)" },
  { ticket:"WIKM", value:"YAHOO/ST_WIKM", caption:"WIKING MINERAL (WIKM)" },
  { ticket:"WISE", value:"YAHOO/ST_WISE", caption:"WISE GROUP (WISE)" },
  { ticket:"WNT", value:"YAHOO/ST_WNT", caption:"WNTRESEARCH (WNT)" },
  { ticket:"WTG", value:"YAHOO/ST_WTG", caption:"WTG (WTG)" },
  { ticket:"XTRA", value:"YAHOO/ST_XTRA", caption:"XTRANET GR STO (XTRA)" },
  { ticket:"XVIVO", value:"YAHOO/ST_XVIVO", caption:"XVIVO PERFUSION (XVIVO)" },
  { ticket:"ZETA", value:"YAHOO/ST_ZETA", caption:"ZETADISPLAY (ZETA)" }
];

YahooStockholm.getTickets = function(){
  return tickets;
}

export default YahooStockholm
