
const YahooSingapure = {};

const tickets = [
  { ticket:"5TG", value:"YAHOO/SI_5TG", caption:"$ 800 Super (5TG)" },
  { ticket:"5GZ", value:"YAHOO/SI_5GZ", caption:"$ AA Grp (5GZ)" },
  { ticket:"5RA", value:"YAHOO/SI_5RA", caption:"$ AP Strat (5RA)" },
  { ticket:"5TY", value:"YAHOO/SI_5TY", caption:"$ Adv Sys (5TY)" },
  { ticket:"5EF", value:"YAHOO/SI_5EF", caption:"$ Adventus (5EF)" },
  { ticket:"5IB", value:"YAHOO/SI_5IB", caption:"$ Albedo (5IB)" },
  { ticket:"5AL", value:"YAHOO/SI_5AL", caption:"$ Annica (5AL)" },
  { ticket:"5EK", value:"YAHOO/SI_5EK", caption:"$ Armarda (5EK)" },
  { ticket:"5NK", value:"YAHOO/SI_5NK", caption:"$ Artivision (5NK)" },
  { ticket:"505", value:"YAHOO/SI_505", caption:"$ AsiaMed (505)" },
  { ticket:"585", value:"YAHOO/SI_585", caption:"$ AsianMic (585)" },
  { ticket:"5CR", value:"YAHOO/SI_5CR", caption:"$ Asiatic (5CR)" },
  { ticket:"5AM", value:"YAHOO/SI_5AM", caption:"$ Asiatravel (5AM)" },
  { ticket:"5UL", value:"YAHOO/SI_5UL", caption:"$ Atlantic (5UL)" },
  { ticket:"5DT", value:"YAHOO/SI_5DT", caption:"$ BrightOrient (5DT)" },
  { ticket:"5RF", value:"YAHOO/SI_5RF", caption:"$ CCFH (5RF)" },
  { ticket:"5QZ", value:"YAHOO/SI_5QZ", caption:"$ CCM Group (5QZ)" },
  { ticket:"5EB", value:"YAHOO/SI_5EB", caption:"$ CFM (5EB)" },
  { ticket:"5CJ", value:"YAHOO/SI_5CJ", caption:"$ CGI Group (5CJ)" },
  { ticket:"5TP", value:"YAHOO/SI_5TP", caption:"$ CNMC (5TP)" },
  { ticket:"539", value:"YAHOO/SI_539", caption:"$ CPH (539)" },
  { ticket:"5BI", value:"YAHOO/SI_5BI", caption:"$ CarrierNet (5BI)" },
  { ticket:"530", value:"YAHOO/SI_530", caption:"$ Cedar (530)" },
  { ticket:"5TW", value:"YAHOO/SI_5TW", caption:"$ Chaswood (5TW)" },
  { ticket:"5SY", value:"YAHOO/SI_5SY", caption:"$ Chew's Gp (5SY)" },
  { ticket:"5KK", value:"YAHOO/SI_5KK", caption:"$ China YongS (5KK)" },
  { ticket:"567", value:"YAHOO/SI_567", caption:"$ Colex (567)" },
  { ticket:"5HT", value:"YAHOO/SI_5HT", caption:"$ CommDesign (5HT)" },
  { ticket:"541", value:"YAHOO/SI_541", caption:"$ CraftP (541)" },
  { ticket:"5UZ", value:"YAHOO/SI_5UZ", caption:"$ DeClout (5UZ)" },
  { ticket:"5SO", value:"YAHOO/SI_5SO", caption:"$ DutyFree (5SO)" },
  { ticket:"5DE", value:"YAHOO/SI_5DE", caption:"$ EMS Ener (5DE)" },
  { ticket:"5RC", value:"YAHOO/SI_5RC", caption:"$ ES Group (5RC)" },
  { ticket:"5KX", value:"YAHOO/SI_5KX", caption:"$ Elektromotive (5KX)" },
  { ticket:"5MQ", value:"YAHOO/SI_5MQ", caption:"$ Epicentre (5MQ)" },
  { ticket:"532", value:"YAHOO/SI_532", caption:"$ Equation (532)" },
  { ticket:"H23", value:"YAHOO/SI_H23", caption:"$ EuNetworks (H23)" },
  { ticket:"5TJ", value:"YAHOO/SI_5TJ", caption:"$ Far East Grp (5TJ)" },
  { ticket:"508", value:"YAHOO/SI_508", caption:"$ Fuji Offs (508)" },
  { ticket:"5KT", value:"YAHOO/SI_5KT", caption:"$ FujianZY (5KT)" },
  { ticket:"595", value:"YAHOO/SI_595", caption:"$ GKE Corp (595)" },
  { ticket:"542", value:"YAHOO/SI_542", caption:"$ Giken (542)" },
  { ticket:"5PC", value:"YAHOO/SI_5PC", caption:"$ Goodland (5PC)" },
  { ticket:"502", value:"YAHOO/SI_502", caption:"$ HSR 500 (502)" },
  { ticket:"5PP", value:"YAHOO/SI_5PP", caption:"$ Hafary (5PP)" },
  { ticket:"5VJ", value:"YAHOO/SI_5VJ", caption:"$ Halcyon (5VJ)" },
  { ticket:"5FU", value:"YAHOO/SI_5FU", caption:"$ Hartawan (5FU)" },
  { ticket:"5NG", value:"YAHOO/SI_5NG", caption:"$ Healthway (5NG)" },
  { ticket:"5OR", value:"YAHOO/SI_5OR", caption:"$ Heatec (5OR)" },
  { ticket:"5PD", value:"YAHOO/SI_5PD", caption:"$ Hengyang (5PD)" },
  { ticket:"5PO", value:"YAHOO/SI_5PO", caption:"$ HiapTong (5PO)" },
  { ticket:"5EV", value:"YAHOO/SI_5EV", caption:"$ Hosen (5EV)" },
  { ticket:"5JY", value:"YAHOO/SI_5JY", caption:"$ Hup Soon (5JY)" },
  { ticket:"536", value:"YAHOO/SI_536", caption:"$ ICP (536)" },
  { ticket:"5TN", value:"YAHOO/SI_5TN", caption:"$ IEV (5TN)" },
  { ticket:"571", value:"YAHOO/SI_571", caption:"$ IPSCOM (571)" },
  { ticket:"581", value:"YAHOO/SI_581", caption:"$ ITE (581)" },
  { ticket:"5CS", value:"YAHOO/SI_5CS", caption:"$ Infinio (5CS)" },
  { ticket:"5FA", value:"YAHOO/SI_5FA", caption:"$ JEP (5FA)" },
  { ticket:"5TS", value:"YAHOO/SI_5TS", caption:"$ JK Tech (5TS)" },
  { ticket:"5OI", value:"YAHOO/SI_5OI", caption:"$ JapanFood (5OI)" },
  { ticket:"5PF", value:"YAHOO/SI_5PF", caption:"$ Jason Marine (5PF)" },
  { ticket:"5UU", value:"YAHOO/SI_5UU", caption:"$ Jason Parquet (5UU)" },
  { ticket:"5OS", value:"YAHOO/SI_5OS", caption:"$ Jubilee (5OS)" },
  { ticket:"5TF", value:"YAHOO/SI_5TF", caption:"$ JunmaTyre (5TF)" },
  { ticket:"504", value:"YAHOO/SI_504", caption:"$ KLW (504)" },
  { ticket:"5TT", value:"YAHOO/SI_5TT", caption:"$ Keong Hong (5TT)" },
  { ticket:"5JT", value:"YAHOO/SI_5JT", caption:"$ Kinergy (5JT)" },
  { ticket:"5TI", value:"YAHOO/SI_5TI", caption:"$ KitchenCulture (5TI)" },
  { ticket:"5VC", value:"YAHOO/SI_5VC", caption:"$ Kori (5VC)" },
  { ticket:"5OC", value:"YAHOO/SI_5OC", caption:"$ Koyo (5OC)" },
  { ticket:"5EL", value:"YAHOO/SI_5EL", caption:"$ Lasseters (5EL)" },
  { ticket:"5OY", value:"YAHOO/SI_5OY", caption:"$ Latitude (5OY)" },
  { ticket:"587", value:"YAHOO/SI_587", caption:"$ Lereno (587)" },
  { ticket:"5TR", value:"YAHOO/SI_5TR", caption:"$ Libra (5TR)" },
  { ticket:"5FW", value:"YAHOO/SI_5FW", caption:"$ Linair (5FW)" },
  { ticket:"5VI", value:"YAHOO/SI_5VI", caption:"$ Logistics (5VI)" },
  { ticket:"594", value:"YAHOO/SI_594", caption:"$ LoyzEnergy (594)" },
  { ticket:"576", value:"YAHOO/SI_576", caption:"$ Magnus (576)" },
  { ticket:"5TH", value:"YAHOO/SI_5TH", caption:"$ Malacca Trust (5TH)" },
  { ticket:"5QR", value:"YAHOO/SI_5QR", caption:"$ Mann Seng (5QR)" },
  { ticket:"5OX", value:"YAHOO/SI_5OX", caption:"$ Mary Chia (5OX)" },
  { ticket:"5UF", value:"YAHOO/SI_5UF", caption:"$ Maxi-Cash (5UF)" },
  { ticket:"5FF", value:"YAHOO/SI_5FF", caption:"$ Medi-Flex (5FF)" },
  { ticket:"546", value:"YAHOO/SI_546", caption:"$ Medtecs (546)" },
  { ticket:"5DS", value:"YAHOO/SI_5DS", caption:"$ Megachem (5DS)" },
  { ticket:"5DX", value:"YAHOO/SI_5DX", caption:"$ Metal Comp (5DX)" },
  { ticket:"5HV", value:"YAHOO/SI_5HV", caption:"$ MetaxEngg (5HV)" },
  { ticket:"5BT", value:"YAHOO/SI_5BT", caption:"$ Moya Asia (5BT)" },
  { ticket:"5AC", value:"YAHOO/SI_5AC", caption:"$ NH Ceram (5AC)" },
  { ticket:"5IF", value:"YAHOO/SI_5IF", caption:"$ NatCool (5IF)" },
  { ticket:"5UJ", value:"YAHOO/SI_5UJ", caption:"$ Neo Group (5UJ)" },
  { ticket:"5QY", value:"YAHOO/SI_5QY", caption:"$ NetPac (5QY)" },
  { ticket:"5FX", value:"YAHOO/SI_5FX", caption:"$ New Wave (5FX)" },
  { ticket:"5HC", value:"YAHOO/SI_5HC", caption:"$ Ntegrator (5HC)" },
  { ticket:"584", value:"YAHOO/SI_584", caption:"$ Oakwell (584)" },
  { ticket:"5ML", value:"YAHOO/SI_5ML", caption:"$ OldChangK (5ML)" },
  { ticket:"5HG", value:"YAHOO/SI_5HG", caption:"$ Oniontech (5HG)" },
  { ticket:"5FI", value:"YAHOO/SI_5FI", caption:"$ OrientGrp (5FI)" },
  { ticket:"5UV", value:"YAHOO/SI_5UV", caption:"$ P99 HLDGS (5UV)" },
  { ticket:"5BS", value:"YAHOO/SI_5BS", caption:"$ PNE Micron (5BS)" },
  { ticket:"5EW", value:"YAHOO/SI_5EW", caption:"$ Pan Asian (5EW)" },
  { ticket:"5PI", value:"YAHOO/SI_5PI", caption:"$ PlatoCap (5PI)" },
  { ticket:"5AE", value:"YAHOO/SI_5AE", caption:"$ Pollux (5AE)" },
  { ticket:"583", value:"YAHOO/SI_583", caption:"$ Progen (583)" },
  { ticket:"5DW", value:"YAHOO/SI_5DW", caption:"$ RenewableEne (5DW)" },
  { ticket:"5LU", value:"YAHOO/SI_5LU", caption:"$ Rokko (5LU)" },
  { ticket:"5PL", value:"YAHOO/SI_5PL", caption:"$ SBI Offsh (5PL)" },
  { ticket:"5OT", value:"YAHOO/SI_5OT", caption:"$ SG MEDICAL (5OT)" },
  { ticket:"5UE", value:"YAHOO/SI_5UE", caption:"$ SHC Asia (5UE)" },
  { ticket:"580", value:"YAHOO/SI_580", caption:"$ Santak (580)" },
  { ticket:"5HW", value:"YAHOO/SI_5HW", caption:"$ ScorpioE (5HW)" },
  { ticket:"5FQ", value:"YAHOO/SI_5FQ", caption:"$ Select (5FQ)" },
  { ticket:"5UN", value:"YAHOO/SI_5UN", caption:"$ Sincap (5UN)" },
  { ticket:"5CE", value:"YAHOO/SI_5CE", caption:"$ SingHaiyi (5CE)" },
  { ticket:"5LE", value:"YAHOO/SI_5LE", caption:"$ SitraH (5LE)" },
  { ticket:"5MM", value:"YAHOO/SI_5MM", caption:"$ Sky One (5MM)" },
  { ticket:"5RE", value:"YAHOO/SI_5RE", caption:"$ Smartflex (5RE)" },
  { ticket:"5MD", value:"YAHOO/SI_5MD", caption:"$ SoonLian (5MD)" },
  { ticket:"5NH", value:"YAHOO/SI_5NH", caption:"$ St James (5NH)" },
  { ticket:"5UA", value:"YAHOO/SI_5UA", caption:"$ Starland (5UA)" },
  { ticket:"5AI", value:"YAHOO/SI_5AI", caption:"$ Sunlight (5AI)" },
  { ticket:"5UO", value:"YAHOO/SI_5UO", caption:"$ Sysma (5UO)" },
  { ticket:"586", value:"YAHOO/SI_586", caption:"$ TMC Edu (586)" },
  { ticket:"574", value:"YAHOO/SI_574", caption:"$ TSH (574)" },
  { ticket:"5OQ", value:"YAHOO/SI_5OQ", caption:"$ Teho (5OQ)" },
  { ticket:"5NL", value:"YAHOO/SI_5NL", caption:"$ Tritech (5NL)" },
  { ticket:"540", value:"YAHOO/SI_540", caption:"$ TungLok (540)" },
  { ticket:"545", value:"YAHOO/SI_545", caption:"$ Vallianz (545)" },
  { ticket:"5BA", value:"YAHOO/SI_5BA", caption:"$ Vashion (5BA)" },
  { ticket:"557", value:"YAHOO/SI_557", caption:"$ Viking (557)" },
  { ticket:"5RJ", value:"YAHOO/SI_5RJ", caption:"$ WE Hldgs (5RJ)" },
  { ticket:"5OF", value:"YAHOO/SI_5OF", caption:"$ Westminster (5OF)" },
  { ticket:"5QT", value:"YAHOO/SI_5QT", caption:"$ YHM (5QT)" },
  { ticket:"5SR", value:"YAHOO/SI_5SR", caption:"$ ZhongminBH (5SR)" },
  { ticket:"5EG", value:"YAHOO/SI_5EG", caption:"$ ZhongxinFruit (5EG)" },
  { ticket:"528", value:"YAHOO/SI_528", caption:"2ndChance (528)" },
  { ticket:"E25", value:"YAHOO/SI_E25", caption:"8Telecom (E25)" },
  { ticket:"A53", value:"YAHOO/SI_A53", caption:"A-Sonic (A53)" },
  { ticket:"P1R", value:"YAHOO/SI_P1R", caption:"AAT (P1R)" },
  { ticket:"A35", value:"YAHOO/SI_A35", caption:"ABF SG BOND ETF (A35)" },
  { ticket:"533", value:"YAHOO/SI_533", caption:"ABR (533)" },
  { ticket:"5EZ", value:"YAHOO/SI_5EZ", caption:"ADAMPAK LIMITED NPV (5EZ)" },
  { ticket:"A18", value:"YAHOO/SI_A18", caption:"AEI Corp (A18)" },
  { ticket:"A10", value:"YAHOO/SI_A10", caption:"AEM (A10)" },
  { ticket:"A54", value:"YAHOO/SI_A54", caption:"AIM (A54)" },
  { ticket:"O5RU", value:"YAHOO/SI_O5RU", caption:"AIMSAMPI Reit (O5RU)" },
  { ticket:"5AU", value:"YAHOO/SI_5AU", caption:"AP Oil (5AU)" },
  { ticket:"A46", value:"YAHOO/SI_A46", caption:"APB (A46)" },
  { ticket:"D1R", value:"YAHOO/SI_D1R", caption:"ARA (D1R)" },
  { ticket:"538", value:"YAHOO/SI_538", caption:"ASJ (538)" },
  { ticket:"A04", value:"YAHOO/SI_A04", caption:"ASL Marine (A04)" },
  { ticket:"575", value:"YAHOO/SI_575", caption:"ASTI (575)" },
  { ticket:"A23", value:"YAHOO/SI_A23", caption:"AURIC (A23)" },
  { ticket:"A15", value:"YAHOO/SI_A15", caption:"AUSSINO^ (A15)" },
  { ticket:"O2I", value:"YAHOO/SI_O2I", caption:"AVIC (O2I)" },
  { ticket:"L5I", value:"YAHOO/SI_L5I", caption:"Abterra Ltd (L5I)" },
  { ticket:"A75", value:"YAHOO/SI_A75", caption:"Ace Achieve (A75)" },
  { ticket:"A02", value:"YAHOO/SI_A02", caption:"Achieva (A02)" },
  { ticket:"A59", value:"YAHOO/SI_A59", caption:"ActionAsia (A59)" },
  { ticket:"A31", value:"YAHOO/SI_A31", caption:"AddvalTech (A31)" },
  { ticket:"5FH", value:"YAHOO/SI_5FH", caption:"AdvSCT (5FH)" },
  { ticket:"5IA", value:"YAHOO/SI_5IA", caption:"AdvaHldg (5IA)" },
  { ticket:"A13", value:"YAHOO/SI_A13", caption:"AlliedTech (A13)" },
  { ticket:"A34", value:"YAHOO/SI_A34", caption:"Amara (A34)" },
  { ticket:"C60", value:"YAHOO/SI_C60", caption:"Amplefield (C60)" },
  { ticket:"M1P", value:"YAHOO/SI_M1P", caption:"Amtek (M1P)" },
  { ticket:"MF5", value:"YAHOO/SI_MF5", caption:"Anchun (MF5)" },
  { ticket:"A52", value:"YAHOO/SI_A52", caption:"AnnAik (A52)" },
  { ticket:"G5X", value:"YAHOO/SI_G5X", caption:"AnwellTech (G5X)" },
  { ticket:"A14", value:"YAHOO/SI_A14", caption:"Armstrong (A14)" },
  { ticket:"Q1P", value:"YAHOO/SI_Q1P", caption:"AscendasHT (Q1P)" },
  { ticket:"CY6U", value:"YAHOO/SI_CY6U", caption:"AscendasIndT (CY6U)" },
  { ticket:"A17U", value:"YAHOO/SI_A17U", caption:"Ascendasreit (A17U)" },
  { ticket:"A68U", value:"YAHOO/SI_A68U", caption:"AscottREIT (A68U)" },
  { ticket:"GH3", value:"YAHOO/SI_GH3", caption:"Asia Fashion (GH3)" },
  { ticket:"A55", value:"YAHOO/SI_A55", caption:"AsiaEntH (A55)" },
  { ticket:"A03", value:"YAHOO/SI_A03", caption:"AsiaPower (A03)" },
  { ticket:"5ET", value:"YAHOO/SI_5ET", caption:"Asiasons (5ET)" },
  { ticket:"A30", value:"YAHOO/SI_A30", caption:"Aspial (A30)" },
  { ticket:"5GJ", value:"YAHOO/SI_5GJ", caption:"AusGroup (5GJ)" },
  { ticket:"CT1", value:"YAHOO/SI_CT1", caption:"Avi-Tech (CT1)" },
  { ticket:"A69", value:"YAHOO/SI_A69", caption:"Azeus (A69)" },
  { ticket:"560", value:"YAHOO/SI_560", caption:"Aztech (560)" },
  { ticket:"KJ5", value:"YAHOO/SI_KJ5", caption:"BBR Hldg (KJ5)" },
  { ticket:"B32", value:"YAHOO/SI_B32", caption:"BH Global (B32)" },
  { ticket:"B08", value:"YAHOO/SI_B08", caption:"BMT 100 (B08)" },
  { ticket:"B03", value:"YAHOO/SI_B03", caption:"BRC Asia (B03)" },
  { ticket:"568", value:"YAHOO/SI_568", caption:"BakerTech (568)" },
  { ticket:"B26", value:"YAHOO/SI_B26", caption:"Ban Leong (B26)" },
  { ticket:"B58", value:"YAHOO/SI_B58", caption:"BanyanTree (B58)" },
  { ticket:"5MC", value:"YAHOO/SI_5MC", caption:"Beng Kuang (5MC)" },
  { ticket:"B64", value:"YAHOO/SI_B64", caption:"Berger (B64)" },
  { ticket:"B66", value:"YAHOO/SI_B66", caption:"BerlianLaju (B66)" },
  { ticket:"5ER", value:"YAHOO/SI_5ER", caption:"Best World (5ER)" },
  { ticket:"B20", value:"YAHOO/SI_B20", caption:"Biosensors (B20)" },
  { ticket:"A33", value:"YAHOO/SI_A33", caption:"Blumont (A33)" },
  { ticket:"B10", value:"YAHOO/SI_B10", caption:"Boardroom (B10)" },
  { ticket:"B28", value:"YAHOO/SI_B28", caption:"Bonvests (B28)" },
  { ticket:"F9D", value:"YAHOO/SI_F9D", caption:"Boustead Sp (F9D)" },
  { ticket:"5DA", value:"YAHOO/SI_5DA", caption:"BreadTalk (5DA)" },
  { ticket:"B69", value:"YAHOO/SI_B69", caption:"Broadway (B69)" },
  { ticket:"B61", value:"YAHOO/SI_B61", caption:"BukitSem (B61)" },
  { ticket:"P8Z", value:"YAHOO/SI_P8Z", caption:"Bumitama (P8Z)" },
  { ticket:"MQ4", value:"YAHOO/SI_MQ4", caption:"BundCenter (MQ4)" },
  { ticket:"D79", value:"YAHOO/SI_D79", caption:"C&G EP (D79)" },
  { ticket:"K2LU", value:"YAHOO/SI_K2LU", caption:"CACHE (K2LU)" },
  { ticket:"J85", value:"YAHOO/SI_J85", caption:"CDL HTrust (J85)" },
  { ticket:"D38", value:"YAHOO/SI_D38", caption:"CDW (D38)" },
  { ticket:"Y35", value:"YAHOO/SI_Y35", caption:"CEFC Intl^ (Y35)" },
  { ticket:"C11", value:"YAHOO/SI_C11", caption:"CEI (C11)" },
  { ticket:"C13", value:"YAHOO/SI_C13", caption:"CH Offshore (C13)" },
  { ticket:"592", value:"YAHOO/SI_592", caption:"CHINA HEALTHCARE LIMITED NPV (592)" },
  { ticket:"QR9", value:"YAHOO/SI_QR9", caption:"CIMB APAC Div 100S$D (QR9)" },
  { ticket:"P5P", value:"YAHOO/SI_P5P", caption:"CIMB APAC Div 100US$ (P5P)" },
  { ticket:"M62", value:"YAHOO/SI_M62", caption:"CIMBASEAN40 100US$ (M62)" },
  { ticket:"C09", value:"YAHOO/SI_C09", caption:"CITYDEV (C09)" },
  { ticket:"C70", value:"YAHOO/SI_C70", caption:"CITYDEV NCCPS (C70)" },
  { ticket:"JA9", value:"YAHOO/SI_JA9", caption:"CJFertilizer (JA9)" },
  { ticket:"C22", value:"YAHOO/SI_C22", caption:"CMPacific (C22)" },
  { ticket:"C03", value:"YAHOO/SI_C03", caption:"CMProp 100 HK$ (C03)" },
  { ticket:"5GC", value:"YAHOO/SI_5GC", caption:"CNA (5GC)" },
  { ticket:"C06", value:"YAHOO/SI_C06", caption:"CSC (C06)" },
  { ticket:"544", value:"YAHOO/SI_544", caption:"CSE Global (544)" },
  { ticket:"C14", value:"YAHOO/SI_C14", caption:"CWT (C14)" },
  { ticket:"D2U", value:"YAHOO/SI_D2U", caption:"Cacola (D2U)" },
  { ticket:"J91U", value:"YAHOO/SI_J91U", caption:"Cambridge (J91U)" },
  { ticket:"JS8", value:"YAHOO/SI_JS8", caption:"CapMallsAsia (JS8)" },
  { ticket:"C61U", value:"YAHOO/SI_C61U", caption:"CapitaComm (C61U)" },
  { ticket:"C38U", value:"YAHOO/SI_C38U", caption:"CapitaMall (C38U)" },
  { ticket:"AU8U", value:"YAHOO/SI_AU8U", caption:"CapitaRChina (AU8U)" },
  { ticket:"C31", value:"YAHOO/SI_C31", caption:"Capitaland (C31)" },
  { ticket:"C04", value:"YAHOO/SI_C04", caption:"Casa (C04)" },
  { ticket:"C56", value:"YAHOO/SI_C56", caption:"Celestial (C56)" },
  { ticket:"OU8", value:"YAHOO/SI_OU8", caption:"Centurion (OU8)" },
  { ticket:"573", value:"YAHOO/SI_573", caption:"Challenger (573)" },
  { ticket:"D2V", value:"YAHOO/SI_D2V", caption:"Changtian (D2V)" },
  { ticket:"5NV", value:"YAHOO/SI_5NV", caption:"ChasenHldg (5NV)" },
  { ticket:"C05", value:"YAHOO/SI_C05", caption:"ChemInd (C05)" },
  { ticket:"AV5", value:"YAHOO/SI_AV5", caption:"Chemoil US$ (AV5)" },
  { ticket:"C50", value:"YAHOO/SI_C50", caption:"CheungWoh (C50)" },
  { ticket:"T16", value:"YAHOO/SI_T16", caption:"China Dairy (T16)" },
  { ticket:"A8J", value:"YAHOO/SI_A8J", caption:"China Farm (A8J)" },
  { ticket:"B0Z", value:"YAHOO/SI_B0Z", caption:"China Fish (B0Z)" },
  { ticket:"D50", value:"YAHOO/SI_D50", caption:"China Great (D50)" },
  { ticket:"C92", value:"YAHOO/SI_C92", caption:"China Haida (C92)" },
  { ticket:"BR9", value:"YAHOO/SI_BR9", caption:"China Hongx (BR9)" },
  { ticket:"C37", value:"YAHOO/SI_C37", caption:"China Intl (C37)" },
  { ticket:"Y34", value:"YAHOO/SI_Y34", caption:"China Mining (Y34)" },
  { ticket:"C71", value:"YAHOO/SI_C71", caption:"China Paper (C71)" },
  { ticket:"Z02", value:"YAHOO/SI_Z02", caption:"China Powerpl^ (Z02)" },
  { ticket:"E90", value:"YAHOO/SI_E90", caption:"China Sky (E90)" },
  { ticket:"FQ8", value:"YAHOO/SI_FQ8", caption:"China Sports (FQ8)" },
  { ticket:"C86", value:"YAHOO/SI_C86", caption:"China Sun (C86)" },
  { ticket:"B9R", value:"YAHOO/SI_B9R", caption:"China XLX (B9R)" },
  { ticket:"A01", value:"YAHOO/SI_A01", caption:"ChinaACorp (A01)" },
  { ticket:"T42", value:"YAHOO/SI_T42", caption:"ChinaAElec (T42)" },
  { ticket:"G92", value:"YAHOO/SI_G92", caption:"ChinaAOil (G92)" },
  { ticket:"EP4", value:"YAHOO/SI_EP4", caption:"ChinaAniH (EP4)" },
  { ticket:"AD7", value:"YAHOO/SI_AD7", caption:"ChinaBearing (AD7)" },
  { ticket:"A0G", value:"YAHOO/SI_A0G", caption:"ChinaEnergy (A0G)" },
  { ticket:"5OU", value:"YAHOO/SI_5OU", caption:"ChinaEnv (5OU)" },
  { ticket:"RS1", value:"YAHOO/SI_RS1", caption:"ChinaEnvRes 4k (RS1)" },
  { ticket:"G54", value:"YAHOO/SI_G54", caption:"ChinaEssen (G54)" },
  { ticket:"F6D", value:"YAHOO/SI_F6D", caption:"ChinaFibreT (F6D)" },
  { ticket:"C59", value:"YAHOO/SI_C59", caption:"ChinaFlexP (C59)" },
  { ticket:"I4U", value:"YAHOO/SI_I4U", caption:"ChinaGaoxian (I4U)" },
  { ticket:"C0Z", value:"YAHOO/SI_C0Z", caption:"ChinaHongc (C0Z)" },
  { ticket:"J18", value:"YAHOO/SI_J18", caption:"ChinaJishan (J18)" },
  { ticket:"P74", value:"YAHOO/SI_P74", caption:"ChinaKangda (P74)" },
  { ticket:"GU5", value:"YAHOO/SI_GU5", caption:"ChinaKunda (GU5)" },
  { ticket:"G86", value:"YAHOO/SI_G86", caption:"ChinaMilk (G86)" },
  { ticket:"K2N", value:"YAHOO/SI_K2N", caption:"ChinaMinzhong (K2N)" },
  { ticket:"D4N", value:"YAHOO/SI_D4N", caption:"ChinaNTown (D4N)" },
  { ticket:"DT2", value:"YAHOO/SI_DT2", caption:"ChinaOilFld^ (DT2)" },
  { ticket:"B3C", value:"YAHOO/SI_B3C", caption:"ChinaPrtP (B3C)" },
  { ticket:"CH8", value:"YAHOO/SI_CH8", caption:"ChinaSsine (CH8)" },
  { ticket:"F2X", value:"YAHOO/SI_F2X", caption:"ChinaTaisan (F2X)" },
  { ticket:"S91", value:"YAHOO/SI_S91", caption:"ChinaVision 2k HK$ (S91)" },
  { ticket:"B2X", value:"YAHOO/SI_B2X", caption:"ChinaYuanb (B2X)" },
  { ticket:"O2R", value:"YAHOO/SI_O2R", caption:"Chinasing Inv (O2R)" },
  { ticket:"C29", value:"YAHOO/SI_C29", caption:"ChipEngS (C29)" },
  { ticket:"C10", value:"YAHOO/SI_C10", caption:"Chosen (C10)" },
  { ticket:"C33", value:"YAHOO/SI_C33", caption:"ChuanHup (C33)" },
  { ticket:"A7RU", value:"YAHOO/SI_A7RU", caption:"CitySpring (A7RU)" },
  { ticket:"5HJ", value:"YAHOO/SI_5HJ", caption:"Cityneon (5HJ)" },
  { ticket:"P9D", value:"YAHOO/SI_P9D", caption:"Civmec (P9D)" },
  { ticket:"KJ9", value:"YAHOO/SI_KJ9", caption:"Cogent (KJ9)" },
  { ticket:"N0Z", value:"YAHOO/SI_N0Z", caption:"CombWill 100 (N0Z)" },
  { ticket:"C52", value:"YAHOO/SI_C52", caption:"ComfortDelGro (C52)" },
  { ticket:"C02", value:"YAHOO/SI_C02", caption:"Compact (C02)" },
  { ticket:"OJ4", value:"YAHOO/SI_OJ4", caption:"Contel Corp (OJ4)" },
  { ticket:"P8A", value:"YAHOO/SI_P8A", caption:"Cordlife (P8A)" },
  { ticket:"C41", value:"YAHOO/SI_C41", caption:"Cortina (C41)" },
  { ticket:"F83", value:"YAHOO/SI_F83", caption:"CoscoCorp (F83)" },
  { ticket:"B9S", value:"YAHOO/SI_B9S", caption:"Cosmosteel (B9S)" },
  { ticket:"E91", value:"YAHOO/SI_E91", caption:"CourageMa (E91)" },
  { ticket:"RE2", value:"YAHOO/SI_RE2", caption:"CourtsAsia (RE2)" },
  { ticket:"C35", value:"YAHOO/SI_C35", caption:"CreativMast^ (C35)" },
  { ticket:"C76", value:"YAHOO/SI_C76", caption:"Creative 50 (C76)" },
  { ticket:"F1F", value:"YAHOO/SI_F1F", caption:"DAIWA FTSE SHARIAH JAPAN 100 DA (F1F)" },
  { ticket:"D05", value:"YAHOO/SI_D05", caption:"DBS (D05)" },
  { ticket:"MU7", value:"YAHOO/SI_MU7", caption:"DBS Bk 4.7% NCPS 100 (MU7)" },
  { ticket:"LF1", value:"YAHOO/SI_LF1", caption:"DBXT ASX200 10US$ (LF1)" },
  { ticket:"K6Y", value:"YAHOO/SI_K6Y", caption:"DBXT AUDBonds 5AU$ (K6Y)" },
  { ticket:"KV5", value:"YAHOO/SI_KV5", caption:"DBXT AUDCS 5AU$ (KV5)" },
  { ticket:"KV7", value:"YAHOO/SI_KV7", caption:"DBXT AUDCS 5SG$ (KV7)" },
  { ticket:"KV6", value:"YAHOO/SI_KV6", caption:"DBXT AUDCS 5US$ (KV6)" },
  { ticket:"KT4", value:"YAHOO/SI_KT4", caption:"DBXT CSI300 10US$ (KT4)" },
  { ticket:"HD8", value:"YAHOO/SI_HD8", caption:"DBXT China25 10US$ (HD8)" },
  { ticket:"L5G", value:"YAHOO/SI_L5G", caption:"DBXT DBCBLEB 10US$ (L5G)" },
  { ticket:"L5F", value:"YAHOO/SI_L5F", caption:"DBXT DBCDJUBS10US$ (L5F)" },
  { ticket:"J0S", value:"YAHOO/SI_J0S", caption:"DBXT DBLCI-OY 5US$ (J0S)" },
  { ticket:"IH0", value:"YAHOO/SI_IH0", caption:"DBXT E50 10US$ (IH0)" },
  { ticket:"KV8", value:"YAHOO/SI_KV8", caption:"DBXT EONIA 5US$ (KV8)" },
  { ticket:"O9A", value:"YAHOO/SI_O9A", caption:"DBXT MS SING 10US$ (O9A)" },
  { ticket:"O9B", value:"YAHOO/SI_O9B", caption:"DBXT MSASPAC 10US$ (O9B)" },
  { ticket:"N2F", value:"YAHOO/SI_N2F", caption:"DBXT MSAXJHDY10US$ (N2F)" },
  { ticket:"IH1", value:"YAHOO/SI_IH1", caption:"DBXT MSAsExJp10US$ (IH1)" },
  { ticket:"O9C", value:"YAHOO/SI_O9C", caption:"DBXT MSBANGL 10US$ (O9C)" },
  { ticket:"J0O", value:"YAHOO/SI_J0O", caption:"DBXT MSBrazil10US$ (J0O)" },
  { ticket:"LG9", value:"YAHOO/SI_LG9", caption:"DBXT MSCHINA 10US$ (LG9)" },
  { ticket:"J0N", value:"YAHOO/SI_J0N", caption:"DBXT MSEMAsia10US$ (J0N)" },
  { ticket:"J0M", value:"YAHOO/SI_J0M", caption:"DBXT MSEmer 10US$ (J0M)" },
  { ticket:"IH3", value:"YAHOO/SI_IH3", caption:"DBXT MSEurope10US$ (IH3)" },
  { ticket:"LG8", value:"YAHOO/SI_LG8", caption:"DBXT MSINDIA 10US$ (LG8)" },
  { ticket:"KJ7", value:"YAHOO/SI_KJ7", caption:"DBXT MSINDO 10US$ (KJ7)" },
  { ticket:"LF2", value:"YAHOO/SI_LF2", caption:"DBXT MSJAP 10US$ (LF2)" },
  { ticket:"IH2", value:"YAHOO/SI_IH2", caption:"DBXT MSKorea 10US$ (IH2)" },
  { ticket:"LG6", value:"YAHOO/SI_LG6", caption:"DBXT MSMSIA 10US$ (LG6)" },
  { ticket:"O9D", value:"YAHOO/SI_O9D", caption:"DBXT MSPAKIS 10US$ (O9D)" },
  { ticket:"N2E", value:"YAHOO/SI_N2E", caption:"DBXT MSPHILS 10US$ (N2E)" },
  { ticket:"J0Q", value:"YAHOO/SI_J0Q", caption:"DBXT MSPacXJp10US$ (J0Q)" },
  { ticket:"J0R", value:"YAHOO/SI_J0R", caption:"DBXT MSRussia10US$ (J0R)" },
  { ticket:"LG7", value:"YAHOO/SI_LG7", caption:"DBXT MSTHAI 10US$ (LG7)" },
  { ticket:"HD7", value:"YAHOO/SI_HD7", caption:"DBXT MSTaiwan10US$ (HD7)" },
  { ticket:"KF8", value:"YAHOO/SI_KF8", caption:"DBXT MSUSA 10US$ (KF8)" },
  { ticket:"J0P", value:"YAHOO/SI_J0P", caption:"DBXT MSWorld 10US$ (J0P)" },
  { ticket:"HE0", value:"YAHOO/SI_HE0", caption:"DBXT Nifty 10US$ (HE0)" },
  { ticket:"K6K", value:"YAHOO/SI_K6K", caption:"DBXT S&P500 10US$ (K6K)" },
  { ticket:"HD6", value:"YAHOO/SI_HD6", caption:"DBXT S&PShort10US$ (HD6)" },
  { ticket:"KJ6", value:"YAHOO/SI_KJ6", caption:"DBXT SORA 5SG$ (KJ6)" },
  { ticket:"KT3", value:"YAHOO/SI_KT3", caption:"DBXT STGLDv 10US$ (KT3)" },
  { ticket:"IH4", value:"YAHOO/SI_IH4", caption:"DBXT USDCS 5US$ (IH4)" },
  { ticket:"KF5", value:"YAHOO/SI_KF5", caption:"DBXT USDIGInfl5US$ (KF5)" },
  { ticket:"HD9", value:"YAHOO/SI_HD9", caption:"DBXT Vietnam 10US$ (HD9)" },
  { ticket:"KT2", value:"YAHOO/SI_KT2", caption:"DBXT iBoxxKR 5US$ (KT2)" },
  { ticket:"KV4", value:"YAHOO/SI_KV4", caption:"DBXT iBoxxSing5SG$ (KV4)" },
  { ticket:"KF6", value:"YAHOO/SI_KF6", caption:"DBXT iBoxxSvEu5US$ (KF6)" },
  { ticket:"KF7", value:"YAHOO/SI_KF7", caption:"DBXT iBoxxUSTr5US$ (KF7)" },
  { ticket:"5CH", value:"YAHOO/SI_5CH", caption:"DMX Tech (5CH)" },
  { ticket:"B2W", value:"YAHOO/SI_B2W", caption:"DTAC 200US$ (B2W)" },
  { ticket:"D01", value:"YAHOO/SI_D01", caption:"DairyFarm 900 US$ (D01)" },
  { ticket:"FP1", value:"YAHOO/SI_FP1", caption:"Dapai (FP1)" },
  { ticket:"5CB", value:"YAHOO/SI_5CB", caption:"Darco (5CB)" },
  { ticket:"D04", value:"YAHOO/SI_D04", caption:"Datapulse (D04)" },
  { ticket:"K2M", value:"YAHOO/SI_K2M", caption:"Debao (K2M)" },
  { ticket:"D03", value:"YAHOO/SI_D03", caption:"Del Monte (D03)" },
  { ticket:"B1N", value:"YAHOO/SI_B1N", caption:"DelongH (B1N)" },
  { ticket:"D11", value:"YAHOO/SI_D11", caption:"Des Studio (D11)" },
  { ticket:"D08", value:"YAHOO/SI_D08", caption:"Devotion (D08)" },
  { ticket:"G77", value:"YAHOO/SI_G77", caption:"Digiland^ (G77)" },
  { ticket:"MT1", value:"YAHOO/SI_MT1", caption:"Dragon Gp (MT1)" },
  { ticket:"GJ8", value:"YAHOO/SI_GJ8", caption:"Dukang (GJ8)" },
  { ticket:"CZ4", value:"YAHOO/SI_CZ4", caption:"Dutech (CZ4)" },
  { ticket:"NO4", value:"YAHOO/SI_NO4", caption:"Dyna-Mac (NO4)" },
  { ticket:"D6U", value:"YAHOO/SI_D6U", caption:"Dynamic (D6U)" },
  { ticket:"E18", value:"YAHOO/SI_E18", caption:"ECS (E18)" },
  { ticket:"N0L", value:"YAHOO/SI_N0L", caption:"EastGateTech (N0L)" },
  { ticket:"5KU", value:"YAHOO/SI_5KU", caption:"EasternH (5KU)" },
  { ticket:"5CT", value:"YAHOO/SI_5CT", caption:"EcoWise (5CT)" },
  { ticket:"E16", value:"YAHOO/SI_E16", caption:"Elec US$ (E16)" },
  { ticket:"550", value:"YAHOO/SI_550", caption:"Elite KSB (550)" },
  { ticket:"E13", value:"YAHOO/SI_E13", caption:"Ellipsiz (E13)" },
  { ticket:"S44", value:"YAHOO/SI_S44", caption:"EnGro Corp (S44)" },
  { ticket:"L23", value:"YAHOO/SI_L23", caption:"Enviro-Hub (L23)" },
  { ticket:"FO8", value:"YAHOO/SI_FO8", caption:"Eratat (FO8)" },
  { ticket:"5FR", value:"YAHOO/SI_5FR", caption:"Etika (5FR)" },
  { ticket:"E02", value:"YAHOO/SI_E02", caption:"EuYanSang (E02)" },
  { ticket:"E27", value:"YAHOO/SI_E27", caption:"Eucon (E27)" },
  { ticket:"E23", value:"YAHOO/SI_E23", caption:"Europtron (E23)" },
  { ticket:"E17", value:"YAHOO/SI_E17", caption:"Excelpoint (E17)" },
  { ticket:"5DN", value:"YAHOO/SI_5DN", caption:"Ezra (5DN)" },
  { ticket:"F99", value:"YAHOO/SI_F99", caption:"F & N (F99)" },
  { ticket:"F07", value:"YAHOO/SI_F07", caption:"FDS Netw^ (F07)" },
  { ticket:"O10", value:"YAHOO/SI_O10", caption:"FEOrchard (O10)" },
  { ticket:"F10", value:"YAHOO/SI_F10", caption:"FJBen (F10)" },
  { ticket:"D8DU", value:"YAHOO/SI_D8DU", caption:"FSL Trust (D8DU)" },
  { ticket:"I54", value:"YAHOO/SI_I54", caption:"Fabchem (I54)" },
  { ticket:"5FL", value:"YAHOO/SI_5FL", caption:"FalconEne (5FL)" },
  { ticket:"Q5T", value:"YAHOO/SI_Q5T", caption:"Far East HTrust (Q5T)" },
  { ticket:"F20", value:"YAHOO/SI_F20", caption:"Federal^ (F20)" },
  { ticket:"F12", value:"YAHOO/SI_F12", caption:"FibreChem (F12)" },
  { ticket:"DK2", value:"YAHOO/SI_DK2", caption:"FibreChem NCPS (DK2)" },
  { ticket:"AW9U", value:"YAHOO/SI_AW9U", caption:"First REIT (AW9U)" },
  { ticket:"EB5", value:"YAHOO/SI_EB5", caption:"FirstRes (EB5)" },
  { ticket:"F22", value:"YAHOO/SI_F22", caption:"Fischer (F22)" },
  { ticket:"529", value:"YAHOO/SI_529", caption:"Food Junc (529)" },
  { ticket:"F03", value:"YAHOO/SI_F03", caption:"FoodEmpire (F03)" },
  { ticket:"B0I", value:"YAHOO/SI_B0I", caption:"Foreland (B0I)" },
  { ticket:"LG2U", value:"YAHOO/SI_LG2U", caption:"ForterraTr (LG2U)" },
  { ticket:"F25U", value:"YAHOO/SI_F25U", caption:"Fortune Reit HK$ (F25U)" },
  { ticket:"F31", value:"YAHOO/SI_F31", caption:"Fragrance (F31)" },
  { ticket:"ND8U", value:"YAHOO/SI_ND8U", caption:"Frasers Comm (ND8U)" },
  { ticket:"RB4", value:"YAHOO/SI_RB4", caption:"Frasers Comm A (RB4)" },
  { ticket:"KT8U", value:"YAHOO/SI_KT8U", caption:"Frasers CommCPPU 500 (KT8U)" },
  { ticket:"J69U", value:"YAHOO/SI_J69U", caption:"FrasersCT (J69U)" },
  { ticket:"F01", value:"YAHOO/SI_F01", caption:"FreightLinks (F01)" },
  { ticket:"E28", value:"YAHOO/SI_E28", caption:"Frencken (E28)" },
  { ticket:"F13", value:"YAHOO/SI_F13", caption:"Fu Yu (F13)" },
  { ticket:"F18", value:"YAHOO/SI_F18", caption:"Full Apex (F18)" },
  { ticket:"F11", value:"YAHOO/SI_F11", caption:"Fung Choi (F11)" },
  { ticket:"DC9", value:"YAHOO/SI_DC9", caption:"Fuxing (DC9)" },
  { ticket:"QS9", value:"YAHOO/SI_QS9", caption:"G Invacom (QS9)" },
  { ticket:"G41", value:"YAHOO/SI_G41", caption:"G K Goh (G41)" },
  { ticket:"O87", value:"YAHOO/SI_O87", caption:"GLD 10US$ (O87)" },
  { ticket:"MC0", value:"YAHOO/SI_MC0", caption:"GLP (MC0)" },
  { ticket:"5IM", value:"YAHOO/SI_5IM", caption:"GMG (5IM)" },
  { ticket:"G08", value:"YAHOO/SI_G08", caption:"GP Bat (G08)" },
  { ticket:"P9J", value:"YAHOO/SI_P9J", caption:"GP Hotels (P9J)" },
  { ticket:"G20", value:"YAHOO/SI_G20", caption:"GP Ind (G20)" },
  { ticket:"G18", value:"YAHOO/SI_G18", caption:"GRP (G18)" },
  { ticket:"J16", value:"YAHOO/SI_J16", caption:"GSH Corp (J16)" },
  { ticket:"5IG", value:"YAHOO/SI_5IG", caption:"Gallant (5IG)" },
  { ticket:"RF7", value:"YAHOO/SI_RF7", caption:"Gaylin (RF7)" },
  { ticket:"Y07", value:"YAHOO/SI_Y07", caption:"GblYellowPgs (Y07)" },
  { ticket:"AM3", value:"YAHOO/SI_AM3", caption:"Gems TV^ (AM3)" },
  { ticket:"G13", value:"YAHOO/SI_G13", caption:"Genting SP (G13)" },
  { ticket:"RE4", value:"YAHOO/SI_RE4", caption:"Geo Energy (RE4)" },
  { ticket:"G11", value:"YAHOO/SI_G11", caption:"Globa (G11)" },
  { ticket:"K6J", value:"YAHOO/SI_K6J", caption:"Global Palm (K6J)" },
  { ticket:"B73", value:"YAHOO/SI_B73", caption:"GlobalInv (B73)" },
  { ticket:"G31", value:"YAHOO/SI_G31", caption:"GlobalTest (G31)" },
  { ticket:"KU3", value:"YAHOO/SI_KU3", caption:"Golden Ocean (KU3)" },
  { ticket:"E5H", value:"YAHOO/SI_E5H", caption:"GoldenAgr (E5H)" },
  { ticket:"G05", value:"YAHOO/SI_G05", caption:"Goodpack (G05)" },
  { ticket:"G50", value:"YAHOO/SI_G50", caption:"GrandBanks^ (G50)" },
  { ticket:"I5H", value:"YAHOO/SI_I5H", caption:"Great Group (I5H)" },
  { ticket:"G07", value:"YAHOO/SI_G07", caption:"GreatEast (G07)" },
  { ticket:"G21", value:"YAHOO/SI_G21", caption:"GuangzhaoIFB (G21)" },
  { ticket:"G09", value:"YAHOO/SI_G09", caption:"GulTech (G09)" },
  { ticket:"F17", value:"YAHOO/SI_F17", caption:"GuocoLand (F17)" },
  { ticket:"B16", value:"YAHOO/SI_B16", caption:"GuocoLeisure (B16)" },
  { ticket:"G33", value:"YAHOO/SI_G33", caption:"GuthrieG (G33)" },
  { ticket:"5SS", value:"YAHOO/SI_5SS", caption:"HARRYS HOLDINGS LTD NPV (5SS)" },
  { ticket:"I85", value:"YAHOO/SI_I85", caption:"HENGXIN TECHNOLOGY LTD NPV (I85)" },
  { ticket:"526", value:"YAHOO/SI_526", caption:"HG Metal (526)" },
  { ticket:"FV2", value:"YAHOO/SI_FV2", caption:"HISAKA (FV2)" },
  { ticket:"H78", value:"YAHOO/SI_H78", caption:"HKLand US$ (H78)" },
  { ticket:"H22", value:"YAHOO/SI_H22", caption:"HL Asia (H22)" },
  { ticket:"S41", value:"YAHOO/SI_S41", caption:"HL Fin (S41)" },
  { ticket:"L18", value:"YAHOO/SI_L18", caption:"HL Global (L18)" },
  { ticket:"H27", value:"YAHOO/SI_H27", caption:"HLH (H27)" },
  { ticket:"5HH", value:"YAHOO/SI_5HH", caption:"HLN Tech (5HH)" },
  { ticket:"588", value:"YAHOO/SI_588", caption:"HMI (588)" },
  { ticket:"NS8U", value:"YAHOO/SI_NS8U", caption:"HPH Trust US$ (NS8U)" },
  { ticket:"H15", value:"YAHOO/SI_H15", caption:"HPL (H15)" },
  { ticket:"H64", value:"YAHOO/SI_H64", caption:"HTL Int (H64)" },
  { ticket:"GG7", value:"YAHOO/SI_GG7", caption:"Hai Leck (GG7)" },
  { ticket:"B22", value:"YAHOO/SI_B22", caption:"HanKore (B22)" },
  { ticket:"DM0", value:"YAHOO/SI_DM0", caption:"Hanwell (DM0)" },
  { ticket:"H02", value:"YAHOO/SI_H02", caption:"Haw Par (H02)" },
  { ticket:"5DP", value:"YAHOO/SI_5DP", caption:"Heeton (5DP)" },
  { ticket:"H28", value:"YAHOO/SI_H28", caption:"Hersing (H28)" },
  { ticket:"H17", value:"YAHOO/SI_H17", caption:"Hi-P (H17)" },
  { ticket:"5JK", value:"YAHOO/SI_5JK", caption:"Hiap Hoe (5JK)" },
  { ticket:"510", value:"YAHOO/SI_510", caption:"Hiap Seng (510)" },
  { ticket:"H13", value:"YAHOO/SI_H13", caption:"Ho Bee (H13)" },
  { ticket:"H12", value:"YAHOO/SI_H12", caption:"Ho Royal (H12)" },
  { ticket:"H18", value:"YAHOO/SI_H18", caption:"HoGCen (H18)" },
  { ticket:"J2T", value:"YAHOO/SI_J2T", caption:"HockLianSeng (J2T)" },
  { ticket:"H20", value:"YAHOO/SI_H20", caption:"Hoe Leong (H20)" },
  { ticket:"H30", value:"YAHOO/SI_H30", caption:"HongFok (H30)" },
  { ticket:"H80", value:"YAHOO/SI_H80", caption:"Hongwei (H80)" },
  { ticket:"H06", value:"YAHOO/SI_H06", caption:"Hor Kew (H06)" },
  { ticket:"NT1", value:"YAHOO/SI_NT1", caption:"Hotung (NT1)" },
  { ticket:"E5P", value:"YAHOO/SI_E5P", caption:"HrGlass (E5P)" },
  { ticket:"KI3", value:"YAHOO/SI_KI3", caption:"Hu An (KI3)" },
  { ticket:"H16", value:"YAHOO/SI_H16", caption:"HuanHsin (H16)" },
  { ticket:"H73", value:"YAHOO/SI_H73", caption:"HupSteel (H73)" },
  { ticket:"H19", value:"YAHOO/SI_H19", caption:"HwaHong (H19)" },
  { ticket:"600", value:"YAHOO/SI_600", caption:"Hyflux (600)" },
  { ticket:"N2H", value:"YAHOO/SI_N2H", caption:"Hyflux 6% CPS 10 (N2H)" },
  { ticket:"I49", value:"YAHOO/SI_I49", caption:"IFS (I49)" },
  { ticket:"Q0F", value:"YAHOO/SI_Q0F", caption:"IHH (Q0F)" },
  { ticket:"I12", value:"YAHOO/SI_I12", caption:"IPC Corp (I12)" },
  { ticket:"QL2", value:"YAHOO/SI_QL2", caption:"IS ASIA BND 100S$D (QL2)" },
  { ticket:"N6M", value:"YAHOO/SI_N6M", caption:"IS ASIA BND 100US$ (N6M)" },
  { ticket:"QL3", value:"YAHOO/SI_QL3", caption:"IS ASIA HYG100S$D (QL3)" },
  { ticket:"O9P", value:"YAHOO/SI_O9P", caption:"IS ASIA HYG100US$ (O9P)" },
  { ticket:"I21", value:"YAHOO/SI_I21", caption:"IS DJ USTECH 10US$ (I21)" },
  { ticket:"QL0", value:"YAHOO/SI_QL0", caption:"IS LC 1-3Y 100S$D (QL0)" },
  { ticket:"O9Q", value:"YAHOO/SI_O9Q", caption:"IS LC 1-3Y 100US$ (O9Q)" },
  { ticket:"QL1", value:"YAHOO/SI_QL1", caption:"IS LC BND 100S$D (QL1)" },
  { ticket:"N6L", value:"YAHOO/SI_N6L", caption:"IS LC BND 100US$ (N6L)" },
  { ticket:"QK9", value:"YAHOO/SI_QK9", caption:"IS MS INDIA 100S$D (QK9)" },
  { ticket:"I98", value:"YAHOO/SI_I98", caption:"IS MS INDIA 100US$ (I98)" },
  { ticket:"I19", value:"YAHOO/SI_I19", caption:"IS MSCI SIN 100US$ (I19)" },
  { ticket:"I17", value:"YAHOO/SI_I17", caption:"IS S&P500 10US$ (I17)" },
  { ticket:"I07", value:"YAHOO/SI_I07", caption:"ISDN (I07)" },
  { ticket:"5EC", value:"YAHOO/SI_5EC", caption:"ISR (5EC)" },
  { ticket:"N6H", value:"YAHOO/SI_N6H", caption:"ITech Grp (N6H)" },
  { ticket:"F3EU", value:"YAHOO/SI_F3EU", caption:"Indiabulls (F3EU)" },
  { ticket:"5JS", value:"YAHOO/SI_5JS", caption:"IndoAgri (5JS)" },
  { ticket:"I03", value:"YAHOO/SI_I03", caption:"Informatics (I03)" },
  { ticket:"M14", value:"YAHOO/SI_M14", caption:"InnoTek (M14)" },
  { ticket:"I26", value:"YAHOO/SI_I26", caption:"Innopac (I26)" },
  { ticket:"591", value:"YAHOO/SI_591", caption:"Innovalu (591)" },
  { ticket:"5GI", value:"YAHOO/SI_5GI", caption:"Interra Res (5GI)" },
  { ticket:"I06", value:"YAHOO/SI_I06", caption:"Intraco (I06)" },
  { ticket:"I11", value:"YAHOO/SI_I11", caption:"Ipco (I11)" },
  { ticket:"I15", value:"YAHOO/SI_I15", caption:"Isetan(S) (I15)" },
  { ticket:"Q0W", value:"YAHOO/SI_Q0W", caption:"JB Foods (Q0W)" },
  { ticket:"EG0", value:"YAHOO/SI_EG0", caption:"JES (EG0)" },
  { ticket:"J36", value:"YAHOO/SI_J36", caption:"JMH 400US$ (J36)" },
  { ticket:"J37", value:"YAHOO/SI_J37", caption:"JSH 500US$ (J37)" },
  { ticket:"J11", value:"YAHOO/SI_J11", caption:"JacksInt (J11)" },
  { ticket:"J17", value:"YAHOO/SI_J17", caption:"Jackspeed (J17)" },
  { ticket:"J03", value:"YAHOO/SI_J03", caption:"Jadason (J03)" },
  { ticket:"C07", value:"YAHOO/SI_C07", caption:"Jardine C&C (C07)" },
  { ticket:"FQ7", value:"YAHOO/SI_FQ7", caption:"JasperInv (FQ7)" },
  { ticket:"J10", value:"YAHOO/SI_J10", caption:"Jaya Hldg (J10)" },
  { ticket:"C8R", value:"YAHOO/SI_C8R", caption:"JiutianC (C8R)" },
  { ticket:"E9L", value:"YAHOO/SI_E9L", caption:"Joyas (E9L)" },
  { ticket:"J15", value:"YAHOO/SI_J15", caption:"Juken Tech (J15)" },
  { ticket:"LH4U", value:"YAHOO/SI_LH4U", caption:"K-Green (LH4U)" },
  { ticket:"K01", value:"YAHOO/SI_K01", caption:"K1 Ventur (K01)" },
  { ticket:"QG6", value:"YAHOO/SI_QG6", caption:"KEPLAND KEPLAND (QG6)" },
  { ticket:"578", value:"YAHOO/SI_578", caption:"KS Energy (578)" },
  { ticket:"ER0", value:"YAHOO/SI_ER0", caption:"KSH Hldg (ER0)" },
  { ticket:"EB7", value:"YAHOO/SI_EB7", caption:"KTL Global (EB7)" },
  { ticket:"K07", value:"YAHOO/SI_K07", caption:"KXD (K07)" },
  { ticket:"K29", value:"YAHOO/SI_K29", caption:"Karin (K29)" },
  { ticket:"F9M", value:"YAHOO/SI_F9M", caption:"KencanaAgri (F9M)" },
  { ticket:"BN4", value:"YAHOO/SI_BN4", caption:"Kep Corp (BN4)" },
  { ticket:"K71U", value:"YAHOO/SI_K71U", caption:"Kep REIT (K71U)" },
  { ticket:"K17", value:"YAHOO/SI_K17", caption:"KepLand (K17)" },
  { ticket:"K11", value:"YAHOO/SI_K11", caption:"KepT&T (K11)" },
  { ticket:"K03", value:"YAHOO/SI_K03", caption:"KhongGuan (K03)" },
  { ticket:"K04", value:"YAHOO/SI_K04", caption:"Kian Ann (K04)" },
  { ticket:"K22", value:"YAHOO/SI_K22", caption:"Kian Ho (K22)" },
  { ticket:"554", value:"YAHOO/SI_554", caption:"KingWan (554)" },
  { ticket:"K14", value:"YAHOO/SI_K14", caption:"Kingboard (K14)" },
  { ticket:"5MZ", value:"YAHOO/SI_5MZ", caption:"KingsmenC (5MZ)" },
  { ticket:"5BK", value:"YAHOO/SI_5BK", caption:"Koda (5BK)" },
  { ticket:"K75", value:"YAHOO/SI_K75", caption:"Koh Bros (K75)" },
  { ticket:"5DL", value:"YAHOO/SI_5DL", caption:"Koon (5DL)" },
  { ticket:"5RK", value:"YAHOO/SI_5RK", caption:"Kreuz (5RK)" },
  { ticket:"L15", value:"YAHOO/SI_L15", caption:"L-Jacob^ (L15)" },
  { ticket:"L22", value:"YAHOO/SI_L22", caption:"LANKom Elec^ (L22)" },
  { ticket:"Q7X", value:"YAHOO/SI_Q7X", caption:"LANTROVISION NPV B/L10 (Q7X)" },
  { ticket:"L38", value:"YAHOO/SI_L38", caption:"LC Dev (L38)" },
  { ticket:"C4P", value:"YAHOO/SI_C4P", caption:"LH Group (C4P)" },
  { ticket:"L10", value:"YAHOO/SI_L10", caption:"LHT (L10)" },
  { ticket:"F1E", value:"YAHOO/SI_F1E", caption:"LKH (F1E)" },
  { ticket:"L24", value:"YAHOO/SI_L24", caption:"LMA (L24)" },
  { ticket:"G1K", value:"YAHOO/SI_G1K", caption:"LYXOR Asia EX 10US$ (G1K)" },
  { ticket:"L05", value:"YAHOO/SI_L05", caption:"LafeCorp (L05)" },
  { ticket:"Q7W", value:"YAHOO/SI_Q7W", caption:"LantroVision (Q7W)" },
  { ticket:"LS9", value:"YAHOO/SI_LS9", caption:"LeaderEnv (LS9)" },
  { ticket:"L25", value:"YAHOO/SI_L25", caption:"Lee KimTah (L25)" },
  { ticket:"593", value:"YAHOO/SI_593", caption:"LeeMetal (593)" },
  { ticket:"Q0X", value:"YAHOO/SI_Q0X", caption:"Ley Choon (Q0X)" },
  { ticket:"E9A", value:"YAHOO/SI_E9A", caption:"Li Heng (E9A)" },
  { ticket:"L03", value:"YAHOO/SI_L03", caption:"Lian Beng (L03)" },
  { ticket:"L20", value:"YAHOO/SI_L20", caption:"LifeBrandz (L20)" },
  { ticket:"L08", value:"YAHOO/SI_L08", caption:"LionAPac (L08)" },
  { ticket:"A78", value:"YAHOO/SI_A78", caption:"LionGold (A78)" },
  { ticket:"L17", value:"YAHOO/SI_L17", caption:"LionTeckC (L17)" },
  { ticket:"D5IU", value:"YAHOO/SI_D5IU", caption:"LippoMalls (D5IU)" },
  { ticket:"E94", value:"YAHOO/SI_E94", caption:"Lizhong (E94)" },
  { ticket:"L28", value:"YAHOO/SI_L28", caption:"Longcheer (L28)" },
  { ticket:"O6Z", value:"YAHOO/SI_O6Z", caption:"Lonza 10 (O6Z)" },
  { ticket:"5IE", value:"YAHOO/SI_5IE", caption:"Lorenzo (5IE)" },
  { ticket:"M22", value:"YAHOO/SI_M22", caption:"LottVis^ (M22)" },
  { ticket:"L19", value:"YAHOO/SI_L19", caption:"Lum Chang (L19)" },
  { ticket:"L09", value:"YAHOO/SI_L09", caption:"LungKee BMU (L09)" },
  { ticket:"L34", value:"YAHOO/SI_L34", caption:"Luxking (L34)" },
  { ticket:"A61", value:"YAHOO/SI_A61", caption:"Luye Pharma (A61)" },
  { ticket:"L46", value:"YAHOO/SI_L46", caption:"Luzhou (L46)" },
  { ticket:"P60", value:"YAHOO/SI_P60", caption:"Lyxor Asia 10US$ (P60)" },
  { ticket:"NF6", value:"YAHOO/SI_NF6", caption:"Lyxor AsiaCS 10US$ (NF6)" },
  { ticket:"NF5", value:"YAHOO/SI_NF5", caption:"Lyxor AsiaFN 10US$ (NF5)" },
  { ticket:"NF3", value:"YAHOO/SI_NF3", caption:"Lyxor AsiaIF 10US$ (NF3)" },
  { ticket:"NF4", value:"YAHOO/SI_NF4", caption:"Lyxor AsiaIT 10US$ (NF4)" },
  { ticket:"NF7", value:"YAHOO/SI_NF7", caption:"Lyxor AsiaMT 10US$ (NF7)" },
  { ticket:"MT7", value:"YAHOO/SI_MT7", caption:"Lyxor AsiaRE 10US$ (MT7)" },
  { ticket:"G1O", value:"YAHOO/SI_G1O", caption:"Lyxor CRBxEny10US$ (G1O)" },
  { ticket:"P58", value:"YAHOO/SI_P58", caption:"Lyxor ChinaH 10US$ (P58)" },
  { ticket:"A0W", value:"YAHOO/SI_A0W", caption:"Lyxor Cmdty 10US$ (A0W)" },
  { ticket:"H1N", value:"YAHOO/SI_H1N", caption:"Lyxor EM Mkt 10US$ (H1N)" },
  { ticket:"H1M", value:"YAHOO/SI_H1M", caption:"Lyxor EastEur10US$ (H1M)" },
  { ticket:"JC5", value:"YAHOO/SI_JC5", caption:"Lyxor Europe 10US$ (JC5)" },
  { ticket:"A9B", value:"YAHOO/SI_A9B", caption:"Lyxor HSI 10US$ (A9B)" },
  { ticket:"FC6", value:"YAHOO/SI_FC6", caption:"Lyxor IndiaNifty10 (FC6)" },
  { ticket:"P2Q", value:"YAHOO/SI_P2Q", caption:"Lyxor Indonesia10US$ (P2Q)" },
  { ticket:"CW4", value:"YAHOO/SI_CW4", caption:"Lyxor Japan 10US$ (CW4)" },
  { ticket:"AO9", value:"YAHOO/SI_AO9", caption:"Lyxor Korea 10US$ (AO9)" },
  { ticket:"H1O", value:"YAHOO/SI_H1O", caption:"Lyxor LATAM 10US$ (H1O)" },
  { ticket:"G1M", value:"YAHOO/SI_G1M", caption:"Lyxor MAL 10US$ (G1M)" },
  { ticket:"G1N", value:"YAHOO/SI_G1N", caption:"Lyxor MSIndia10US$ (G1N)" },
  { ticket:"H1Q", value:"YAHOO/SI_H1Q", caption:"Lyxor Nasdaq 10US$ (H1Q)" },
  { ticket:"JC7", value:"YAHOO/SI_JC7", caption:"Lyxor Russia 10US$ (JC7)" },
  { ticket:"A9A", value:"YAHOO/SI_A9A", caption:"Lyxor Taiwan 10US$ (A9A)" },
  { ticket:"P2P", value:"YAHOO/SI_P2P", caption:"Lyxor ThaiSET 10US$ (P2P)" },
  { ticket:"JC6", value:"YAHOO/SI_JC6", caption:"Lyxor USDJIA 10US$ (JC6)" },
  { ticket:"H1P", value:"YAHOO/SI_H1P", caption:"Lyxor World 10US$ (H1P)" },
  { ticket:"N14", value:"YAHOO/SI_N14", caption:"M Devt (N14)" },
  { ticket:"B2F", value:"YAHOO/SI_B2F", caption:"M1 (B2F)" },
  { ticket:"553", value:"YAHOO/SI_553", caption:"MAVERIC LTD NPV (553)" },
  { ticket:"A27", value:"YAHOO/SI_A27", caption:"MDR (A27)" },
  { ticket:"5BM", value:"YAHOO/SI_5BM", caption:"MFS Tech (5BM)" },
  { ticket:"5EN", value:"YAHOO/SI_5EN", caption:"MIDAS (5EN)" },
  { ticket:"M11", value:"YAHOO/SI_M11", caption:"MITech (M11)" },
  { ticket:"NC9", value:"YAHOO/SI_NC9", caption:"MSC 100 (NC9)" },
  { ticket:"M05", value:"YAHOO/SI_M05", caption:"MTQ Corp (M05)" },
  { ticket:"F86", value:"YAHOO/SI_F86", caption:"MYP (F86)" },
  { ticket:"A0P", value:"YAHOO/SI_A0P", caption:"MacCookPSF (A0P)" },
  { ticket:"M41", value:"YAHOO/SI_M41", caption:"MacqIntInfra (M41)" },
  { ticket:"M04", value:"YAHOO/SI_M04", caption:"ManOri US$ (M04)" },
  { ticket:"L02", value:"YAHOO/SI_L02", caption:"ManhattanRes (L02)" },
  { ticket:"N2IU", value:"YAHOO/SI_N2IU", caption:"MapletreeCom (N2IU)" },
  { ticket:"ME8U", value:"YAHOO/SI_ME8U", caption:"MapletreeInd (ME8U)" },
  { ticket:"M44U", value:"YAHOO/SI_M44U", caption:"MapletreeLog (M44U)" },
  { ticket:"5LY", value:"YAHOO/SI_5LY", caption:"Marco Polo (5LY)" },
  { ticket:"M12", value:"YAHOO/SI_M12", caption:"Maruwa 100 Yen1k (M12)" },
  { ticket:"M15", value:"YAHOO/SI_M15", caption:"Matex^ (M15)" },
  { ticket:"M30", value:"YAHOO/SI_M30", caption:"Meghmani SDS (M30)" },
  { ticket:"M24", value:"YAHOO/SI_M24", caption:"Meiban Gp (M24)" },
  { ticket:"5MS", value:"YAHOO/SI_5MS", caption:"MemstarT (5MS)" },
  { ticket:"M26", value:"YAHOO/SI_M26", caption:"Memtech (M26)" },
  { ticket:"5NF", value:"YAHOO/SI_5NF", caption:"Mencast (5NF)" },
  { ticket:"EE6", value:"YAHOO/SI_EE6", caption:"Mercator (EE6)" },
  { ticket:"DU4", value:"YAHOO/SI_DU4", caption:"Mermaid (DU4)" },
  { ticket:"QG1", value:"YAHOO/SI_QG1", caption:"Metech Int^ (QG1)" },
  { ticket:"M01", value:"YAHOO/SI_M01", caption:"MetroHldg (M01)" },
  { ticket:"MV4", value:"YAHOO/SI_MV4", caption:"Mewah (MV4)" },
  { ticket:"5DD", value:"YAHOO/SI_5DD", caption:"Micro-Mech (5DD)" },
  { ticket:"C68", value:"YAHOO/SI_C68", caption:"Mirach Ener (C68)" },
  { ticket:"M03", value:"YAHOO/SI_M03", caption:"Miyoshi (M03)" },
  { ticket:"M06", value:"YAHOO/SI_M06", caption:"MultiChem (M06)" },
  { ticket:"MF6", value:"YAHOO/SI_MF6", caption:"Mun Siong (MF6)" },
  { ticket:"597", value:"YAHOO/SI_597", caption:"NEL GROUP LIMITED NPV (597)" },
  { ticket:"N03", value:"YAHOO/SI_N03", caption:"NOL (N03)" },
  { ticket:"N02", value:"YAHOO/SI_N02", caption:"NSL (N02)" },
  { ticket:"N4E", value:"YAHOO/SI_N4E", caption:"Nam Cheong (N4E)" },
  { ticket:"G0I", value:"YAHOO/SI_G0I", caption:"NamLee (G0I)" },
  { ticket:"N01", value:"YAHOO/SI_N01", caption:"NeraTel (N01)" },
  { ticket:"N08", value:"YAHOO/SI_N08", caption:"New Toyo (N08)" },
  { ticket:"B07", value:"YAHOO/SI_B07", caption:"NexGenSCom^ (B07)" },
  { ticket:"5GF", value:"YAHOO/SI_5GF", caption:"Nico Steel (5GF)" },
  { ticket:"G3B", value:"YAHOO/SI_G3B", caption:"Nikko AM STI ETF100 (G3B)" },
  { ticket:"N32", value:"YAHOO/SI_N32", caption:"Nippecraft (N32)" },
  { ticket:"547", value:"YAHOO/SI_547", caption:"Nobel Des (547)" },
  { ticket:"N21", value:"YAHOO/SI_N21", caption:"Noble Grp (N21)" },
  { ticket:"543", value:"YAHOO/SI_543", caption:"Noel (543)" },
  { ticket:"N33", value:"YAHOO/SI_N33", caption:"Nomura Yen1k (N33)" },
  { ticket:"MR7", value:"YAHOO/SI_MR7", caption:"Nordic (MR7)" },
  { ticket:"MR8", value:"YAHOO/SI_MR8", caption:"Novo Gp (MR8)" },
  { ticket:"O39", value:"YAHOO/SI_O39", caption:"OCBC Bk (O39)" },
  { ticket:"O15", value:"YAHOO/SI_O15", caption:"OCBC Bk 4.2%NCPS (O15)" },
  { ticket:"O16", value:"YAHOO/SI_O16", caption:"OCBC Bk 4.5%NCPS 100 (O16)" },
  { ticket:"F4B", value:"YAHOO/SI_F4B", caption:"OCBC Bk 5.1%NCPS 100 (F4B)" },
  { ticket:"O31", value:"YAHOO/SI_O31", caption:"OCC 3.93% NCPS 10 (O31)" },
  { ticket:"GG0", value:"YAHOO/SI_GG0", caption:"OCC 5.1% NCPS 100 (GG0)" },
  { ticket:"S3N", value:"YAHOO/SI_S3N", caption:"OKH Global (S3N)" },
  { ticket:"5CF", value:"YAHOO/SI_5CF", caption:"OKP (5CF)" },
  { ticket:"O23", value:"YAHOO/SI_O23", caption:"OSIM (O23)" },
  { ticket:"LJ3", value:"YAHOO/SI_LJ3", caption:"OUE Ltd (LJ3)" },
  { ticket:"O05", value:"YAHOO/SI_O05", caption:"Ocean Sky (O05)" },
  { ticket:"579", value:"YAHOO/SI_579", caption:"Oceanus (579)" },
  { ticket:"O32", value:"YAHOO/SI_O32", caption:"Olam (O32)" },
  { ticket:"O57", value:"YAHOO/SI_O57", caption:"OmegaNav 50 (O57)" },
  { ticket:"O08", value:"YAHOO/SI_O08", caption:"Ossia (O08)" },
  { ticket:"G4F", value:"YAHOO/SI_G4F", caption:"Otto Marine (G4F)" },
  { ticket:"AJ2", value:"YAHOO/SI_AJ2", caption:"Ouhua (AJ2)" },
  { ticket:"RQ1", value:"YAHOO/SI_RQ1", caption:"OverseasEdu (RQ1)" },
  { ticket:"5UX", value:"YAHOO/SI_5UX", caption:"OxleyHldg (5UX)" },
  { ticket:"P8Q", value:"YAHOO/SI_P8Q", caption:"PAC ANDES 500 (P8Q)" },
  { ticket:"P06", value:"YAHOO/SI_P06", caption:"PCA Tech (P06)" },
  { ticket:"P19", value:"YAHOO/SI_P19", caption:"PCI (P19)" },
  { ticket:"IX2", value:"YAHOO/SI_IX2", caption:"PEC (IX2)" },
  { ticket:"P05", value:"YAHOO/SI_P05", caption:"PFood (P05)" },
  { ticket:"C2PU", value:"YAHOO/SI_C2PU", caption:"PLife REIT (C2PU)" },
  { ticket:"P12", value:"YAHOO/SI_P12", caption:"PM Data (P12)" },
  { ticket:"P07", value:"YAHOO/SI_P07", caption:"PNE Ind (P07)" },
  { ticket:"K6S", value:"YAHOO/SI_K6S", caption:"PRU 500US$ (K6S)" },
  { ticket:"L6T", value:"YAHOO/SI_L6T", caption:"PSL Hldg (L6T)" },
  { ticket:"P11", value:"YAHOO/SI_P11", caption:"Pac Andes (P11)" },
  { ticket:"P15", value:"YAHOO/SI_P15", caption:"Pac Cent (P15)" },
  { ticket:"P47", value:"YAHOO/SI_P47", caption:"Pacific HC (P47)" },
  { ticket:"P36", value:"YAHOO/SI_P36", caption:"Pan Hong (P36)" },
  { ticket:"H49", value:"YAHOO/SI_H49", caption:"Pan Pacific (H49)" },
  { ticket:"P52", value:"YAHOO/SI_P52", caption:"PanUnited (P52)" },
  { ticket:"O9E", value:"YAHOO/SI_O9E", caption:"Parkson (O9E)" },
  { ticket:"P13", value:"YAHOO/SI_P13", caption:"Penguin (P13)" },
  { ticket:"N9LU", value:"YAHOO/SI_N9LU", caption:"PerennialCRT (N9LU)" },
  { ticket:"P22", value:"YAHOO/SI_P22", caption:"Pertama (P22)" },
  { ticket:"P34", value:"YAHOO/SI_P34", caption:"Petra (P34)" },
  { ticket:"P31", value:"YAHOO/SI_P31", caption:"Pharmesis (P31)" },
  { ticket:"P82", value:"YAHOO/SI_P82", caption:"Plastoform^ (P82)" },
  { ticket:"P01", value:"YAHOO/SI_P01", caption:"PohTC (P01)" },
  { ticket:"P29", value:"YAHOO/SI_P29", caption:"Popular (P29)" },
  { ticket:"J74", value:"YAHOO/SI_J74", caption:"Pteris (J74)" },
  { ticket:"QC7", value:"YAHOO/SI_QC7", caption:"Q&MDental (QC7)" },
  { ticket:"Q01", value:"YAHOO/SI_Q01", caption:"QAF (Q01)" },
  { ticket:"QY3", value:"YAHOO/SI_QY3", caption:"QY3: (QY3)" },
  { ticket:"552", value:"YAHOO/SI_552", caption:"QianHu (552)" },
  { ticket:"KT9", value:"YAHOO/SI_KT9", caption:"Qingmei (KT9)" },
  { ticket:"CL7", value:"YAHOO/SI_CL7", caption:"RH Energy (CL7)" },
  { ticket:"T13", value:"YAHOO/SI_T13", caption:"RH PetroGas (T13)" },
  { ticket:"NR7", value:"YAHOO/SI_NR7", caption:"Raffles Edu (NR7)" },
  { ticket:"R01", value:"YAHOO/SI_R01", caption:"RafflesMG (R01)" },
  { ticket:"R14", value:"YAHOO/SI_R14", caption:"Ramba (R14)" },
  { ticket:"B1ZU", value:"YAHOO/SI_B1ZU", caption:"Rickmers (B1ZU)" },
  { ticket:"AP4", value:"YAHOO/SI_AP4", caption:"Riverstone (AP4)" },
  { ticket:"R07", value:"YAHOO/SI_R07", caption:"Rotary (R07)" },
  { ticket:"A50", value:"YAHOO/SI_A50", caption:"Rowsley (A50)" },
  { ticket:"E8Z", value:"YAHOO/SI_E8Z", caption:"Roxy-Pacific (E8Z)" },
  { ticket:"J8O", value:"YAHOO/SI_J8O", caption:"Ryobi Kiso (J8O)" },
  { ticket:"M09", value:"YAHOO/SI_M09", caption:"S i2i (M09)" },
  { ticket:"S23", value:"YAHOO/SI_S23", caption:"S'pura Fin (S23)" },
  { ticket:"S58", value:"YAHOO/SI_S58", caption:"SATS (S58)" },
  { ticket:"S61", value:"YAHOO/SI_S61", caption:"SBSTransit 500 (S61)" },
  { ticket:"D2S", value:"YAHOO/SI_D2S", caption:"SCGlobal (D2S)" },
  { ticket:"S68", value:"YAHOO/SI_S68", caption:"SGX (S68)" },
  { ticket:"565", value:"YAHOO/SI_565", caption:"SHC CAPITAL ASIA LTD NPV (565)" },
  { ticket:"S45U", value:"YAHOO/SI_S45U", caption:"SI Fund (S45U)" },
  { ticket:"C6L", value:"YAHOO/SI_C6L", caption:"SIA (C6L)" },
  { ticket:"S59", value:"YAHOO/SI_S59", caption:"SIA Engg (S59)" },
  { ticket:"5GB", value:"YAHOO/SI_5GB", caption:"SIIC Env (5GB)" },
  { ticket:"S53", value:"YAHOO/SI_S53", caption:"SMRT (S53)" },
  { ticket:"X04", value:"YAHOO/SI_X04", caption:"SP AusNet (X04)" },
  { ticket:"S13", value:"YAHOO/SI_S13", caption:"SP Corp (S13)" },
  { ticket:"D07", value:"YAHOO/SI_D07", caption:"SPDR DJIA 10US$ (D07)" },
  { ticket:"S27", value:"YAHOO/SI_S27", caption:"SPDR S&P500 10US$ (S27)" },
  { ticket:"T39", value:"YAHOO/SI_T39", caption:"SPH (T39)" },
  { ticket:"S63", value:"YAHOO/SI_S63", caption:"ST Engg (S63)" },
  { ticket:"S24", value:"YAHOO/SI_S24", caption:"STATSChP (S24)" },
  { ticket:"ES3", value:"YAHOO/SI_ES3", caption:"STI ETF (ES3)" },
  { ticket:"GZ9", value:"YAHOO/SI_GZ9", caption:"STXPO 100 (GZ9)" },
  { ticket:"F06", value:"YAHOO/SI_F06", caption:"SUNMOON (F06)" },
  { ticket:"M1GU", value:"YAHOO/SI_M1GU", caption:"Sabana REIT (M1GU)" },
  { ticket:"DZ8U", value:"YAHOO/SI_DZ8U", caption:"SaizenREIT (DZ8U)" },
  { ticket:"5DO", value:"YAHOO/SI_5DO", caption:"Sakae (5DO)" },
  { ticket:"AJ1", value:"YAHOO/SI_AJ1", caption:"Sakari (AJ1)" },
  { ticket:"E6R", value:"YAHOO/SI_E6R", caption:"Samko (E6R)" },
  { ticket:"S56", value:"YAHOO/SI_S56", caption:"Samudera (S56)" },
  { ticket:"S46", value:"YAHOO/SI_S46", caption:"San Teh (S46)" },
  { ticket:"NF1", value:"YAHOO/SI_NF1", caption:"Sapphire Corp (NF1)" },
  { ticket:"U77", value:"YAHOO/SI_U77", caption:"Sarin (U77)" },
  { ticket:"T20", value:"YAHOO/SI_T20", caption:"Scintronix^ (T20)" },
  { ticket:"566", value:"YAHOO/SI_566", caption:"SeeHS (566)" },
  { ticket:"U96", value:"YAHOO/SI_U96", caption:"Semb Corp (U96)" },
  { ticket:"S51", value:"YAHOO/SI_S51", caption:"SembMar (S51)" },
  { ticket:"S69", value:"YAHOO/SI_S69", caption:"Serial (S69)" },
  { ticket:"IW5", value:"YAHOO/SI_IW5", caption:"Seroja (IW5)" },
  { ticket:"S07", value:"YAHOO/SI_S07", caption:"Shang Asia 2kHK$ (S07)" },
  { ticket:"X27", value:"YAHOO/SI_X27", caption:"ShangTurbo (X27)" },
  { ticket:"T57", value:"YAHOO/SI_T57", caption:"ShanghaiAsia (T57)" },
  { ticket:"OV8", value:"YAHOO/SI_OV8", caption:"Sheng Siong (OV8)" },
  { ticket:"5CP", value:"YAHOO/SI_5CP", caption:"Silverlake (5CP)" },
  { ticket:"S05", value:"YAHOO/SI_S05", caption:"Sim Lian (S05)" },
  { ticket:"KF4", value:"YAHOO/SI_KF4", caption:"Sin Heng (KF4)" },
  { ticket:"B7K", value:"YAHOO/SI_B7K", caption:"SinGheeHuat (B7K)" },
  { ticket:"A26", value:"YAHOO/SI_A26", caption:"Sinarmas (A26)" },
  { ticket:"S35", value:"YAHOO/SI_S35", caption:"Sing Inv (S35)" },
  { ticket:"5IC", value:"YAHOO/SI_5IC", caption:"SingHldg (5IC)" },
  { ticket:"S08", value:"YAHOO/SI_S08", caption:"SingPost (S08)" },
  { ticket:"Z74", value:"YAHOO/SI_Z74", caption:"SingTel (Z74)" },
  { ticket:"F3V", value:"YAHOO/SI_F3V", caption:"SinoConst (F3V)" },
  { ticket:"JS5", value:"YAHOO/SI_JS5", caption:"SinoGrandnes (JS5)" },
  { ticket:"AD8", value:"YAHOO/SI_AD8", caption:"SinoTechfib (AD8)" },
  { ticket:"X06", value:"YAHOO/SI_X06", caption:"Sinopipe (X06)" },
  { ticket:"C9Q", value:"YAHOO/SI_C9Q", caption:"Sinostar (C9Q)" },
  { ticket:"D3W", value:"YAHOO/SI_D3W", caption:"Sinotel (D3W)" },
  { ticket:"5CN", value:"YAHOO/SI_5CN", caption:"Sinwa (5CN)" },
  { ticket:"E6E", value:"YAHOO/SI_E6E", caption:"SoundGlobal (E6E)" },
  { ticket:"5KI", value:"YAHOO/SI_5KI", caption:"SoupRestn (5KI)" },
  { ticket:"T77", value:"YAHOO/SI_T77", caption:"SouthernPkg (T77)" },
  { ticket:"S30", value:"YAHOO/SI_S30", caption:"Sp Land (S30)" },
  { ticket:"S19", value:"YAHOO/SI_S19", caption:"Sp Ship (S19)" },
  { ticket:"S49", value:"YAHOO/SI_S49", caption:"SpRe (S49)" },
  { ticket:"Y45", value:"YAHOO/SI_Y45", caption:"SpWindsor (Y45)" },
  { ticket:"564", value:"YAHOO/SI_564", caption:"Spindex (564)" },
  { ticket:"NC2", value:"YAHOO/SI_NC2", caption:"Sri Trang (NC2)" },
  { ticket:"S20", value:"YAHOO/SI_S20", caption:"St Trdg (S20)" },
  { ticket:"H07", value:"YAHOO/SI_H07", caption:"StamfordLd (H07)" },
  { ticket:"S29", value:"YAHOO/SI_S29", caption:"StamfordTyres (S29)" },
  { ticket:"CC3", value:"YAHOO/SI_CC3", caption:"StarHub (CC3)" },
  { ticket:"X64", value:"YAHOO/SI_X64", caption:"StarPharm (X64)" },
  { ticket:"P40U", value:"YAHOO/SI_P40U", caption:"Starhill Gbl (P40U)" },
  { ticket:"S85", value:"YAHOO/SI_S85", caption:"Straco (S85)" },
  { ticket:"S73", value:"YAHOO/SI_S73", caption:"Stratech^ (S73)" },
  { ticket:"A7S", value:"YAHOO/SI_A7S", caption:"SunVic (A7S)" },
  { ticket:"C2J", value:"YAHOO/SI_C2J", caption:"Sunmart (C2J)" },
  { ticket:"T35", value:"YAHOO/SI_T35", caption:"Sunning Tech (T35)" },
  { ticket:"S38", value:"YAHOO/SI_S38", caption:"Sunray^ (S38)" },
  { ticket:"S71", value:"YAHOO/SI_S71", caption:"Sunright (S71)" },
  { ticket:"CZ3", value:"YAHOO/SI_CZ3", caption:"Suntar Eco (CZ3)" },
  { ticket:"T82U", value:"YAHOO/SI_T82U", caption:"SuntecReit (T82U)" },
  { ticket:"S47", value:"YAHOO/SI_S47", caption:"SupPack (S47)" },
  { ticket:"S10", value:"YAHOO/SI_S10", caption:"SuperGroup (S10)" },
  { ticket:"S48", value:"YAHOO/SI_S48", caption:"Superbowl (S48)" },
  { ticket:"Q7Q", value:"YAHOO/SI_Q7Q", caption:"SurfaceMT^ (Q7Q)" },
  { ticket:"QF6", value:"YAHOO/SI_QF6", caption:"Swee Hong (QF6)" },
  { ticket:"AK3", value:"YAHOO/SI_AK3", caption:"Swiber (AK3)" },
  { ticket:"O2F", value:"YAHOO/SI_O2F", caption:"Swing Media (O2F)" },
  { ticket:"5FD", value:"YAHOO/SI_5FD", caption:"Swissco Hldg (5FD)" },
  { ticket:"Z75", value:"YAHOO/SI_Z75", caption:"Synear (Z75)" },
  { ticket:"PA3", value:"YAHOO/SI_PA3", caption:"TA Corp (PA3)" },
  { ticket:"Y92", value:"YAHOO/SI_Y92", caption:"THBEV (Y92)" },
  { ticket:"T18", value:"YAHOO/SI_T18", caption:"TPV (T18)" },
  { ticket:"T09", value:"YAHOO/SI_T09", caption:"TT Int (T09)" },
  { ticket:"K1Q", value:"YAHOO/SI_K1Q", caption:"TTJ (K1Q)" },
  { ticket:"500", value:"YAHOO/SI_500", caption:"Tai Sin (500)" },
  { ticket:"T03", value:"YAHOO/SI_T03", caption:"Tat Hong (T03)" },
  { ticket:"T12", value:"YAHOO/SI_T12", caption:"Tat Seng (T12)" },
  { ticket:"5CQ", value:"YAHOO/SI_5CQ", caption:"TechOil&Gas (5CQ)" },
  { ticket:"T43", value:"YAHOO/SI_T43", caption:"Techcomp (T43)" },
  { ticket:"561", value:"YAHOO/SI_561", caption:"Teckwah (561)" },
  { ticket:"M1Z", value:"YAHOO/SI_M1Z", caption:"Tee Intl (M1Z)" },
  { ticket:"T41", value:"YAHOO/SI_T41", caption:"TeleChoice (T41)" },
  { ticket:"T28", value:"YAHOO/SI_T28", caption:"Teledata^ (T28)" },
  { ticket:"AI1", value:"YAHOO/SI_AI1", caption:"TexchemPack^ (AI1)" },
  { ticket:"596", value:"YAHOO/SI_596", caption:"ThaiVillag (596)" },
  { ticket:"T04", value:"YAHOO/SI_T04", caption:"Thakral (T04)" },
  { ticket:"T14", value:"YAHOO/SI_T14", caption:"TianjinZUS$ (T14)" },
  { ticket:"J7X", value:"YAHOO/SI_J7X", caption:"Tigerair (J7X)" },
  { ticket:"K2P", value:"YAHOO/SI_K2P", caption:"Tiong Seng (K2P)" },
  { ticket:"T06", value:"YAHOO/SI_T06", caption:"TiongWoon (T06)" },
  { ticket:"519", value:"YAHOO/SI_519", caption:"TopGlobal (519)" },
  { ticket:"S2D", value:"YAHOO/SI_S2D", caption:"Tosei 100 (S2D)" },
  { ticket:"E15", value:"YAHOO/SI_E15", caption:"Transcu (E15)" },
  { ticket:"570", value:"YAHOO/SI_570", caption:"Transit (570)" },
  { ticket:"T55", value:"YAHOO/SI_T55", caption:"Transpac (T55)" },
  { ticket:"T19", value:"YAHOO/SI_T19", caption:"Transview (T19)" },
  { ticket:"5KH", value:"YAHOO/SI_5KH", caption:"Travelite (5KH)" },
  { ticket:"5AB", value:"YAHOO/SI_5AB", caption:"Trek (5AB)" },
  { ticket:"RC5", value:"YAHOO/SI_RC5", caption:"Triyards (RC5)" },
  { ticket:"T26", value:"YAHOO/SI_T26", caption:"Tsit Wing (T26)" },
  { ticket:"T24", value:"YAHOO/SI_T24", caption:"Tuan Sing (T24)" },
  { ticket:"T08", value:"YAHOO/SI_T08", caption:"TyeSoon (T08)" },
  { ticket:"U04", value:"YAHOO/SI_U04", caption:"UE (U04)" },
  { ticket:"NI3", value:"YAHOO/SI_NI3", caption:"UE E&C (NI3)" },
  { ticket:"U05", value:"YAHOO/SI_U05", caption:"UE P (U05)" },
  { ticket:"JK8", value:"YAHOO/SI_JK8", caption:"UETF SSE50China100 (JK8)" },
  { ticket:"U06", value:"YAHOO/SI_U06", caption:"UIC (U06)" },
  { ticket:"U07", value:"YAHOO/SI_U07", caption:"UIS (U07)" },
  { ticket:"558", value:"YAHOO/SI_558", caption:"UMS (558)" },
  { ticket:"U11", value:"YAHOO/SI_U11", caption:"UOB (U11)" },
  { ticket:"GL8", value:"YAHOO/SI_GL8", caption:"UOB 5.05%NCPS 100 (GL8)" },
  { ticket:"U10", value:"YAHOO/SI_U10", caption:"UOB-KayH (U10)" },
  { ticket:"U13", value:"YAHOO/SI_U13", caption:"UOI (U13)" },
  { ticket:"U14", value:"YAHOO/SI_U14", caption:"UOL (U14)" },
  { ticket:"RX9", value:"YAHOO/SI_RX9", caption:"UOL A (RX9)" },
  { ticket:"U09", value:"YAHOO/SI_U09", caption:"UPP (U09)" },
  { ticket:"C3T", value:"YAHOO/SI_C3T", caption:"Uni-Asia (C3T)" },
  { ticket:"P30", value:"YAHOO/SI_P30", caption:"UniFiber (P30)" },
  { ticket:"U01", value:"YAHOO/SI_U01", caption:"UniFood (U01)" },
  { ticket:"U18", value:"YAHOO/SI_U18", caption:"Unified (U18)" },
  { ticket:"V69", value:"YAHOO/SI_V69", caption:"Union Steel (V69)" },
  { ticket:"A6F", value:"YAHOO/SI_A6F", caption:"Unionmet (A6F)" },
  { ticket:"U19", value:"YAHOO/SI_U19", caption:"UtdEnvirotech (U19)" },
  { ticket:"EH5", value:"YAHOO/SI_EH5", caption:"UtdOAus (EH5)" },
  { ticket:"PH0", value:"YAHOO/SI_PH0", caption:"VGO (PH0)" },
  { ticket:"V01", value:"YAHOO/SI_V01", caption:"VICOM (V01)" },
  { ticket:"BN2", value:"YAHOO/SI_BN2", caption:"Valuetronics (BN2)" },
  { ticket:"MS7", value:"YAHOO/SI_MS7", caption:"Vard Holdings (MS7)" },
  { ticket:"V03", value:"YAHOO/SI_V03", caption:"Venture (V03)" },
  { ticket:"535", value:"YAHOO/SI_535", caption:"VibroPower (535)" },
  { ticket:"569", value:"YAHOO/SI_569", caption:"Vicplas (569)" },
  { ticket:"L5J", value:"YAHOO/SI_L5J", caption:"VizBranz (L5J)" },
  { ticket:"W01", value:"YAHOO/SI_W01", caption:"WBL Corp (W01)" },
  { ticket:"Q0U", value:"YAHOO/SI_Q0U", caption:"WING TAI HOLDINGS NPV B/L 10 (Q0U)" },
  { ticket:"E3B", value:"YAHOO/SI_E3B", caption:"Wee Hur (E3B)" },
  { ticket:"ON7", value:"YAHOO/SI_ON7", caption:"Weiye (ON7)" },
  { ticket:"M35", value:"YAHOO/SI_M35", caption:"Wheelock (M35)" },
  { ticket:"W12", value:"YAHOO/SI_W12", caption:"Willas-Arr (W12)" },
  { ticket:"F34", value:"YAHOO/SI_F34", caption:"Wilmar (F34)" },
  { ticket:"W05", value:"YAHOO/SI_W05", caption:"Wing Tai (W05)" },
  { ticket:"B49", value:"YAHOO/SI_B49", caption:"WorldPreci (B49)" },
  { ticket:"M9F", value:"YAHOO/SI_M9F", caption:"XMH (M9F)" },
  { ticket:"MN5", value:"YAHOO/SI_MN5", caption:"XinRen (MN5)" },
  { ticket:"I04", value:"YAHOO/SI_I04", caption:"Xpress (I04)" },
  { ticket:"Y08", value:"YAHOO/SI_Y08", caption:"YHI (Y08)" },
  { ticket:"QY4", value:"YAHOO/SI_QY4", caption:"YOMA STRATEGIC HOLDINGS LIMITED (QY4)" },
  { ticket:"MC7", value:"YAHOO/SI_MC7", caption:"Yamada (MC7)" },
  { ticket:"R8P", value:"YAHOO/SI_R8P", caption:"Yangi EURO S (R8P)" },
  { ticket:"BS6", value:"YAHOO/SI_BS6", caption:"Yangzijiang (BS6)" },
  { ticket:"Z25", value:"YAHOO/SI_Z25", caption:"Yanlord (Z25)" },
  { ticket:"Y03", value:"YAHOO/SI_Y03", caption:"Yeo HS (Y03)" },
  { ticket:"R4A", value:"YAHOO/SI_R4A", caption:"Yeo HS 1 (R4A)" },
  { ticket:"5DM", value:"YAHOO/SI_5DM", caption:"Ying Li (5DM)" },
  { ticket:"Z59", value:"YAHOO/SI_Z59", caption:"Yoma (Z59)" },
  { ticket:"CX5", value:"YAHOO/SI_CX5", caption:"Yong Xin^ (CX5)" },
  { ticket:"E6A", value:"YAHOO/SI_E6A", caption:"Yongmao (E6A)" },
  { ticket:"Y02", value:"YAHOO/SI_Y02", caption:"Yongnam (Y02)" },
  { ticket:"Y06", value:"YAHOO/SI_Y06", caption:"Youyue^ (Y06)" },
  { ticket:"G10", value:"YAHOO/SI_G10", caption:"Yuexiu Prop 2k (G10)" },
  { ticket:"D5N", value:"YAHOO/SI_D5N", caption:"Z-Obee (D5N)" },
  { ticket:"Z01", value:"YAHOO/SI_Z01", caption:"Zagro (Z01)" },
  { ticket:"I9T", value:"YAHOO/SI_I9T", caption:"Ziwo (I9T)" },
  { ticket:"A05", value:"YAHOO/SI_A05", caption:"a AVJennings A$ (A05)" },
  { ticket:"O02", value:"YAHOO/SI_O02", caption:"a OGL Resources A$ (O02)" },
  { ticket:"S21", value:"YAHOO/SI_S21", caption:"e Genting HK US$ (S21)" },
  { ticket:"T15", value:"YAHOO/SI_T15", caption:"h TCIL 3k HK$ (T15)" },
  { ticket:"K3HD", value:"YAHOO/SI_K3HD", caption:"u ACH ADR 10US$ (K3HD)" },
  { ticket:"PU0D", value:"YAHOO/SI_PU0D", caption:"u ALU ADR 10US$ (PU0D)" },
  { ticket:"PT7D", value:"YAHOO/SI_PT7D", caption:"u ALUM ADR 10US$ (PT7D)" },
  { ticket:"K3SD", value:"YAHOO/SI_K3SD", caption:"u BIDU ADR 10US$+ (K3SD)" },
  { ticket:"K3CD", value:"YAHOO/SI_K3CD", caption:"u CEA ADR 10US$ (K3CD)" },
  { ticket:"K3ED", value:"YAHOO/SI_K3ED", caption:"u CHA ADR 10US$ (K3ED)" },
  { ticket:"K3PD", value:"YAHOO/SI_K3PD", caption:"u CHL ADR 10US$ (K3PD)" },
  { ticket:"K3ID", value:"YAHOO/SI_K3ID", caption:"u CHU ADR 10US$ (K3ID)" },
  { ticket:"K3RD", value:"YAHOO/SI_K3RD", caption:"u CTRP ADR 10US$+ (K3RD)" },
  { ticket:"K3JD", value:"YAHOO/SI_K3JD", caption:"u CYOU ADR 10US$+ (K3JD)" },
  { ticket:"N6ED", value:"YAHOO/SI_N6ED", caption:"u DCM ADR 10US$ (N6ED)" },
  { ticket:"PU5D", value:"YAHOO/SI_PU5D", caption:"u DEO ADR 10US$ (PU5D)" },
  { ticket:"N6CD", value:"YAHOO/SI_N6CD", caption:"u FMCN ADR 10US$+ (N6CD)" },
  { ticket:"PU2D", value:"YAHOO/SI_PU2D", caption:"u FTE ADR 10US$ (PU2D)" },
  { ticket:"PU6D", value:"YAHOO/SI_PU6D", caption:"u HBC ADR 10US$ (PU6D)" },
  { ticket:"K3UD", value:"YAHOO/SI_K3UD", caption:"u HMIN ADR 10US$+ (K3UD)" },
  { ticket:"K3FD", value:"YAHOO/SI_K3FD", caption:"u HNP ADR 10US$ (K3FD)" },
  { ticket:"N6AD", value:"YAHOO/SI_N6AD", caption:"u JASO ADR 10US$+ (N6AD)" },
  { ticket:"PT8D", value:"YAHOO/SI_PT8D", caption:"u JHX ADR 10US$ (PT8D)" },
  { ticket:"N6DD", value:"YAHOO/SI_N6DD", caption:"u MFG ADR 10US$ (N6DD)" },
  { ticket:"PT6D", value:"YAHOO/SI_PT6D", caption:"u MKTAY ADR 10US$ (PT6D)" },
  { ticket:"K3QD", value:"YAHOO/SI_K3QD", caption:"u MR ADR 10US$+ (K3QD)" },
  { ticket:"N5YD", value:"YAHOO/SI_N5YD", caption:"u MTU ADR 10US$ (N5YD)" },
  { ticket:"K3MD", value:"YAHOO/SI_K3MD", caption:"u NTES ADR 10US$+ (K3MD)" },
  { ticket:"PT9D", value:"YAHOO/SI_PT9D", caption:"u NZT ADR 10US$ (PT9D)" },
  { ticket:"N5ZD", value:"YAHOO/SI_N5ZD", caption:"u PKX ADR 10US$ (N5ZD)" },
  { ticket:"PV0D", value:"YAHOO/SI_PV0D", caption:"u PT ADR 10US$ (PV0D)" },
  { ticket:"K3OD", value:"YAHOO/SI_K3OD", caption:"u PTR ADR 10US$ (K3OD)" },
  { ticket:"PU7D", value:"YAHOO/SI_PU7D", caption:"u RDS/A ADR 10US$ (PU7D)" },
  { ticket:"K3DD", value:"YAHOO/SI_K3DD", caption:"u SHI ADR 10US$ (K3DD)" },
  { ticket:"PU8D", value:"YAHOO/SI_PU8D", caption:"u STO ADR 10US$ (PU8D)" },
  { ticket:"K3ND", value:"YAHOO/SI_K3ND", caption:"u STP ADR 10US$+ (K3ND)" },
  { ticket:"PU9D", value:"YAHOO/SI_PU9D", caption:"u SYT ADR 10US$ (PU9D)" },
  { ticket:"N6FD", value:"YAHOO/SI_N6FD", caption:"u TM ADR 10US$ (N6FD)" },
  { ticket:"PU1D", value:"YAHOO/SI_PU1D", caption:"u TOT ADR 10US$ (PU1D)" },
  { ticket:"K3KD", value:"YAHOO/SI_K3KD", caption:"u TSL ADR 10 US$+ (K3KD)" },
  { ticket:"PU3D", value:"YAHOO/SI_PU3D", caption:"u VE ADR 10US$ (PU3D)" },
  { ticket:"PU4D", value:"YAHOO/SI_PU4D", caption:"u VOD ADR 10US$ (PU4D)" },
  { ticket:"N6GD", value:"YAHOO/SI_N6GD", caption:"u WACLY ADR 10US$ (N6GD)" },
  { ticket:"K3GD", value:"YAHOO/SI_K3GD", caption:"u YZC ADR 10US$ (K3GD)" },
  { ticket:"K3TD", value:"YAHOO/SI_K3TD", caption:"u ZNH ADR 10US$ (K3TD)" }
]

YahooSingapure.getTickets = function(){
  return tickets
}

export default YahooSingapure
