
const ISO3Country = {};

const iso3Countries = [
       { caption: "Afghanistan", value: "AFG"},
		   { caption: "Albania", value: "ALB"},
		   { caption: "Algeria", value: "DZA"},
		   { caption: "American Samoa", value: "ASM"},
		   { caption: "Angola", value: "AGO"},
		   { caption: "Antigua and Barbuda", value: "ATG"},
		   { caption: "Argentina", value: "ARG"},
		   { caption: "Armenia", value: "ARM"},
		   { caption: "Aruba", value: "ABW"},
		   { caption: "Australia", value: "AUS"},
		   { caption: "Austria", value: "AUT"},
		   { caption: "Azerbaijan", value: "AZE"},
		   { caption: "The Bahams", value: "BHS"},
		   { caption: "Kingdom of Bahrain", value: "BHR"},
		   { caption: "Bangladesh", value: "BGD"},
		   { caption: "Barbados", value: "BRB"},
		   { caption: "Belarus", value: "BLR"},
		   { caption: "Belgium", value: "BEL"},
		   { caption: "Belize", value: "BLZ"},
		   { caption: "Benin", value: "BEN"},
		   { caption: "Bermuda", value: "BMU"},
		   { caption: "Bhutan", value: "BTN"},
		   { caption: "Bolivia", value: "BOL"},
		   { caption: "Bosnia & Herzegovina", value: "BIH"},
		   { caption: "Botswana", value: "BWA"},
		   { caption: "Brazil", value: "BRA"},
		   { caption: "Brunei Darussalam", value: "BRN"},
		   { caption: "Bulgaria", value: "BGR"},
		   { caption: "Burkina Faso", value: "BFA"},
		   { caption: "Burundi", value: "BDI"},
		   { caption: "Cambodia", value: "KHM"},
		   { caption: "Cameroon", value: "CMR"},
		   { caption: "Canada", value: "CAN"},
		   { caption: "Cape Verde", value: "CPV"},
		   { caption: "Central African Rep.", value: "CAF"},
		   { caption: "Chad", value: "TCD"},
		   { caption: "Chile", value: "CHL"},
		   { caption: "People's Republic of China: Mainland", value: "CHN"},
		   { caption: "People's Republic of China:Hong Kong", value: "HKG"},
		   { caption: "People's Republic of China:Macao", value: "MAC"},
		   { caption: "Colombia", value: "COL"},
		   { caption: "Comoros", value: "COM"},
		   { caption: "Democratic Republic of Congo", value: "ZAR"},
		   { caption: "Republic of Congo", value: "COG"},
		   { caption: "Costa Rica", value: "CRI"},
		   { caption: "Cote d'Ivoire", value: "CIV"},
		   { caption: "Croatia", value: "HRV"},
		   { caption: "Cuba", value: "CUB"},
		   { caption: "Cyprus", value: "CYP"},
		   { caption: "Czech Republic", value: "CZE"},
		   { caption: "Denmark", value: "DNK"},
		   { caption: "Djibouti", value: "DJI"},
		   { caption: "Dominica", value: "DMA"},
		   { caption: "Dominican Republic", value: "DOM"},
		   { caption: "Ecuador", value: "ECU"},
		   { caption: "Egypt", value: "EGY"},
		   { caption: "El Salvador", value: "SLV"},
		   { caption: "Equatorial Guinea", value: "GNQ"},
		   { caption: "Eritrea", value: "ERI"},
		   { caption: "Estonia", value: "EST"},
		   { caption: "Ethiopia", value: "ETH"},
		   { caption: "Faeroe Islands", value: "FRO"},
		   { caption: "Fiji", value: "FJI"},
		   { caption: "Finland", value: "FIN"},
		   { caption: "France", value: "FRA"},
		   { caption: "French Polynesia", value: "PYF"},
		   { caption: "Gabon", value: "GAB"},
		   { caption: "The Gambia", value: "GMB"},
		   { caption: "Georgia", value: "GEO"},
		   { caption: "Germany", value: "DEU"},
		   { caption: "Ghana", value: "GHA"},
		   { caption: "Gibraltar", value: "GIB"},
		   { caption: "Greece", value: "GRC"},
		   { caption: "Greenland", value: "GRL"},
		   { caption: "Grenada", value: "GRD"},
		   { caption: "Guadeloupe", value: "GLP"},
		   { caption: "Guam", value: "GUM"},
		   { caption: "Guatemala", value: "GTM"},
		   { caption: "French Guiena", value: "GUF"},
		   { caption: "Guinea", value: "GNB"},
		   { caption: "Guinea-Bissau", value: "GIN"},
		   { caption: "Guyana", value: "GUY"},
		   { caption: "Haiti", value: "HTI"},
		   { caption: "Honduras", value: "HND"},
		   { caption: "Hungary", value: "HUN"},
		   { caption: "Iceland", value: "ISL"},
		   { caption: "India", value: "IND"},
		   { caption: "Indonesia", value: "IDN"},
		   { caption: "Islamic Republic of Iran", value: "IRN"},
		   { caption: "Iraq", value: "IRQ"},
		   { caption: "Ireland", value: "IRL"},
		   { caption: "Israel", value: "ISR"},
		   { caption: "Italy", value: "ITA"},
		   { caption: "Jamaica", value: "JAM"},
		   { caption: "Japan", value: "JPN"},
		   { caption: "Jordan", value: "JOR"},
		   { caption: "Kazakhstan", value: "KAZ"},
		   { caption: "Kenya", value: "KEN"},
		   { caption: "Kiribati", value: "KIR"},
		   { caption: "Korea", value: "KOR"},
		   { caption: "Kuwait", value: "KWT"},
		   { caption: "Kyrgyz Republic", value: "KGZ"},
		   { caption: "Lao People's Dem.Rep", value: "LAO"},
		   { caption: "Latvia", value: "LVA"},
		   { caption: "Lebanon", value: "LBN"},
		   { caption: "Lesotho", value: "LSO"},
		   { caption: "Liberia", value: "LBR"},
		   { caption: "Libya", value: "LBY"},
		   { caption: "Lithuania", value: "LTU"},
		   { caption: "Luxembourg", value: "LUX"},
		   { caption: "FYR Macedonia", value: "MKD"},
		   { caption: "Madagascar", value: "MDG"},
		   { caption: "Malawi", value: "MWI"},
		   { caption: "Malaysia", value: "MYS"},
		   { caption: "Maldives", value: "MDV"},
		   { caption: "Mali", value: "MLI"},
		   { caption: "Malta", value: "MLT"},
		   { caption: "Martinique", value: "MTQ"},
		   { caption: "Mauritania", value: "MRT"},
		   { caption: "Mauritius", value: "MUS"},
		   { caption: "Mexico", value: "MEX"},
		   { caption: "Moldova", value: "MDA"},
		   { caption: "Mongolia", value: "MNG"},
		   { caption: "Morocco", value: "MAR"},
		   { caption: "Mozambique", value: "MOZ"},
		   { caption: "Myanmar", value: "MMR"},
		   { caption: "Namibia", value: "NAM"},
		   { caption: "Nauru", value: "NAU"},
		   { caption: "Nepal", value: "NPL"},
		   { caption: "Netherlands", value: "NLD"},
		   { caption: "Netherlands Antilles", value: "ANT"},
		   { caption: "New Caledonia", value: "NCL"},
		   { caption: "New Zealand", value: "NZL"},
		   { caption: "Nicaragua", value: "NIC"},
		   { caption: "Niger", value: "NER"},
		   { caption: "Nigeria", value: "NGA"},
		   { caption: "North Korea", value: "PRK"},
		   { caption: "Norway", value: "NOR"},
		   { caption: "Oman", value: "OMN"},
		   { caption: "Pakistan", value: "PAK"},
		   { caption: "Palau", value: "PLW"},
		   { caption: "Panama", value: "PAN"},
		   { caption: "Papua New Guinea", value: "PNG"},
		   { caption: "Paraguay", value: "PRY"},
		   { caption: "Peru", value: "PER"},
		   { caption: "Philippines", value: "PHL"},
		   { caption: "Poland", value: "POL"},
		   { caption: "Portugal", value: "PRT"},
		   { caption: "Qatar", value: "QAT"},
		   { caption: "RUunion", value: "REU"},
		   { caption: "Romania", value: "ROM"},
		   { caption: "Russia", value: "RUS"},
		   { caption: "Rwanda", value: "RWA"},
		   { caption: "Samoa", value: "WSM"},
		   { caption: "SOo TomU & PrYncipe", value: "STP"},
		   { caption: "Saudi Arabia", value: "SAU"},
		   { caption: "Senegal", value: "SEN"},
		   { caption: "Serbia & Montenegro", value: "SER"},
		   { caption: "Seychelles", value: "SYC"},
		   { caption: "Sierra Leone", value: "SLE"},
		   { caption: "Singapore", value: "SIN"},
		   { caption: "Slovak Republic", value: "SVK"},
		   { caption: "Slovenia", value: "SVN"},
		   { caption: "Solomon Islands", value: "SLB"},
		   { caption: "Somalia", value: "SOM"},
		   { caption: "South Africa", value: "ZAF"},
		   { caption: "Spain", value: "ESP"},
		   { caption: "Sri Lanka", value: "LKA"},
		   { caption: "St. Kitts and Nevis", value: "KNA"},
		   { caption: "St. Lucia", value: "LCA"},
		   { caption: "St. Vincent & Grens.", value: "VCT"},
		   { caption: "Sudan", value: "SDN"},
		   { caption: "Suriname", value: "SUR"},
		   { caption: "Swaziland", value: "SWZ"},
		   { caption: "Sweden", value: "SWE"},
		   { caption: "Switzerland", value: "CHE"},
		   { caption: "Syrian Arab Republic", value: "SYR"},
		   { caption: "Tajikistan", value: "TJK"},
		   { caption: "Tanzania", value: "TZA"},
		   { caption: "Thailand", value: "THA"},
		   { caption: "Togo", value: "TGO"},
		   { caption: "Tonga", value: "TON"},
		   { caption: "Trinidad and Tobago", value: "TTO"},
		   { caption: "Tunisia", value: "TUN"},
		   { caption: "Turkey", value: "TUR"},
		   { caption: "Turkmenistan", value: "TKM"},
		   { caption: "Uganda", value: "UGA"},
		   { caption: "Ukraine", value: "UKR"},
		   { caption: "United Arab Emirates", value: "UAE"},
		   { caption: "United Kingdom", value: "GBR"},
		   { caption: "United States", value: "USA"},
		   { caption: "Uruguay", value: "URY"},
		   { caption: "Uzbekistan", value: "UZB"},
		   { caption: "Vanuatu", value: "VUT"},
		   { caption: "Bolivarian Republic of Venezuela", value: "VEN"},
		   { caption: "Vietnam", value: "VNM"},
		   { caption: "West Bank/Gaza Strip", value: "WBG"},
		   { caption: "Republic of Yemen", value: "YEM"},
		   { caption: "Yugoslavia", value: "YUG"},
		   { caption: "Zambia", value: "ZMB"},
		   { caption: "Zimbabwe", value: "ZWE"}
];

ISO3Country.getCountries = function(){
  return iso3Countries;
}

export default ISO3Country
