
const GoogleSingapure = {};

const tickets = [
  { ticket:"5WE", value:"GOOG/SGX_5WE", caption:"$ Moya Hldg Asia (5WE)" },
{ ticket:"5UY", value:"GOOG/SGX_5UY", caption:"$ OxleyHldg 100 (5UY)" },
{ ticket:"5UE", value:"GOOG/SGX_5UE", caption:"$ SHC Asia (5UE)" },
{ ticket:"502", value:"GOOG/SGX_502", caption:"3Cnergy Ltd (502)" },
{ ticket:"5TG", value:"GOOG/SGX_5TG", caption:"800 Super Holdings Ltd (5TG)" },
{ ticket:"E25", value:"GOOG/SGX_E25", caption:"8Telecom International Holdings Co. Ltd. (E25)" },
{ ticket:"A53", value:"GOOG/SGX_A53", caption:"A-Sonic Aerospace Limited (A53)" },
{ ticket:"5GZ", value:"GOOG/SGX_5GZ", caption:"AA Group Holdings Ltd. (5GZ)" },
{ ticket:"A35", value:"GOOG/SGX_A35", caption:"ABF SG BOND ETF (A35)" },
{ ticket:"533", value:"GOOG/SGX_533", caption:"ABR Holdings Limited (533)" },
{ ticket:"A18", value:"GOOG/SGX_A18", caption:"AEI Corporation Ltd. (A18)" },
{ ticket:"A10", value:"GOOG/SGX_A10", caption:"AEM Holdings Ltd. (A10)" },
{ ticket:"O5RU", value:"GOOG/SGX_O5RU", caption:"AIMS AMP Capital Industrial REIT (O5RU)" },
{ ticket:"5AU", value:"GOOG/SGX_5AU", caption:"AP Oil International Limited (5AU)" },
{ ticket:"D1R", value:"GOOG/SGX_D1R", caption:"ARA Asset Management Limited (D1R)" },
{ ticket:"538", value:"GOOG/SGX_538", caption:"ASJ Holdings Limited (538)" },
{ ticket:"A04", value:"GOOG/SGX_A04", caption:"ASL Marine Holdings Ltd (A04)" },
{ ticket:"575", value:"GOOG/SGX_575", caption:"ASTI Holdings Limited (575)" },
{ ticket:"O2I", value:"GOOG/SGX_O2I", caption:"AVIC International Maritime Holdings Ltd (O2I)" },
{ ticket:"L5I", value:"GOOG/SGX_L5I", caption:"Abterra Ltd. (L5I)" },
{ ticket:"A75", value:"GOOG/SGX_A75", caption:"Ace Achieve Infocom Limited (A75)" },
{ ticket:"A02", value:"GOOG/SGX_A02", caption:"Achieva Limited (A02)" },
{ ticket:"A01", value:"GOOG/SGX_A01", caption:"Acma Ltd (A01)" },
{ ticket:"A59", value:"GOOG/SGX_A59", caption:"Action Asia (A59)" },
{ ticket:"A31", value:"GOOG/SGX_A31", caption:"Addvalue Technologies Limited (A31)" },
{ ticket:"5FH", value:"GOOG/SGX_5FH", caption:"Advance SCT Limited (5FH)" },
{ ticket:"5IA", value:"GOOG/SGX_5IA", caption:"Advanced Holdings Limited (5IA)" },
{ ticket:"A54", value:"GOOG/SGX_A54", caption:"Advanced Integrated Manufacturing Corp. (A54)" },
{ ticket:"5TY", value:"GOOG/SGX_5TY", caption:"Advanced Systems Automation Limited (5TY)" },
{ ticket:"5EF", value:"GOOG/SGX_5EF", caption:"Adventus Holdings Ltd (5EF)" },
{ ticket:"5IB", value:"GOOG/SGX_5IB", caption:"Albedo Limited (5IB)" },
{ ticket:"A13", value:"GOOG/SGX_A13", caption:"Allied Technologies Ltd (A13)" },
{ ticket:"A34", value:"GOOG/SGX_A34", caption:"Amara Holdings Ltd. (A34)" },
{ ticket:"C60", value:"GOOG/SGX_C60", caption:"Amplefield Limited (C60)" },
{ ticket:"M1P", value:"GOOG/SGX_M1P", caption:"Amtek Engineering Ltd (M1P)" },
{ ticket:"MF5", value:"GOOG/SGX_MF5", caption:"Anchun International Holdings Ltd (MF5)" },
{ ticket:"A52", value:"GOOG/SGX_A52", caption:"AnnAik Limited (A52)" },
{ ticket:"5AL", value:"GOOG/SGX_5AL", caption:"Annica Holdings Limited (5AL)" },
{ ticket:"G5X", value:"GOOG/SGX_G5X", caption:"Anwell Technologies Limited (G5X)" },
{ ticket:"5EK", value:"GOOG/SGX_5EK", caption:"Armarda Group Ltd. (5EK)" },
{ ticket:"A14", value:"GOOG/SGX_A14", caption:"Armstrong Industrial Corporation Limited (A14)" },
{ ticket:"5NK", value:"GOOG/SGX_5NK", caption:"Artivision Technologies Ltd. (5NK)" },
{ ticket:"Q1P", value:"GOOG/SGX_Q1P", caption:"Ascendas Hospitality Trust Management (Q1P)" },
{ ticket:"CY6U", value:"GOOG/SGX_CY6U", caption:"Ascendas India Trust (CY6U)" },
{ ticket:"A17U", value:"GOOG/SGX_A17U", caption:"Ascendas Real Estate Investment Trust (A17U)" },
{ ticket:"A68U", value:"GOOG/SGX_A68U", caption:"Ascott Residence Trust (A68U)" },
{ ticket:"A55", value:"GOOG/SGX_A55", caption:"Asia Enterprises Holding Limited (A55)" },
{ ticket:"GH3", value:"GOOG/SGX_GH3", caption:"Asia Fashion Holdings Ltd (GH3)" },
{ ticket:"A46", value:"GOOG/SGX_A46", caption:"Asia Pacific Breweries Ltd. (A46)" },
{ ticket:"5RA", value:"GOOG/SGX_5RA", caption:"Asia Pacific Strategic Investments Ltd (5RA)" },
{ ticket:"A03", value:"GOOG/SGX_A03", caption:"Asia Power Corporation Limited (A03)" },
{ ticket:"505", value:"GOOG/SGX_505", caption:"AsiaMedic Limited (505)" },
{ ticket:"585", value:"GOOG/SGX_585", caption:"Asian Micro Holdings Limited (585)" },
{ ticket:"S7OU", value:"GOOG/SGX_S7OU", caption:"Asian Pay Television Trust (S7OU)" },
{ ticket:"5WV", value:"GOOG/SGX_5WV", caption:"Asiaphos Ltd (5WV)" },
{ ticket:"5ET", value:"GOOG/SGX_5ET", caption:"Asiasons Capital Limited (5ET)" },
{ ticket:"5CR", value:"GOOG/SGX_5CR", caption:"Asiatic Group (Holdings) Limited (5CR)" },
{ ticket:"5AM", value:"GOOG/SGX_5AM", caption:"Asiatravel.com Holdings Ltd (5AM)" },
{ ticket:"A30", value:"GOOG/SGX_A30", caption:"Aspial Corporation (A30)" },
{ ticket:"5UL", value:"GOOG/SGX_5UL", caption:"Atlantic Navigation Holdings (Sing) Ltd (5UL)" },
{ ticket:"A23", value:"GOOG/SGX_A23", caption:"Auric Pacific Group Limited (A23)" },
{ ticket:"5GJ", value:"GOOG/SGX_5GJ", caption:"AusGroup Limited (5GJ)" },
{ ticket:"A15", value:"GOOG/SGX_A15", caption:"Aussino Group Ltd. (A15)" },
{ ticket:"CT1", value:"GOOG/SGX_CT1", caption:"Avi Tech Electronics Ltd. (CT1)" },
{ ticket:"A69", value:"GOOG/SGX_A69", caption:"Azeus Systems Holdings Ltd. (A69)" },
{ ticket:"560", value:"GOOG/SGX_560", caption:"Aztech Group Ltd (560)" },
{ ticket:"KJ5", value:"GOOG/SGX_KJ5", caption:"BBR Holdings (S) Ltd. (KJ5)" },
{ ticket:"B32", value:"GOOG/SGX_B32", caption:"BH Global Corporation Ltd (B32)" },
{ ticket:"B03", value:"GOOG/SGX_B03", caption:"BRC Asia Limited (B03)" },
{ ticket:"568", value:"GOOG/SGX_568", caption:"Baker Technology Limited (568)" },
{ ticket:"B26", value:"GOOG/SGX_B26", caption:"Ban Leong Technologies Ltd (B26)" },
{ ticket:"B58", value:"GOOG/SGX_B58", caption:"Banyan Tree Holdings Ltd (B58)" },
{ ticket:"5MC", value:"GOOG/SGX_5MC", caption:"Beng Kuang Marine Limited (5MC)" },
{ ticket:"B64", value:"GOOG/SGX_B64", caption:"Berger International Ltd (B64)" },
{ ticket:"5ER", value:"GOOG/SGX_5ER", caption:"Best World International Limited (5ER)" },
{ ticket:"B20", value:"GOOG/SGX_B20", caption:"Biosensors International Group Ltd (B20)" },
{ ticket:"A33", value:"GOOG/SGX_A33", caption:"Blumont Group Ltd (A33)" },
{ ticket:"B10", value:"GOOG/SGX_B10", caption:"Boardroom Limited (B10)" },
{ ticket:"B28", value:"GOOG/SGX_B28", caption:"Bonvests Holdings Limited (B28)" },
{ ticket:"F9D", value:"GOOG/SGX_F9D", caption:"Boustead Singapore Limited (F9D)" },
{ ticket:"5DA", value:"GOOG/SGX_5DA", caption:"BreadTalk Group Limited (5DA)" },
{ ticket:"5DT", value:"GOOG/SGX_5DT", caption:"Bright Orient Holding Ltd. (5DT)" },
{ ticket:"B49", value:"GOOG/SGX_B49", caption:"Bright World Precision Machinery Limited (B49)" },
{ ticket:"B08", value:"GOOG/SGX_B08", caption:"British and Malayan Trustees Limited (B08)" },
{ ticket:"B69", value:"GOOG/SGX_B69", caption:"Broadway Industrial Group Ltd (B69)" },
{ ticket:"B61", value:"GOOG/SGX_B61", caption:"Bukit Sembawang Estates Limited (B61)" },
{ ticket:"P8Z", value:"GOOG/SGX_P8Z", caption:"Bumitama Agri Ltd (P8Z)" },
{ ticket:"MQ4", value:"GOOG/SGX_MQ4", caption:"Bund Center Investment Ltd (MQ4)" },
{ ticket:"D79", value:"GOOG/SGX_D79", caption:"C&amp;G Environmental Protection Hldgs Ltd (D79)" },
{ ticket:"C04", value:"GOOG/SGX_C04", caption:"CASA Holdings Ltd (C04)" },
{ ticket:"5RF", value:"GOOG/SGX_5RF", caption:"CCFH Ltd (5RF)" },
{ ticket:"5QZ", value:"GOOG/SGX_5QZ", caption:"CCM Group Ltd (5QZ)" },
{ ticket:"J85", value:"GOOG/SGX_J85", caption:"CDL Hospitality Trusts (J85)" },
{ ticket:"D38", value:"GOOG/SGX_D38", caption:"CDW Holding Limited (D38)" },
{ ticket:"Y35", value:"GOOG/SGX_Y35", caption:"CEFC International Ltd (Y35)" },
{ ticket:"C11", value:"GOOG/SGX_C11", caption:"CEI Contract Manufacturing Limited (C11)" },
{ ticket:"5EB", value:"GOOG/SGX_5EB", caption:"CFM Holdings Limited (5EB)" },
{ ticket:"C13", value:"GOOG/SGX_C13", caption:"CH Offshore Limited (C13)" },
{ ticket:"P5P", value:"GOOG/SGX_P5P", caption:"CIMB APAC Div 100US$ (P5P)" },
{ ticket:"M62", value:"GOOG/SGX_M62", caption:"CIMBASEAN40 100US$ (M62)" },
{ ticket:"C03", value:"GOOG/SGX_C03", caption:"CMProp 100 HK$ (C03)" },
{ ticket:"5GC", value:"GOOG/SGX_5GC", caption:"CNA Group Ltd. (5GC)" },
{ ticket:"5TP", value:"GOOG/SGX_5TP", caption:"CNMC Goldmine Holdings Ltd (5TP)" },
{ ticket:"539", value:"GOOG/SGX_539", caption:"CPH Ltd (539)" },
{ ticket:"C06", value:"GOOG/SGX_C06", caption:"CSC Holdings Limited (C06)" },
{ ticket:"544", value:"GOOG/SGX_544", caption:"CSE Global Ltd. (544)" },
{ ticket:"C14", value:"GOOG/SGX_C14", caption:"CWT Ltd (C14)" },
{ ticket:"K2LU", value:"GOOG/SGX_K2LU", caption:"Cache Logistics Trust (K2LU)" },
{ ticket:"D2U", value:"GOOG/SGX_D2U", caption:"Cacola Furniture International Limited (D2U)" },
{ ticket:"J91U", value:"GOOG/SGX_J91U", caption:"Cambridge Industrial Trust (J91U)" },
{ ticket:"C61U", value:"GOOG/SGX_C61U", caption:"CapitaCommercial Trust (C61U)" },
{ ticket:"C31", value:"GOOG/SGX_C31", caption:"CapitaLand Limited (C31)" },
{ ticket:"C38U", value:"GOOG/SGX_C38U", caption:"CapitaMall Trust (C38U)" },
{ ticket:"JS8", value:"GOOG/SGX_JS8", caption:"CapitaMalls Asia Limited (JS8)" },
{ ticket:"AU8U", value:"GOOG/SGX_AU8U", caption:"CapitaRetail China Trust (AU8U)" },
{ ticket:"530", value:"GOOG/SGX_530", caption:"Cedar Strategic Holdings Ltd (530)" },
{ ticket:"OU8", value:"GOOG/SGX_OU8", caption:"Centurion Corp Ltd (OU8)" },
{ ticket:"573", value:"GOOG/SGX_573", caption:"Challenger Technologies Limited (573)" },
{ ticket:"JA9", value:"GOOG/SGX_JA9", caption:"Changjiang Fertilizer Holdings Ltd (JA9)" },
{ ticket:"D2V", value:"GOOG/SGX_D2V", caption:"Changtian Plastic &amp; Chemical Limited (D2V)" },
{ ticket:"5QT", value:"GOOG/SGX_5QT", caption:"Charisma Energy Services Ltd (5QT)" },
{ ticket:"5NV", value:"GOOG/SGX_5NV", caption:"Chasen Holdings Limited (5NV)" },
{ ticket:"5TW", value:"GOOG/SGX_5TW", caption:"Chaswood Resources Holdings Ltd (5TW)" },
{ ticket:"C05", value:"GOOG/SGX_C05", caption:"Chemical Industries (Far East) Limited (C05)" },
{ ticket:"AV5", value:"GOOG/SGX_AV5", caption:"Chemoil Energy Limited (AV5)" },
{ ticket:"C50", value:"GOOG/SGX_C50", caption:"Cheung Woh Technologies Ltd (C50)" },
{ ticket:"5SY", value:"GOOG/SGX_5SY", caption:"Chew S Group Ltd (5SY)" },
{ ticket:"EP4", value:"GOOG/SGX_EP4", caption:"China Animal Healthcare Ltd (EP4)" },
{ ticket:"T42", value:"GOOG/SGX_T42", caption:"China Auto Electronics Group Limited (T42)" },
{ ticket:"G92", value:"GOOG/SGX_G92", caption:"China Aviation Oil (Singapore) Corp. Ltd (G92)" },
{ ticket:"AD7", value:"GOOG/SGX_AD7", caption:"China Bearing (Singapore) Ltd. (AD7)" },
{ ticket:"T16", value:"GOOG/SGX_T16", caption:"China Dairy Group Ltd. (T16)" },
{ ticket:"A0G", value:"GOOG/SGX_A0G", caption:"China Energy Limited (A0G)" },
{ ticket:"5OU", value:"GOOG/SGX_5OU", caption:"China Environment Limited (5OU)" },
{ ticket:"G54", value:"GOOG/SGX_G54", caption:"China Essence Group Ltd. (G54)" },
{ ticket:"A8J", value:"GOOG/SGX_A8J", caption:"China Farm Equipment Limited (A8J)" },
{ ticket:"F6D", value:"GOOG/SGX_F6D", caption:"China Fibretech Ltd. (F6D)" },
{ ticket:"B0Z", value:"GOOG/SGX_B0Z", caption:"China Fishery Group Limited (B0Z)" },
{ ticket:"C59", value:"GOOG/SGX_C59", caption:"China Flexible Packaging Holdings Ltd (C59)" },
{ ticket:"I4U", value:"GOOG/SGX_I4U", caption:"China Gaoxian Fibre Fabric Holdings Ltd (I4U)" },
{ ticket:"D50", value:"GOOG/SGX_D50", caption:"China Great Land Holdings Ltd. (D50)" },
{ ticket:"C92", value:"GOOG/SGX_C92", caption:"China Haida Ltd. (C92)" },
{ ticket:"C0Z", value:"GOOG/SGX_C0Z", caption:"China Hongcheng Holdings Ltd. (C0Z)" },
{ ticket:"C37", value:"GOOG/SGX_C37", caption:"China International Holdings Limited (C37)" },
{ ticket:"J18", value:"GOOG/SGX_J18", caption:"China Jishan Holdings Limited (J18)" },
{ ticket:"GU5", value:"GOOG/SGX_GU5", caption:"China Kunda Technology Holdings Limited (GU5)" },
{ ticket:"C22", value:"GOOG/SGX_C22", caption:"China Merchants Holdings (Pacific) Ltd (C22)" },
{ ticket:"Y34", value:"GOOG/SGX_Y34", caption:"China Mining International Ltd (Y34)" },
{ ticket:"K2N", value:"GOOG/SGX_K2N", caption:"China Minzhong Food Corporation Limited (K2N)" },
{ ticket:"D4N", value:"GOOG/SGX_D4N", caption:"China New Town Development Co. Ltd. (D4N)" },
{ ticket:"DT2", value:"GOOG/SGX_DT2", caption:"China Oilfield Technology Services Group (DT2)" },
{ ticket:"C71", value:"GOOG/SGX_C71", caption:"China Paper Holdings Limited (C71)" },
{ ticket:"Z02", value:"GOOG/SGX_Z02", caption:"China Powerplus Limited (Z02)" },
{ ticket:"B3C", value:"GOOG/SGX_B3C", caption:"China Print Power Group Ltd (B3C)" },
{ ticket:"FQ8", value:"GOOG/SGX_FQ8", caption:"China Sports International Limited. (FQ8)" },
{ ticket:"CH8", value:"GOOG/SGX_CH8", caption:"China Sunsine Chemical Holdings Ltd. (CH8)" },
{ ticket:"F2X", value:"GOOG/SGX_F2X", caption:"China Taisan Tech. Group Holdings Ltd. (F2X)" },
{ ticket:"B9R", value:"GOOG/SGX_B9R", caption:"China XLX Fertiliser Ltd. (B9R)" },
{ ticket:"5KK", value:"GOOG/SGX_5KK", caption:"China Yongsheng Limited (5KK)" },
{ ticket:"B2X", value:"GOOG/SGX_B2X", caption:"China Yuanbang Property Holdings Ltd. (B2X)" },
{ ticket:"RS1", value:"GOOG/SGX_RS1", caption:"ChinaEnvRes 4k (RS1)" },
{ ticket:"P74", value:"GOOG/SGX_P74", caption:"ChinaKangda (P74)" },
{ ticket:"O2R", value:"GOOG/SGX_O2R", caption:"Chinasing Investment Holdings Limited (O2R)" },
{ ticket:"S91", value:"GOOG/SGX_S91", caption:"Chinavision Media Group Limited (S91)" },
{ ticket:"5CJ", value:"GOOG/SGX_5CJ", caption:"Chinese Global Investors Group Ltd (5CJ)" },
{ ticket:"C29", value:"GOOG/SGX_C29", caption:"Chip Eng Seng Corporation Ltd (C29)" },
{ ticket:"C10", value:"GOOG/SGX_C10", caption:"Chosen Holdings Limited (C10)" },
{ ticket:"C33", value:"GOOG/SGX_C33", caption:"Chuan Hup Holdings Limited (C33)" },
{ ticket:"C09", value:"GOOG/SGX_C09", caption:"City Developments Limited (C09)" },
{ ticket:"C70", value:"GOOG/SGX_C70", caption:"City Developments Limited (C70)" },
{ ticket:"A7RU", value:"GOOG/SGX_A7RU", caption:"CitySpring Infrastructure Trust (A7RU)" },
{ ticket:"5HJ", value:"GOOG/SGX_5HJ", caption:"Cityneon Holdings Limited (5HJ)" },
{ ticket:"P9D", value:"GOOG/SGX_P9D", caption:"Civmec Ltd (P9D)" },
{ ticket:"KJ9", value:"GOOG/SGX_KJ9", caption:"Cogent Holdings Ltd (KJ9)" },
{ ticket:"567", value:"GOOG/SGX_567", caption:"Colex Holdings Limited (567)" },
{ ticket:"N0Z", value:"GOOG/SGX_N0Z", caption:"Combine Will International Holdings Ltd (N0Z)" },
{ ticket:"C52", value:"GOOG/SGX_C52", caption:"ComfortDelGro Corporation Limited (C52)" },
{ ticket:"5HT", value:"GOOG/SGX_5HT", caption:"Communication Design International Ltd. (5HT)" },
{ ticket:"T4E", value:"GOOG/SGX_T4E", caption:"Compact Metal Industries Ltd (T4E)" },
{ ticket:"L1D", value:"GOOG/SGX_L1D", caption:"Consciencefood (L1D)" },
{ ticket:"P8A", value:"GOOG/SGX_P8A", caption:"Cordlife Group Ltd (P8A)" },
{ ticket:"C41", value:"GOOG/SGX_C41", caption:"Cortina Holdings Limited (C41)" },
{ ticket:"F83", value:"GOOG/SGX_F83", caption:"Cosco Corporation (Singapore) Limited (F83)" },
{ ticket:"B9S", value:"GOOG/SGX_B9S", caption:"CosmoSteel Holdings Limited (B9S)" },
{ ticket:"E91", value:"GOOG/SGX_E91", caption:"Courage Marine Group Limited (E91)" },
{ ticket:"RE2", value:"GOOG/SGX_RE2", caption:"Courts Asia Ltd (RE2)" },
{ ticket:"541", value:"GOOG/SGX_541", caption:"Craft Print International Limited (541)" },
{ ticket:"C76", value:"GOOG/SGX_C76", caption:"Creative Technology Ltd. (C76)" },
{ ticket:"S6NU", value:"GOOG/SGX_S6NU", caption:"Croesus Retail Trust (S6NU)" },
{ ticket:"MU7", value:"GOOG/SGX_MU7", caption:"DBS Bk 4.7% NCPS 100 (MU7)" },
{ ticket:"D05", value:"GOOG/SGX_D05", caption:"DBS Group Holdings Ltd (D05)" },
{ ticket:"LF1", value:"GOOG/SGX_LF1", caption:"DBXT ASX200 10US$ (LF1)" },
{ ticket:"K6Y", value:"GOOG/SGX_K6Y", caption:"DBXT AUDBonds 5AU$ (K6Y)" },
{ ticket:"KV5", value:"GOOG/SGX_KV5", caption:"DBXT AUDCS 5AU$ (KV5)" },
{ ticket:"KV7", value:"GOOG/SGX_KV7", caption:"DBXT AUDCS 5SG$ (KV7)" },
{ ticket:"KV6", value:"GOOG/SGX_KV6", caption:"DBXT AUDCS 5US$ (KV6)" },
{ ticket:"KT4", value:"GOOG/SGX_KT4", caption:"DBXT CSI300 10US$ (KT4)" },
{ ticket:"HD8", value:"GOOG/SGX_HD8", caption:"DBXT China25 10US$ (HD8)" },
{ ticket:"L5G", value:"GOOG/SGX_L5G", caption:"DBXT DBCBLEB 10US$ (L5G)" },
{ ticket:"L5F", value:"GOOG/SGX_L5F", caption:"DBXT DBCDJUBS10US$ (L5F)" },
{ ticket:"J0S", value:"GOOG/SGX_J0S", caption:"DBXT DBLCI-OY 5US$ (J0S)" },
{ ticket:"IH0", value:"GOOG/SGX_IH0", caption:"DBXT E50 10US$ (IH0)" },
{ ticket:"KV8", value:"GOOG/SGX_KV8", caption:"DBXT EONIA 5US$ (KV8)" },
{ ticket:"O9A", value:"GOOG/SGX_O9A", caption:"DBXT MS SING 10US$ (O9A)" },
{ ticket:"O9B", value:"GOOG/SGX_O9B", caption:"DBXT MSASPAC 10US$ (O9B)" },
{ ticket:"N2F", value:"GOOG/SGX_N2F", caption:"DBXT MSAXJHDY10US$ (N2F)" },
{ ticket:"IH1", value:"GOOG/SGX_IH1", caption:"DBXT MSAsExJp10US$ (IH1)" },
{ ticket:"O9C", value:"GOOG/SGX_O9C", caption:"DBXT MSBANGL 10US$ (O9C)" },
{ ticket:"J0O", value:"GOOG/SGX_J0O", caption:"DBXT MSBrazil10US$ (J0O)" },
{ ticket:"LG9", value:"GOOG/SGX_LG9", caption:"DBXT MSCHINA 10US$ (LG9)" },
{ ticket:"J0N", value:"GOOG/SGX_J0N", caption:"DBXT MSEMAsia10US$ (J0N)" },
{ ticket:"J0M", value:"GOOG/SGX_J0M", caption:"DBXT MSEmer 10US$ (J0M)" },
{ ticket:"IH3", value:"GOOG/SGX_IH3", caption:"DBXT MSEurope10US$ (IH3)" },
{ ticket:"LG8", value:"GOOG/SGX_LG8", caption:"DBXT MSINDIA 10US$ (LG8)" },
{ ticket:"KJ7", value:"GOOG/SGX_KJ7", caption:"DBXT MSINDO 10US$ (KJ7)" },
{ ticket:"LF2", value:"GOOG/SGX_LF2", caption:"DBXT MSJAP 10US$ (LF2)" },
{ ticket:"IH2", value:"GOOG/SGX_IH2", caption:"DBXT MSKorea 10US$ (IH2)" },
{ ticket:"LG6", value:"GOOG/SGX_LG6", caption:"DBXT MSMSIA 10US$ (LG6)" },
{ ticket:"O9D", value:"GOOG/SGX_O9D", caption:"DBXT MSPAKIS 10US$ (O9D)" },
{ ticket:"N2E", value:"GOOG/SGX_N2E", caption:"DBXT MSPHILS 10US$ (N2E)" },
{ ticket:"J0Q", value:"GOOG/SGX_J0Q", caption:"DBXT MSPacXJp10US$ (J0Q)" },
{ ticket:"J0R", value:"GOOG/SGX_J0R", caption:"DBXT MSRussia10US$ (J0R)" },
{ ticket:"LG7", value:"GOOG/SGX_LG7", caption:"DBXT MSTHAI 10US$ (LG7)" },
{ ticket:"HD7", value:"GOOG/SGX_HD7", caption:"DBXT MSTaiwan10US$ (HD7)" },
{ ticket:"KF8", value:"GOOG/SGX_KF8", caption:"DBXT MSUSA 10US$ (KF8)" },
{ ticket:"J0P", value:"GOOG/SGX_J0P", caption:"DBXT MSWorld 10US$ (J0P)" },
{ ticket:"HE0", value:"GOOG/SGX_HE0", caption:"DBXT Nifty 10US$ (HE0)" },
{ ticket:"K6K", value:"GOOG/SGX_K6K", caption:"DBXT S&amp;P500 10US$ (K6K)" },
{ ticket:"HD6", value:"GOOG/SGX_HD6", caption:"DBXT S&amp;PShort10US$ (HD6)" },
{ ticket:"KJ6", value:"GOOG/SGX_KJ6", caption:"DBXT SORA 5SG$ (KJ6)" },
{ ticket:"KT3", value:"GOOG/SGX_KT3", caption:"DBXT STGLDv 10US$ (KT3)" },
{ ticket:"IH4", value:"GOOG/SGX_IH4", caption:"DBXT USDCS 5US$ (IH4)" },
{ ticket:"KF5", value:"GOOG/SGX_KF5", caption:"DBXT USDIGInfl5US$ (KF5)" },
{ ticket:"HD9", value:"GOOG/SGX_HD9", caption:"DBXT Vietnam 10US$ (HD9)" },
{ ticket:"SH8", value:"GOOG/SGX_SH8", caption:"DBXT iBoxxIDR 10US$ (SH8)" },
{ ticket:"KT2", value:"GOOG/SGX_KT2", caption:"DBXT iBoxxKR 5US$ (KT2)" },
{ ticket:"KV4", value:"GOOG/SGX_KV4", caption:"DBXT iBoxxSing5SG$ (KV4)" },
{ ticket:"KF6", value:"GOOG/SGX_KF6", caption:"DBXT iBoxxSvEu5US$ (KF6)" },
{ ticket:"KF7", value:"GOOG/SGX_KF7", caption:"DBXT iBoxxUSTr5US$ (KF7)" },
{ ticket:"5CH", value:"GOOG/SGX_5CH", caption:"DMX Technologies Group Limited (5CH)" },
{ ticket:"D01", value:"GOOG/SGX_D01", caption:"Dairy Farm International Holdings Ltd (D01)" },
{ ticket:"FP1", value:"GOOG/SGX_FP1", caption:"Dapai International Holdings Co Ltd (FP1)" },
{ ticket:"D04", value:"GOOG/SGX_D04", caption:"Datapulse Technology Limited (D04)" },
{ ticket:"K2M", value:"GOOG/SGX_K2M", caption:"Debao Property Development Ltd. (K2M)" },
{ ticket:"5UZ", value:"GOOG/SGX_5UZ", caption:"Declout Ltd (5UZ)" },
{ ticket:"D03", value:"GOOG/SGX_D03", caption:"Del Monte Pacific Limited (D03)" },
{ ticket:"B1N", value:"GOOG/SGX_B1N", caption:"Delong Holdings Limited (B1N)" },
{ ticket:"D11", value:"GOOG/SGX_D11", caption:"Design Studio Furniture Manufacturer Ltd (D11)" },
{ ticket:"D08", value:"GOOG/SGX_D08", caption:"Devotion Energy Group Limited (D08)" },
{ ticket:"G77", value:"GOOG/SGX_G77", caption:"Digiland International Ltd (G77)" },
{ ticket:"MT1", value:"GOOG/SGX_MT1", caption:"Dragon Group International Limited (MT1)" },
{ ticket:"GJ8", value:"GOOG/SGX_GJ8", caption:"Dukang Distillers Holdings Ltd (GJ8)" },
{ ticket:"CZ4", value:"GOOG/SGX_CZ4", caption:"Dutech Holdings Limited (CZ4)" },
{ ticket:"5SO", value:"GOOG/SGX_5SO", caption:"Duty Free International Ltd (5SO)" },
{ ticket:"NO4", value:"GOOG/SGX_NO4", caption:"Dyna-Mac Holding Ltd (NO4)" },
{ ticket:"D6U", value:"GOOG/SGX_D6U", caption:"Dynamic Colours Limited (D6U)" },
{ ticket:"E18", value:"GOOG/SGX_E18", caption:"ECS Holdings Limited (E18)" },
{ ticket:"5DE", value:"GOOG/SGX_5DE", caption:"EMS Energy Limited (5DE)" },
{ ticket:"5RC", value:"GOOG/SGX_5RC", caption:"ES Group (Holdings) Limited (5RC)" },
{ ticket:"N0L", value:"GOOG/SGX_N0L", caption:"EastGate Technology Ltd. (N0L)" },
{ ticket:"5KU", value:"GOOG/SGX_5KU", caption:"Eastern Holdings Ltd (5KU)" },
{ ticket:"E16", value:"GOOG/SGX_E16", caption:"Elec &amp; Eltek International Co. Ltd. (E16)" },
{ ticket:"5VU", value:"GOOG/SGX_5VU", caption:"Elektromotive Group Ltd (5VU)" },
{ ticket:"550", value:"GOOG/SGX_550", caption:"Elite KSB Holdings Limited (550)" },
{ ticket:"E13", value:"GOOG/SGX_E13", caption:"Ellipsiz Ltd. (E13)" },
{ ticket:"S44", value:"GOOG/SGX_S44", caption:"Engro Corporation Limited (S44)" },
{ ticket:"L23", value:"GOOG/SGX_L23", caption:"Enviro-Hub Holdings Limited (L23)" },
{ ticket:"5MQ", value:"GOOG/SGX_5MQ", caption:"Epicentre Holdings Limited (5MQ)" },
{ ticket:"532", value:"GOOG/SGX_532", caption:"Equation Corp. Limited (532)" },
{ ticket:"FO8", value:"GOOG/SGX_FO8", caption:"Eratat Lifestyle Limited (FO8)" },
{ ticket:"R9D", value:"GOOG/SGX_R9D", caption:"Etika A (R9D)" },
{ ticket:"5FR", value:"GOOG/SGX_5FR", caption:"Etika International Holdings Limited (5FR)" },
{ ticket:"E02", value:"GOOG/SGX_E02", caption:"Eu Yan Sang International Ltd. (E02)" },
{ ticket:"E27", value:"GOOG/SGX_E27", caption:"Eucon Holding Limited (E27)" },
{ ticket:"E23", value:"GOOG/SGX_E23", caption:"Europtronic Group Ltd. (E23)" },
{ ticket:"E17", value:"GOOG/SGX_E17", caption:"Excelpoint Technology Ltd (E17)" },
{ ticket:"5ME", value:"GOOG/SGX_5ME", caption:"EzionHldg (5ME)" },
{ ticket:"5DN", value:"GOOG/SGX_5DN", caption:"Ezra Holdings Limited (5DN)" },
{ ticket:"F10", value:"GOOG/SGX_F10", caption:"F J Benjamin Holdings Ltd (F10)" },
{ ticket:"F07", value:"GOOG/SGX_F07", caption:"FDS Networks Group Ltd (F07)" },
{ ticket:"I54", value:"GOOG/SGX_I54", caption:"Fabchem China Ltd (I54)" },
{ ticket:"5FL", value:"GOOG/SGX_5FL", caption:"Falcon Energy Group Limited (5FL)" },
{ ticket:"5TJ", value:"GOOG/SGX_5TJ", caption:"Far East Group Ltd (5TJ)" },
{ ticket:"Q5T", value:"GOOG/SGX_Q5T", caption:"Far East Hospitality Trust (Q5T)" },
{ ticket:"O10", value:"GOOG/SGX_O10", caption:"Far East Orchard Ltd (O10)" },
{ ticket:"F20", value:"GOOG/SGX_F20", caption:"Federal International (2000) Ltd. (F20)" },
{ ticket:"5F4", value:"GOOG/SGX_5F4", caption:"Figtree Holdings Ltd (5F4)" },
{ ticket:"AW9U", value:"GOOG/SGX_AW9U", caption:"First Real Estate Investment Trust (AW9U)" },
{ ticket:"EB5", value:"GOOG/SGX_EB5", caption:"First Resources Ltd (EB5)" },
{ ticket:"D8DU", value:"GOOG/SGX_D8DU", caption:"First Ship Lease Trust (D8DU)" },
{ ticket:"F22", value:"GOOG/SGX_F22", caption:"Fischer Tech Ltd. (F22)" },
{ ticket:"F03", value:"GOOG/SGX_F03", caption:"Food Empire Holdings Limited (F03)" },
{ ticket:"529", value:"GOOG/SGX_529", caption:"Food Junction Holdings Limited (529)" },
{ ticket:"B0I", value:"GOOG/SGX_B0I", caption:"Foreland Fabrictech Holdings Ltd. (B0I)" },
{ ticket:"LG2U", value:"GOOG/SGX_LG2U", caption:"Forterra Trust (LG2U)" },
{ ticket:"F25U", value:"GOOG/SGX_F25U", caption:"Fortune Real Estate Investment Trust (F25U)" },
{ ticket:"F31", value:"GOOG/SGX_F31", caption:"Fragrance Group Limited (F31)" },
{ ticket:"F99", value:"GOOG/SGX_F99", caption:"Fraser and Neave Limited (F99)" },
{ ticket:"J69U", value:"GOOG/SGX_J69U", caption:"Frasers Centrepoint Trust (J69U)" },
{ ticket:"R8V", value:"GOOG/SGX_R8V", caption:"Frasers Comm A (R8V)" },
{ ticket:"KT8U", value:"GOOG/SGX_KT8U", caption:"Frasers Commercial Trust (KT8U)" },
{ ticket:"ND8U", value:"GOOG/SGX_ND8U", caption:"Frasers Commercial Trust (ND8U)" },
{ ticket:"E28", value:"GOOG/SGX_E28", caption:"Frencken Group Limited (E28)" },
{ ticket:"F13", value:"GOOG/SGX_F13", caption:"Fu Yu Corporation Ltd (F13)" },
{ ticket:"508", value:"GOOG/SGX_508", caption:"Fuji Offset Plates Manufacturing Ltd (508)" },
{ ticket:"5KT", value:"GOOG/SGX_5KT", caption:"Fujian Zhenyun Plastics Industry Co. Ltd (5KT)" },
{ ticket:"F18", value:"GOOG/SGX_F18", caption:"Full Apex (Holdings) Ltd (F18)" },
{ ticket:"F11", value:"GOOG/SGX_F11", caption:"Fung Choi Media Group Limited (F11)" },
{ ticket:"DC9", value:"GOOG/SGX_DC9", caption:"Fuxing China Group Limited (DC9)" },
{ ticket:"G41", value:"GOOG/SGX_G41", caption:"G. K. Goh Holdings Limited (G41)" },
{ ticket:"5VP", value:"GOOG/SGX_5VP", caption:"GDS Global Ltd (5VP)" },
{ ticket:"595", value:"GOOG/SGX_595", caption:"GKE Corporation Ltd (595)" },
{ ticket:"O87", value:"GOOG/SGX_O87", caption:"GLD 10US$ (O87)" },
{ ticket:"5IM", value:"GOOG/SGX_5IM", caption:"GMG Global Ltd (5IM)" },
{ ticket:"G08", value:"GOOG/SGX_G08", caption:"GP Batteries International Ltd. (G08)" },
{ ticket:"G20", value:"GOOG/SGX_G20", caption:"GP Industries Limited (G20)" },
{ ticket:"G18", value:"GOOG/SGX_G18", caption:"GRP Ltd (G18)" },
{ ticket:"J16", value:"GOOG/SGX_J16", caption:"GSH Corporation Ltd (J16)" },
{ ticket:"5IG", value:"GOOG/SGX_5IG", caption:"Gallant Venture Ltd. (5IG)" },
{ ticket:"RF7", value:"GOOG/SGX_RF7", caption:"Gaylin Holdings Ltd (RF7)" },
{ ticket:"AM3", value:"GOOG/SGX_AM3", caption:"Gems TV Holdings Ltd. (AM3)" },
{ ticket:"S21", value:"GOOG/SGX_S21", caption:"Genting Hong Kong Limited (Malaysia) (S21)" },
{ ticket:"G13", value:"GOOG/SGX_G13", caption:"Genting Singapore PLC (G13)" },
{ ticket:"RE4", value:"GOOG/SGX_RE4", caption:"Geo Energy Resources Ltd (RE4)" },
{ ticket:"542", value:"GOOG/SGX_542", caption:"Giken Sakata (S) Limited (542)" },
{ ticket:"G11", value:"GOOG/SGX_G11", caption:"Globa (G11)" },
{ ticket:"QS9", value:"GOOG/SGX_QS9", caption:"Global Invacom Group Ltd (QS9)" },
{ ticket:"B73", value:"GOOG/SGX_B73", caption:"Global Investments Limited (B73)" },
{ ticket:"MC0", value:"GOOG/SGX_MC0", caption:"Global Logistic Properties Ltd (MC0)" },
{ ticket:"K6J", value:"GOOG/SGX_K6J", caption:"Global Palm Resources Holdings Ltd (K6J)" },
{ ticket:"P9J", value:"GOOG/SGX_P9J", caption:"Global Premium Hotels Ltd (P9J)" },
{ ticket:"G31", value:"GOOG/SGX_G31", caption:"Global Testing Corporation Limited (G31)" },
{ ticket:"Y07", value:"GOOG/SGX_Y07", caption:"Global Yellow Pages Limited (Y07)" },
{ ticket:"E5H", value:"GOOG/SGX_E5H", caption:"Golden Agri-Resources Ltd (E5H)" },
{ ticket:"KU3", value:"GOOG/SGX_KU3", caption:"Golden Ocean (KU3)" },
{ ticket:"5PC", value:"GOOG/SGX_5PC", caption:"Goodland Group Ltd (5PC)" },
{ ticket:"G05", value:"GOOG/SGX_G05", caption:"Goodpack Limited (G05)" },
{ ticket:"G50", value:"GOOG/SGX_G50", caption:"Grand Banks Yachts Ltd (G50)" },
{ ticket:"G07", value:"GOOG/SGX_G07", caption:"Great Eastern Holding Limited (G07)" },
{ ticket:"I5H", value:"GOOG/SGX_I5H", caption:"Great Group Holdings Ltd (I5H)" },
{ ticket:"G09", value:"GOOG/SGX_G09", caption:"Gul Technologies Singapore Ltd (G09)" },
{ ticket:"F17", value:"GOOG/SGX_F17", caption:"GuocoLand Limited (F17)" },
{ ticket:"B16", value:"GOOG/SGX_B16", caption:"GuocoLeisure Ltd (B16)" },
{ ticket:"G33", value:"GOOG/SGX_G33", caption:"Guthrie GTS Limited (G33)" },
{ ticket:"526", value:"GOOG/SGX_526", caption:"HG Metal Manufacturing Ltd. (526)" },
{ ticket:"L18", value:"GOOG/SGX_L18", caption:"HL Global Enterprises Limited (L18)" },
{ ticket:"H27", value:"GOOG/SGX_H27", caption:"HLH Group Ltd. (H27)" },
{ ticket:"H64", value:"GOOG/SGX_H64", caption:"HTL International Holdings Limited (H64)" },
{ ticket:"5VS", value:"GOOG/SGX_5VS", caption:"Hafary Holdings Ltd (5VS)" },
{ ticket:"GG7", value:"GOOG/SGX_GG7", caption:"Hai Leck Holdings Limited (GG7)" },
{ ticket:"5VJ", value:"GOOG/SGX_5VJ", caption:"Halcyon Agri Corporation Ltd (5VJ)" },
{ ticket:"B22", value:"GOOG/SGX_B22", caption:"HanKore Environment Tech Group Ltd (B22)" },
{ ticket:"DM0", value:"GOOG/SGX_DM0", caption:"Hanwell Holdings Ltd (DM0)" },
{ ticket:"5SS", value:"GOOG/SGX_5SS", caption:"Harry S Hldg Ltd. (5SS)" },
{ ticket:"5FU", value:"GOOG/SGX_5FU", caption:"Hartawan Holdings Limited (5FU)" },
{ ticket:"H02", value:"GOOG/SGX_H02", caption:"Haw Par Corporation Ltd. (H02)" },
{ ticket:"588", value:"GOOG/SGX_588", caption:"Health Management International Ltd. (588)" },
{ ticket:"5NG", value:"GOOG/SGX_5NG", caption:"Healthway Medical Corporation Limited (5NG)" },
{ ticket:"5OR", value:"GOOG/SGX_5OR", caption:"Heatec Jietong Holdings Ltd (5OR)" },
{ ticket:"5DP", value:"GOOG/SGX_5DP", caption:"Heeton Holdings Limited (5DP)" },
{ ticket:"I85", value:"GOOG/SGX_I85", caption:"Hengxin Technology Ltd. (I85)" },
{ ticket:"5PD", value:"GOOG/SGX_5PD", caption:"Hengyang Petrochemical Logistics Ltd. (5PD)" },
{ ticket:"H17", value:"GOOG/SGX_H17", caption:"Hi-P International Limited (H17)" },
{ ticket:"5JK", value:"GOOG/SGX_5JK", caption:"Hiap Hoe Ltd (5JK)" },
{ ticket:"510", value:"GOOG/SGX_510", caption:"Hiap Seng Engineering Ltd. (510)" },
{ ticket:"5PO", value:"GOOG/SGX_5PO", caption:"Hiap Tong Corporation Ltd (5PO)" },
{ ticket:"FV2", value:"GOOG/SGX_FV2", caption:"Hisaka Holdings Ltd (FV2)" },
{ ticket:"H13", value:"GOOG/SGX_H13", caption:"Ho Bee Land Ltd (H13)" },
{ ticket:"J2T", value:"GOOG/SGX_J2T", caption:"Hock Lian Seng Holdings Limited (J2T)" },
{ ticket:"H20", value:"GOOG/SGX_H20", caption:"Hoe Leong Corporation Ltd. (H20)" },
{ ticket:"H30", value:"GOOG/SGX_H30", caption:"Hong Fok Corporation Limited (H30)" },
{ ticket:"H22", value:"GOOG/SGX_H22", caption:"Hong Leong Asia Ltd. (H22)" },
{ ticket:"S41", value:"GOOG/SGX_S41", caption:"Hong Leong Finance Ltd (S41)" },
{ ticket:"H78", value:"GOOG/SGX_H78", caption:"Hongkong Land Holdings Limited (H78)" },
{ ticket:"H06", value:"GOOG/SGX_H06", caption:"Hor Kew Corporation Ltd (H06)" },
{ ticket:"5EV", value:"GOOG/SGX_5EV", caption:"Hosen Group Ltd. (5EV)" },
{ ticket:"H18", value:"GOOG/SGX_H18", caption:"Hotel Grand Central Limited (H18)" },
{ ticket:"H15", value:"GOOG/SGX_H15", caption:"Hotel Properties Limited (H15)" },
{ ticket:"H12", value:"GOOG/SGX_H12", caption:"Hotel Royal Limited (H12)" },
{ ticket:"NT1", value:"GOOG/SGX_NT1", caption:"Hotung Investment Holdings Ltd (NT1)" },
{ ticket:"E5P", value:"GOOG/SGX_E5P", caption:"Hour Glass Ltd (E5P)" },
{ ticket:"KI3", value:"GOOG/SGX_KI3", caption:"Hu An Cable Holdings Ltd (KI3)" },
{ ticket:"H16", value:"GOOG/SGX_H16", caption:"Huan Hsin Holdings Ltd. (H16)" },
{ ticket:"H73", value:"GOOG/SGX_H73", caption:"HupSteel Limited (H73)" },
{ ticket:"NS8U", value:"GOOG/SGX_NS8U", caption:"Hutchison Port Hldg Trust (NS8U)" },
{ ticket:"H19", value:"GOOG/SGX_H19", caption:"Hwa Hong Corporation Limited (H19)" },
{ ticket:"600", value:"GOOG/SGX_600", caption:"Hyflux Ltd. (600)" },
{ ticket:"N2H", value:"GOOG/SGX_N2H", caption:"Hyflux Ltd. (N2H)" },
{ ticket:"536", value:"GOOG/SGX_536", caption:"ICP Ltd (536)" },
{ ticket:"5TN", value:"GOOG/SGX_5TN", caption:"IEV Holdings Ltd (5TN)" },
{ ticket:"I49", value:"GOOG/SGX_I49", caption:"IFS Capital Ltd. (I49)" },
{ ticket:"Q0F", value:"GOOG/SGX_Q0F", caption:"IHH Healthcare Bhd (Q0F)" },
{ ticket:"I12", value:"GOOG/SGX_I12", caption:"IPC Corporation Ltd. (I12)" },
{ ticket:"N6M", value:"GOOG/SGX_N6M", caption:"IS ASIA BND 100US$ (N6M)" },
{ ticket:"O9P", value:"GOOG/SGX_O9P", caption:"IS ASIA HYG100US$ (O9P)" },
{ ticket:"I21", value:"GOOG/SGX_I21", caption:"IS DJ USTECH 10US$ (I21)" },
{ ticket:"O9Q", value:"GOOG/SGX_O9Q", caption:"IS LC 1-3Y 100US$ (O9Q)" },
{ ticket:"N6L", value:"GOOG/SGX_N6L", caption:"IS LC BND 100US$ (N6L)" },
{ ticket:"I98", value:"GOOG/SGX_I98", caption:"IS MS INDIA 100US$ (I98)" },
{ ticket:"I19", value:"GOOG/SGX_I19", caption:"IS MSCI SIN 100US$ (I19)" },
{ ticket:"I17", value:"GOOG/SGX_I17", caption:"IS S&amp;P500 10US$ (I17)" },
{ ticket:"I07", value:"GOOG/SGX_I07", caption:"ISDN Holdings Limited (I07)" },
{ ticket:"5EC", value:"GOOG/SGX_5EC", caption:"ISR Capital Ltd (5EC)" },
{ ticket:"581", value:"GOOG/SGX_581", caption:"ITE Electric Co. (581)" },
{ ticket:"F3EU", value:"GOOG/SGX_F3EU", caption:"Indiabulls Properties Investment Trust (F3EU)" },
{ ticket:"5JS", value:"GOOG/SGX_5JS", caption:"Indofood Agri Resources Ltd. (5JS)" },
{ ticket:"5CS", value:"GOOG/SGX_5CS", caption:"Infinio Group Ltd (5CS)" },
{ ticket:"I03", value:"GOOG/SGX_I03", caption:"Informatics Education Ltd (I03)" },
{ ticket:"M14", value:"GOOG/SGX_M14", caption:"InnoTek Limited (M14)" },
{ ticket:"I26", value:"GOOG/SGX_I26", caption:"Innopac Holdings Ltd (I26)" },
{ ticket:"591", value:"GOOG/SGX_591", caption:"Innovalues Limited (591)" },
{ ticket:"5WA", value:"GOOG/SGX_5WA", caption:"International Healthway Corporation Ltd (5WA)" },
{ ticket:"571", value:"GOOG/SGX_571", caption:"International Press Softcom Limited (571)" },
{ ticket:"N6H", value:"GOOG/SGX_N6H", caption:"Internet Technology Group Ltd. (N6H)" },
{ ticket:"5GI", value:"GOOG/SGX_5GI", caption:"Interra Resources Limited (5GI)" },
{ ticket:"I06", value:"GOOG/SGX_I06", caption:"Intraco Limited (I06)" },
{ ticket:"I11", value:"GOOG/SGX_I11", caption:"Ipco International Limited (I11)" },
{ ticket:"I15", value:"GOOG/SGX_I15", caption:"Isetan (Singapore) Limited (I15)" },
{ ticket:"5WF", value:"GOOG/SGX_5WF", caption:"Isoteam Ltd (5WF)" },
{ ticket:"Q0W", value:"GOOG/SGX_Q0W", caption:"JB Foods Ltd (Q0W)" },
{ ticket:"5FA", value:"GOOG/SGX_5FA", caption:"JEP Holdings Limited (5FA)" },
{ ticket:"EG0", value:"GOOG/SGX_EG0", caption:"JES International Holdings Limited (EG0)" },
{ ticket:"5TS", value:"GOOG/SGX_5TS", caption:"JK Tech Holdings Ltd (5TS)" },
{ ticket:"J11", value:"GOOG/SGX_J11", caption:"Jacks International Limited (J11)" },
{ ticket:"J17", value:"GOOG/SGX_J17", caption:"Jackspeed Corporation Limited (J17)" },
{ ticket:"J03", value:"GOOG/SGX_J03", caption:"Jadason Enterprises Limited (J03)" },
{ ticket:"5OI", value:"GOOG/SGX_5OI", caption:"Japan Foods Holding Ltd (5OI)" },
{ ticket:"C07", value:"GOOG/SGX_C07", caption:"Jardine Cycle &amp; Carriage Limited (C07)" },
{ ticket:"J36", value:"GOOG/SGX_J36", caption:"Jardine Matheson Holdings Limited (J36)" },
{ ticket:"J37", value:"GOOG/SGX_J37", caption:"Jardine Strategic Holdings Limited (J37)" },
{ ticket:"5UU", value:"GOOG/SGX_5UU", caption:"Jason Holdings Ltd (5UU)" },
{ ticket:"5PF", value:"GOOG/SGX_5PF", caption:"Jason Marine Group Limited (5PF)" },
{ ticket:"FQ7", value:"GOOG/SGX_FQ7", caption:"Jasper Investments Limited (FQ7)" },
{ ticket:"J10", value:"GOOG/SGX_J10", caption:"Jaya Holdings Limited (J10)" },
{ ticket:"C8R", value:"GOOG/SGX_C8R", caption:"Jiutian Chemical Group Limited (C8R)" },
{ ticket:"E9L", value:"GOOG/SGX_E9L", caption:"Joyas International Holdings Limited (E9L)" },
{ ticket:"5OS", value:"GOOG/SGX_5OS", caption:"Jubilee Industries Holdings Ltd (5OS)" },
{ ticket:"5TF", value:"GOOG/SGX_5TF", caption:"Junma Tyre Cord Company Limited (5TF)" },
{ ticket:"LH4U", value:"GOOG/SGX_LH4U", caption:"K-Green Trust (LH4U)" },
{ ticket:"K01", value:"GOOG/SGX_K01", caption:"K1 Ventures (K01)" },
{ ticket:"504", value:"GOOG/SGX_504", caption:"KLW Holdings Limited (504)" },
{ ticket:"5VC", value:"GOOG/SGX_5VC", caption:"KORI Holdings Ltd (5VC)" },
{ ticket:"578", value:"GOOG/SGX_578", caption:"KS Energy Services Limited (578)" },
{ ticket:"ER0", value:"GOOG/SGX_ER0", caption:"KSH Holdings Limited (ER0)" },
{ ticket:"EB7", value:"GOOG/SGX_EB7", caption:"KTL Global Limited (EB7)" },
{ ticket:"K29", value:"GOOG/SGX_K29", caption:"Karin Technology Holdings Ltd. (K29)" },
{ ticket:"F9M", value:"GOOG/SGX_F9M", caption:"Kencana Agri Ltd (F9M)" },
{ ticket:"5TT", value:"GOOG/SGX_5TT", caption:"Keong Hong Holdings Ltd (5TT)" },
{ ticket:"BN4", value:"GOOG/SGX_BN4", caption:"Keppel Corporation Limited (BN4)" },
{ ticket:"K17", value:"GOOG/SGX_K17", caption:"Keppel Land Ltd (K17)" },
{ ticket:"K71U", value:"GOOG/SGX_K71U", caption:"Keppel REIT (K71U)" },
{ ticket:"K11", value:"GOOG/SGX_K11", caption:"Keppel Telecom. &amp; Transport. Ltd. (K11)" },
{ ticket:"K03", value:"GOOG/SGX_K03", caption:"Khong Guan Flour Milling Limited (K03)" },
{ ticket:"K04", value:"GOOG/SGX_K04", caption:"Kian Ann Engineering Ltd (K04)" },
{ ticket:"K22", value:"GOOG/SGX_K22", caption:"Kian Ho Bearings Ltd (K22)" },
{ ticket:"5JT", value:"GOOG/SGX_5JT", caption:"Kinergy Limited (5JT)" },
{ ticket:"554", value:"GOOG/SGX_554", caption:"King Wan Corp. Ltd. (554)" },
{ ticket:"K14", value:"GOOG/SGX_K14", caption:"Kingboard Copper Foil Holdings Limited (K14)" },
{ ticket:"5MZ", value:"GOOG/SGX_5MZ", caption:"Kingsmen Creatives Ltd. (5MZ)" },
{ ticket:"5TI", value:"GOOG/SGX_5TI", caption:"Kitchen Culture Holdings Ltd (5TI)" },
{ ticket:"5BK", value:"GOOG/SGX_5BK", caption:"Koda Ltd. (5BK)" },
{ ticket:"K75", value:"GOOG/SGX_K75", caption:"Koh Brothers Group Limited (K75)" },
{ ticket:"5DL", value:"GOOG/SGX_5DL", caption:"Koon (5DL)" },
{ ticket:"5OC", value:"GOOG/SGX_5OC", caption:"Koyo International Ltd (5OC)" },
{ ticket:"5RK", value:"GOOG/SGX_5RK", caption:"Kreuz Holdings Ltd (5RK)" },
{ ticket:"SK3", value:"GOOG/SGX_SK3", caption:"KrisEnergy Holdings Ltd (SK3)" },
{ ticket:"L22", value:"GOOG/SGX_L22", caption:"LANKom Electronics Limited (L22)" },
{ ticket:"L38", value:"GOOG/SGX_L38", caption:"LCD Global Investments Ltd (L38)" },
{ ticket:"C4P", value:"GOOG/SGX_C4P", caption:"LH Group Ltd (C4P)" },
{ ticket:"L10", value:"GOOG/SGX_L10", caption:"LHT Holdings Limited (L10)" },
{ ticket:"G1K", value:"GOOG/SGX_G1K", caption:"LYXOR Asia EX 10US$ (G1K)" },
{ ticket:"L05", value:"GOOG/SGX_L05", caption:"Lafe Corporation Limited (L05)" },
{ ticket:"Q7W", value:"GOOG/SGX_Q7W", caption:"Lantrovision S Ltd (Q7W)" },
{ ticket:"5EL", value:"GOOG/SGX_5EL", caption:"Lasseters International Holdings Ltd. (5EL)" },
{ ticket:"5OY", value:"GOOG/SGX_5OY", caption:"Latitude Tree International Group Ltd (5OY)" },
{ ticket:"LS9", value:"GOOG/SGX_LS9", caption:"Leader Environmental Technologies Ltd (LS9)" },
{ ticket:"L25", value:"GOOG/SGX_L25", caption:"Lee Kim Tah Holdings Ltd (L25)" },
{ ticket:"593", value:"GOOG/SGX_593", caption:"Lee Metal Group Ltd (593)" },
{ ticket:"587", value:"GOOG/SGX_587", caption:"Lereno Bio-Chem Ltd. (587)" },
{ ticket:"Q0X", value:"GOOG/SGX_Q0X", caption:"Ley Choon Group Holdings Ltd (Q0X)" },
{ ticket:"E9A", value:"GOOG/SGX_E9A", caption:"Li Heng Chemical Fibre Technologies Ltd (E9A)" },
{ ticket:"L03", value:"GOOG/SGX_L03", caption:"Lian Beng Group Ltd (L03)" },
{ ticket:"5TR", value:"GOOG/SGX_5TR", caption:"Libra Group Ltd (5TR)" },
{ ticket:"L20", value:"GOOG/SGX_L20", caption:"LifeBrandz Ltd (L20)" },
{ ticket:"5FW", value:"GOOG/SGX_5FW", caption:"Linair Technologies Limited (5FW)" },
{ ticket:"L15", value:"GOOG/SGX_L15", caption:"Lindeteves-Jacoberg Limited (L15)" },
{ ticket:"L08", value:"GOOG/SGX_L08", caption:"Lion Asiapac Limited (L08)" },
{ ticket:"L17", value:"GOOG/SGX_L17", caption:"Lion Teck Chiang Limited (L17)" },
{ ticket:"A78", value:"GOOG/SGX_A78", caption:"LionGold Corp Ltd (A78)" },
{ ticket:"D5IU", value:"GOOG/SGX_D5IU", caption:"Lippo Malls Indonesia Retail Trust (D5IU)" },
{ ticket:"E94", value:"GOOG/SGX_E94", caption:"Lizhong Wheel Group Limited (E94)" },
{ ticket:"5VI", value:"GOOG/SGX_5VI", caption:"Logistics Holdings Ltd (5VI)" },
{ ticket:"L28", value:"GOOG/SGX_L28", caption:"Longcheer Holdings Ltd (L28)" },
{ ticket:"5IE", value:"GOOG/SGX_5IE", caption:"Lorenzo International Limited (5IE)" },
{ ticket:"M22", value:"GOOG/SGX_M22", caption:"LottVision Ltd. (M22)" },
{ ticket:"F1E", value:"GOOG/SGX_F1E", caption:"Low Keng Huat (Singapore) Ltd (F1E)" },
{ ticket:"594", value:"GOOG/SGX_594", caption:"Loyz Energy Ltd (594)" },
{ ticket:"L19", value:"GOOG/SGX_L19", caption:"Lum Chang Holdings Limited (L19)" },
{ ticket:"L09", value:"GOOG/SGX_L09", caption:"LungKee BMU (L09)" },
{ ticket:"L34", value:"GOOG/SGX_L34", caption:"Luxking Group Holdings Limited (L34)" },
{ ticket:"L46", value:"GOOG/SGX_L46", caption:"Luzhou Bio-chem Technology Limited (L46)" },
{ ticket:"P60", value:"GOOG/SGX_P60", caption:"Lyxor Asia 10US$ (P60)" },
{ ticket:"NF6", value:"GOOG/SGX_NF6", caption:"Lyxor AsiaCS 10US$ (NF6)" },
{ ticket:"NF5", value:"GOOG/SGX_NF5", caption:"Lyxor AsiaFN 10US$ (NF5)" },
{ ticket:"NF3", value:"GOOG/SGX_NF3", caption:"Lyxor AsiaIF 10US$ (NF3)" },
{ ticket:"NF4", value:"GOOG/SGX_NF4", caption:"Lyxor AsiaIT 10US$ (NF4)" },
{ ticket:"NF7", value:"GOOG/SGX_NF7", caption:"Lyxor AsiaMT 10US$ (NF7)" },
{ ticket:"MT7", value:"GOOG/SGX_MT7", caption:"Lyxor AsiaRE 10US$ (MT7)" },
{ ticket:"G1O", value:"GOOG/SGX_G1O", caption:"Lyxor CRBxEny10US$ (G1O)" },
{ ticket:"P58", value:"GOOG/SGX_P58", caption:"Lyxor ChinaH 10US$ (P58)" },
{ ticket:"A0W", value:"GOOG/SGX_A0W", caption:"Lyxor Cmdty 10US$ (A0W)" },
{ ticket:"H1N", value:"GOOG/SGX_H1N", caption:"Lyxor EM Mkt 10US$ (H1N)" },
{ ticket:"H1M", value:"GOOG/SGX_H1M", caption:"Lyxor EastEur10US$ (H1M)" },
{ ticket:"JC5", value:"GOOG/SGX_JC5", caption:"Lyxor Europe 10US$ (JC5)" },
{ ticket:"A9B", value:"GOOG/SGX_A9B", caption:"Lyxor HSI 10US$ (A9B)" },
{ ticket:"P2Q", value:"GOOG/SGX_P2Q", caption:"Lyxor Indonesia10US$ (P2Q)" },
{ ticket:"CW4", value:"GOOG/SGX_CW4", caption:"Lyxor Japan 10US$ (CW4)" },
{ ticket:"AO9", value:"GOOG/SGX_AO9", caption:"Lyxor Korea 10US$ (AO9)" },
{ ticket:"H1O", value:"GOOG/SGX_H1O", caption:"Lyxor LATAM 10US$ (H1O)" },
{ ticket:"G1M", value:"GOOG/SGX_G1M", caption:"Lyxor MAL 10US$ (G1M)" },
{ ticket:"G1N", value:"GOOG/SGX_G1N", caption:"Lyxor MSIndia10US$ (G1N)" },
{ ticket:"H1Q", value:"GOOG/SGX_H1Q", caption:"Lyxor Nasdaq 10US$ (H1Q)" },
{ ticket:"JC7", value:"GOOG/SGX_JC7", caption:"Lyxor Russia 10US$ (JC7)" },
{ ticket:"A9A", value:"GOOG/SGX_A9A", caption:"Lyxor Taiwan 10US$ (A9A)" },
{ ticket:"P2P", value:"GOOG/SGX_P2P", caption:"Lyxor ThaiSET 10US$ (P2P)" },
{ ticket:"JC6", value:"GOOG/SGX_JC6", caption:"Lyxor USDJIA 10US$ (JC6)" },
{ ticket:"H1P", value:"GOOG/SGX_H1P", caption:"Lyxor World 10US$ (H1P)" },
{ ticket:"N14", value:"GOOG/SGX_N14", caption:"M Development Ltd (N14)" },
{ ticket:"B2F", value:"GOOG/SGX_B2F", caption:"M1 Ltd (B2F)" },
{ ticket:"5BM", value:"GOOG/SGX_5BM", caption:"MFS Technology Ltd (5BM)" },
{ ticket:"NC9", value:"GOOG/SGX_NC9", caption:"MSC 100 (NC9)" },
{ ticket:"M05", value:"GOOG/SGX_M05", caption:"MTQ Corporation Limited (M05)" },
{ ticket:"F86", value:"GOOG/SGX_F86", caption:"MYP Ltd (F86)" },
{ ticket:"A0P", value:"GOOG/SGX_A0P", caption:"MacCookPSF (A0P)" },
{ ticket:"M41", value:"GOOG/SGX_M41", caption:"Macquarie Int. Infrastructure Fund Ltd. (M41)" },
{ ticket:"576", value:"GOOG/SGX_576", caption:"Magnus Energy Group Ltd. (576)" },
{ ticket:"5TH", value:"GOOG/SGX_5TH", caption:"Malacca Trust Ltd (5TH)" },
{ ticket:"M04", value:"GOOG/SGX_M04", caption:"Mandarin Oriental International Limited (M04)" },
{ ticket:"L02", value:"GOOG/SGX_L02", caption:"Manhattan Resources Limited (L02)" },
{ ticket:"5QR", value:"GOOG/SGX_5QR", caption:"Mann Seng Metal International Limited (5QR)" },
{ ticket:"M11", value:"GOOG/SGX_M11", caption:"Manufacturing Integration Technology Ltd (M11)" },
{ ticket:"N2IU", value:"GOOG/SGX_N2IU", caption:"Mapletree Commercial Trust (N2IU)" },
{ ticket:"RW0U", value:"GOOG/SGX_RW0U", caption:"Mapletree Greater China Commercial Trust (RW0U)" },
{ ticket:"ME8U", value:"GOOG/SGX_ME8U", caption:"Mapletree Industrial Trust (ME8U)" },
{ ticket:"M44U", value:"GOOG/SGX_M44U", caption:"Mapletree Logistics Trust (M44U)" },
{ ticket:"5LY", value:"GOOG/SGX_5LY", caption:"Marco Polo Marine Ltd (5LY)" },
{ ticket:"5OX", value:"GOOG/SGX_5OX", caption:"Mary Chia Holdings Ltd (5OX)" },
{ ticket:"M15", value:"GOOG/SGX_M15", caption:"Matex International Limited (M15)" },
{ ticket:"5UF", value:"GOOG/SGX_5UF", caption:"Maxi-Cash Financial Services Corp Ltd (5UF)" },
{ ticket:"5FF", value:"GOOG/SGX_5FF", caption:"Medi-Flex Limited (5FF)" },
{ ticket:"546", value:"GOOG/SGX_546", caption:"Medtecs International Corporation Ltd (546)" },
{ ticket:"5DS", value:"GOOG/SGX_5DS", caption:"Megachem Limited (5DS)" },
{ ticket:"M30", value:"GOOG/SGX_M30", caption:"Meghmani Organics Ltd. (M30)" },
{ ticket:"5MS", value:"GOOG/SGX_5MS", caption:"Memstar Technology Ltd. (5MS)" },
{ ticket:"M26", value:"GOOG/SGX_M26", caption:"Memtech International Ltd (M26)" },
{ ticket:"5NF", value:"GOOG/SGX_5NF", caption:"Mencast Holdings Ltd. (5NF)" },
{ ticket:"EE6", value:"GOOG/SGX_EE6", caption:"Mercator Lines (Singapore) Ltd (EE6)" },
{ ticket:"DU4", value:"GOOG/SGX_DU4", caption:"Mermaid Maritime Public Company Limited (DU4)" },
{ ticket:"5DX", value:"GOOG/SGX_5DX", caption:"Metal Component Engineering Limited (5DX)" },
{ ticket:"5HV", value:"GOOG/SGX_5HV", caption:"Metax Engineering Corporation Limited (5HV)" },
{ ticket:"QG1", value:"GOOG/SGX_QG1", caption:"Metech International Ltd (QG1)" },
{ ticket:"M01", value:"GOOG/SGX_M01", caption:"Metro Holdings Limited (M01)" },
{ ticket:"MV4", value:"GOOG/SGX_MV4", caption:"Mewah International Inc (MV4)" },
{ ticket:"5DD", value:"GOOG/SGX_5DD", caption:"Micro-Mechanics (Holdings) Ltd (5DD)" },
{ ticket:"5EN", value:"GOOG/SGX_5EN", caption:"Midas Holdings Ltd (5EN)" },
{ ticket:"C68", value:"GOOG/SGX_C68", caption:"Mirach Energy Limited (C68)" },
{ ticket:"M03", value:"GOOG/SGX_M03", caption:"Miyoshi Precision Limited (M03)" },
{ ticket:"5WJ", value:"GOOG/SGX_5WJ", caption:"Moneymax Financial Services Ltd (5WJ)" },
{ ticket:"5BT", value:"GOOG/SGX_5BT", caption:"Moya Asia Ltd (5BT)" },
{ ticket:"M06", value:"GOOG/SGX_M06", caption:"Multi-Chem Ltd (M06)" },
{ ticket:"MF6", value:"GOOG/SGX_MF6", caption:"Mun Siong Engineering Ltd (MF6)" },
{ ticket:"5AC", value:"GOOG/SGX_5AC", caption:"NH Ceramics Ltd. (5AC)" },
{ ticket:"N02", value:"GOOG/SGX_N02", caption:"NSL Ltd (N02)" },
{ ticket:"N4E", value:"GOOG/SGX_N4E", caption:"Nam Cheong Ltd (N4E)" },
{ ticket:"G0I", value:"GOOG/SGX_G0I", caption:"Nam Lee Pressed Metal Industries Limited (G0I)" },
{ ticket:"5IF", value:"GOOG/SGX_5IF", caption:"Natural Cool Holdings Limited (5IF)" },
{ ticket:"5UJ", value:"GOOG/SGX_5UJ", caption:"Neo Group Ltd (5UJ)" },
{ ticket:"N03", value:"GOOG/SGX_N03", caption:"Neptune Orient Lines Ltd. (N03)" },
{ ticket:"N01", value:"GOOG/SGX_N01", caption:"Nera Telecommunications Ltd. (N01)" },
{ ticket:"5QY", value:"GOOG/SGX_5QY", caption:"Net Pacific Financial Holdings Ltd (5QY)" },
{ ticket:"N08", value:"GOOG/SGX_N08", caption:"New Toyo International Holdings Ltd (N08)" },
{ ticket:"5FX", value:"GOOG/SGX_5FX", caption:"New Wave Holdings Ltd. (5FX)" },
{ ticket:"B07", value:"GOOG/SGX_B07", caption:"Next Generation Satellite Communications (B07)" },
{ ticket:"5GF", value:"GOOG/SGX_5GF", caption:"Nico Steel Holdings Limited (5GF)" },
{ ticket:"G3B", value:"GOOG/SGX_G3B", caption:"Nikko AM STI ETF100 (G3B)" },
{ ticket:"N32", value:"GOOG/SGX_N32", caption:"Nippecraft Limited (N32)" },
{ ticket:"547", value:"GOOG/SGX_547", caption:"Nobel Design Holdings Ltd (547)" },
{ ticket:"N21", value:"GOOG/SGX_N21", caption:"Noble Group Limited (N21)" },
{ ticket:"543", value:"GOOG/SGX_543", caption:"Noel Gifts International Limited (543)" },
{ ticket:"MR7", value:"GOOG/SGX_MR7", caption:"Nordic Group Ltd (MR7)" },
{ ticket:"MR8", value:"GOOG/SGX_MR8", caption:"Novo Group Limited (MR8)" },
{ ticket:"5HC", value:"GOOG/SGX_5HC", caption:"Ntegrator International LTD (5HC)" },
{ ticket:"O15", value:"GOOG/SGX_O15", caption:"OCBC Bk 4.2%NCPS (O15)" },
{ ticket:"O16", value:"GOOG/SGX_O16", caption:"OCBC Bk 4.5%NCPS 100 (O16)" },
{ ticket:"F4B", value:"GOOG/SGX_F4B", caption:"OCBC Bk 5.1%NCPS 100 (F4B)" },
{ ticket:"O31", value:"GOOG/SGX_O31", caption:"OCC 3.93% NCPS 10 (O31)" },
{ ticket:"GG0", value:"GOOG/SGX_GG0", caption:"OCC 5.1% NCPS 100 (GG0)" },
{ ticket:"584", value:"GOOG/SGX_584", caption:"OEL Holdings Ltd (584)" },
{ ticket:"S3N", value:"GOOG/SGX_S3N", caption:"OKH Global Ltd (S3N)" },
{ ticket:"5CF", value:"GOOG/SGX_5CF", caption:"OKP Holdings Ltd (5CF)" },
{ ticket:"O23", value:"GOOG/SGX_O23", caption:"OSIM International Ltd. (O23)" },
{ ticket:"SK7", value:"GOOG/SGX_SK7", caption:"OUE Hospitality Trust (SK7)" },
{ ticket:"LJ3", value:"GOOG/SGX_LJ3", caption:"OUE Ltd (LJ3)" },
{ ticket:"O05", value:"GOOG/SGX_O05", caption:"Ocean Sky International Ltd. (O05)" },
{ ticket:"579", value:"GOOG/SGX_579", caption:"Oceanus Group Limited (579)" },
{ ticket:"O32", value:"GOOG/SGX_O32", caption:"Olam International Ltd (O32)" },
{ ticket:"5ML", value:"GOOG/SGX_5ML", caption:"Old Chang Kee Ltd (5ML)" },
{ ticket:"O57", value:"GOOG/SGX_O57", caption:"OmegaNav 50 (O57)" },
{ ticket:"5HG", value:"GOOG/SGX_5HG", caption:"Oniontech Limited (5HG)" },
{ ticket:"5FI", value:"GOOG/SGX_5FI", caption:"Oriental Group Ltd (5FI)" },
{ ticket:"O08", value:"GOOG/SGX_O08", caption:"Ossia International Ltd (O08)" },
{ ticket:"G4F", value:"GOOG/SGX_G4F", caption:"Otto Marine Ltd (G4F)" },
{ ticket:"AJ2", value:"GOOG/SGX_AJ2", caption:"Ouhua Energy Holdings Limited (AJ2)" },
{ ticket:"O39", value:"GOOG/SGX_O39", caption:"Oversea-Chinese Banking Corp. Limited (O39)" },
{ ticket:"RQ1", value:"GOOG/SGX_RQ1", caption:"Overseas Education Ltd (RQ1)" },
{ ticket:"5UX", value:"GOOG/SGX_5UX", caption:"Oxley Holdings Ltd (5UX)" },
{ ticket:"5UV", value:"GOOG/SGX_5UV", caption:"P99 Holdings Ltd (5UV)" },
{ ticket:"P06", value:"GOOG/SGX_P06", caption:"PCA Technology Ltd (P06)" },
{ ticket:"P19", value:"GOOG/SGX_P19", caption:"PCI Limited (P19)" },
{ ticket:"IX2", value:"GOOG/SGX_IX2", caption:"PEC Ltd. (IX2)" },
{ ticket:"P07", value:"GOOG/SGX_P07", caption:"PNE Industries Ltd (P07)" },
{ ticket:"5BS", value:"GOOG/SGX_5BS", caption:"PNE Micron Holdings Ltd. (5BS)" },
{ ticket:"K6S", value:"GOOG/SGX_K6S", caption:"PRU 500US$ (K6S)" },
{ ticket:"5WD", value:"GOOG/SGX_5WD", caption:"PS Group Holdings Ltd (5WD)" },
{ ticket:"L6T", value:"GOOG/SGX_L6T", caption:"PSL Holdings Limited (L6T)" },
{ ticket:"P11", value:"GOOG/SGX_P11", caption:"Pacific Andes Resources Development Ltd (P11)" },
{ ticket:"P15", value:"GOOG/SGX_P15", caption:"Pacific Century Regional Developments (P15)" },
{ ticket:"P47", value:"GOOG/SGX_P47", caption:"Pacific Healthcare Holdings Ltd. (P47)" },
{ ticket:"T8V", value:"GOOG/SGX_T8V", caption:"Pacific Radiance Ltd (T8V)" },
{ ticket:"5EW", value:"GOOG/SGX_5EW", caption:"Pan Asian Holdings Ltd (5EW)" },
{ ticket:"P36", value:"GOOG/SGX_P36", caption:"Pan Hong Property Group Limited (P36)" },
{ ticket:"H49", value:"GOOG/SGX_H49", caption:"Pan Pacific Hotels Group Ltd (H49)" },
{ ticket:"P52", value:"GOOG/SGX_P52", caption:"Pan-United Corporation Ltd (P52)" },
{ ticket:"O9E", value:"GOOG/SGX_O9E", caption:"Parkson Retail Asia Pte Ltd (O9E)" },
{ ticket:"C2PU", value:"GOOG/SGX_C2PU", caption:"Parkway Life REIT (C2PU)" },
{ ticket:"P13", value:"GOOG/SGX_P13", caption:"Penguin International Limited (P13)" },
{ ticket:"P05", value:"GOOG/SGX_P05", caption:"People's Food Holdings Limited (P05)" },
{ ticket:"N9LU", value:"GOOG/SGX_N9LU", caption:"Perennial China Retail Trust (N9LU)" },
{ ticket:"P34", value:"GOOG/SGX_P34", caption:"Petra Foods Limited (P34)" },
{ ticket:"P31", value:"GOOG/SGX_P31", caption:"Pharmesis International Ltd. (P31)" },
{ ticket:"P82", value:"GOOG/SGX_P82", caption:"Plastoform Holdings Ltd (P82)" },
{ ticket:"5PI", value:"GOOG/SGX_5PI", caption:"Plato Capital Ltd (5PI)" },
{ ticket:"P01", value:"GOOG/SGX_P01", caption:"Poh Tiong Choon Logistics Ltd. (P01)" },
{ ticket:"5BI", value:"GOOG/SGX_5BI", caption:"Polaris Ltd (5BI)" },
{ ticket:"5AE", value:"GOOG/SGX_5AE", caption:"Pollux Properties Limited (5AE)" },
{ ticket:"P29", value:"GOOG/SGX_P29", caption:"Popular Holdings Ltd. (P29)" },
{ ticket:"P12", value:"GOOG/SGX_P12", caption:"Powermatic Data Systems Ltd. (P12)" },
{ ticket:"583", value:"GOOG/SGX_583", caption:"Progen Holdings Limited (583)" },
{ ticket:"J74", value:"GOOG/SGX_J74", caption:"Pteris Global Ltd (J74)" },
{ ticket:"QC7", value:"GOOG/SGX_QC7", caption:"Q &amp; M Dental Group (Singapore) Limited (QC7)" },
{ ticket:"Q01", value:"GOOG/SGX_Q01", caption:"QAF Limited (Q01)" },
{ ticket:"KT9", value:"GOOG/SGX_KT9", caption:"QINGMEI GROUP HOLDINGS LIMITED (KT9)" },
{ ticket:"552", value:"GOOG/SGX_552", caption:"Qian Hu Corporation Limited (552)" },
{ ticket:"CL7", value:"GOOG/SGX_CL7", caption:"R H Energy Limited (CL7)" },
{ ticket:"T13", value:"GOOG/SGX_T13", caption:"RH PetroGas Limited (T13)" },
{ ticket:"NR7", value:"GOOG/SGX_NR7", caption:"Raffles Education Corp Ltd (NR7)" },
{ ticket:"R01", value:"GOOG/SGX_R01", caption:"Raffles Medical Group Ltd. (R01)" },
{ ticket:"R14", value:"GOOG/SGX_R14", caption:"Ramba Energy Ltd (R14)" },
{ ticket:"RF1U", value:"GOOG/SGX_RF1U", caption:"Religare Health Trust (RF1U)" },
{ ticket:"5DW", value:"GOOG/SGX_5DW", caption:"Renewable Energy Asia Group Ltd (5DW)" },
{ ticket:"5WH", value:"GOOG/SGX_5WH", caption:"Rex International Holding Ltd (5WH)" },
{ ticket:"B1ZU", value:"GOOG/SGX_B1ZU", caption:"Rickmers Maritime (B1ZU)" },
{ ticket:"AP4", value:"GOOG/SGX_AP4", caption:"Riverstone Holdings Limited (AP4)" },
{ ticket:"5LU", value:"GOOG/SGX_5LU", caption:"Rokko Holdings Ltd (5LU)" },
{ ticket:"R07", value:"GOOG/SGX_R07", caption:"Rotary Engineering Limited (R07)" },
{ ticket:"A50", value:"GOOG/SGX_A50", caption:"Rowsley Limited (A50)" },
{ ticket:"E8Z", value:"GOOG/SGX_E8Z", caption:"Roxy-Pacific Holdings Ltd (E8Z)" },
{ ticket:"J8O", value:"GOOG/SGX_J8O", caption:"Ryobi Kiso Holdings Ltd. (J8O)" },
{ ticket:"M09", value:"GOOG/SGX_M09", caption:"S i2i Ltd (M09)" },
{ ticket:"5PL", value:"GOOG/SGX_5PL", caption:"SBI Offshore Limited (5PL)" },
{ ticket:"S61", value:"GOOG/SGX_S61", caption:"SBS Transit Ltd. (S61)" },
{ ticket:"D2S", value:"GOOG/SGX_D2S", caption:"SC Global Developments Pte Ltd (D2S)" },
{ ticket:"S45U", value:"GOOG/SGX_S45U", caption:"SI Fund (S45U)" },
{ ticket:"S59", value:"GOOG/SGX_S59", caption:"SIA Engineering Company Limited (S59)" },
{ ticket:"5GB", value:"GOOG/SGX_5GB", caption:"SIIC Environment Hldg Ltd (5GB)" },
{ ticket:"S53", value:"GOOG/SGX_S53", caption:"SMRT Corporation Ltd. (S53)" },
{ ticket:"X04", value:"GOOG/SGX_X04", caption:"SP AusNet (SNG) (X04)" },
{ ticket:"S13", value:"GOOG/SGX_S13", caption:"SP Corporation Limited (S13)" },
{ ticket:"D07", value:"GOOG/SGX_D07", caption:"SPDR DJIA 10US$ (D07)" },
{ ticket:"S27", value:"GOOG/SGX_S27", caption:"SPDR S&amp;P500 10US$ (S27)" },
{ ticket:"SK6U", value:"GOOG/SGX_SK6U", caption:"SPH REIT (SK6U)" },
{ ticket:"X64", value:"GOOG/SGX_X64", caption:"STAR Pharmaceutical Limited (X64)" },
{ ticket:"S24", value:"GOOG/SGX_S24", caption:"STATS ChipPAC Ltd. (S24)" },
{ ticket:"ES3", value:"GOOG/SGX_ES3", caption:"STI ETF (ES3)" },
{ ticket:"GZ9", value:"GOOG/SGX_GZ9", caption:"STX Pan Ocean Co Ltd. (GZ9)" },
{ ticket:"M1GU", value:"GOOG/SGX_M1GU", caption:"Sabana Shariah Compliant REIT (M1GU)" },
{ ticket:"T8KU", value:"GOOG/SGX_T8KU", caption:"Saizen REIT 100 (T8KU)" },
{ ticket:"T8JU", value:"GOOG/SGX_T8JU", caption:"Saizen Real Estate Investment Trust (T8JU)" },
{ ticket:"5DO", value:"GOOG/SGX_5DO", caption:"Sakae Holdings Ltd (5DO)" },
{ ticket:"E6R", value:"GOOG/SGX_E6R", caption:"Samko Timber Limited (E6R)" },
{ ticket:"S56", value:"GOOG/SGX_S56", caption:"Samudera Shipping Line Ltd. (S56)" },
{ ticket:"S46", value:"GOOG/SGX_S46", caption:"San Teh Ltd. (S46)" },
{ ticket:"580", value:"GOOG/SGX_580", caption:"Santak Holdings Limited (580)" },
{ ticket:"NF1", value:"GOOG/SGX_NF1", caption:"Sapphire Corp Limited (NF1)" },
{ ticket:"U77", value:"GOOG/SGX_U77", caption:"Sarin Technologies Ltd. (U77)" },
{ ticket:"S58", value:"GOOG/SGX_S58", caption:"Sats Ltd (S58)" },
{ ticket:"T20", value:"GOOG/SGX_T20", caption:"Scintronix Corp Ltd (T20)" },
{ ticket:"5HW", value:"GOOG/SGX_5HW", caption:"Scorpio East Holdings Ltd. (5HW)" },
{ ticket:"528", value:"GOOG/SGX_528", caption:"Second Chance Properties Ltd (528)" },
{ ticket:"566", value:"GOOG/SGX_566", caption:"See Hup Seng Limited (566)" },
{ ticket:"5FQ", value:"GOOG/SGX_5FQ", caption:"Select Group Limited (5FQ)" },
{ ticket:"U96", value:"GOOG/SGX_U96", caption:"SembCorp Industries Limited (U96)" },
{ ticket:"S51", value:"GOOG/SGX_S51", caption:"SembCorp Marine Ltd. (S51)" },
{ ticket:"S69", value:"GOOG/SGX_S69", caption:"Serial System Ltd. (S69)" },
{ ticket:"IW5", value:"GOOG/SGX_IW5", caption:"Seroja Investments Ltd (IW5)" },
{ ticket:"S07", value:"GOOG/SGX_S07", caption:"Shang Asia 2kHK$ (S07)" },
{ ticket:"T57", value:"GOOG/SGX_T57", caption:"Shanghai Asia Holdings Limited (T57)" },
{ ticket:"X27", value:"GOOG/SGX_X27", caption:"Shanghai Turbo Enterprises Ltd (X27)" },
{ ticket:"OV8", value:"GOOG/SGX_OV8", caption:"Sheng Siong Group Ltd (OV8)" },
{ ticket:"5CP", value:"GOOG/SGX_5CP", caption:"Silverlake Axis Ltd (5CP)" },
{ ticket:"S05", value:"GOOG/SGX_S05", caption:"Sim Lian Group Limited (S05)" },
{ ticket:"B7K", value:"GOOG/SGX_B7K", caption:"Sin Ghee Huat Corporation Ltd. (B7K)" },
{ ticket:"KF4", value:"GOOG/SGX_KF4", caption:"Sin Heng Heavy Machinery Ltd (KF4)" },
{ ticket:"A26", value:"GOOG/SGX_A26", caption:"Sinarmas Land Ltd (A26)" },
{ ticket:"5UN", value:"GOOG/SGX_5UN", caption:"Sincap group Ltd (5UN)" },
{ ticket:"5IC", value:"GOOG/SGX_5IC", caption:"Sing Holdings Limited (5IC)" },
{ ticket:"S35", value:"GOOG/SGX_S35", caption:"Sing Investments &amp; Finance Limited (S35)" },
{ ticket:"5CE", value:"GOOG/SGX_5CE", caption:"SingHaiyi Group Ltd (5CE)" },
{ ticket:"C6L", value:"GOOG/SGX_C6L", caption:"Singapore Airlines Ltd. (C6L)" },
{ ticket:"S68", value:"GOOG/SGX_S68", caption:"Singapore Exchange Limited (S68)" },
{ ticket:"5WG", value:"GOOG/SGX_5WG", caption:"Singapore Kitchen Equipment Ltd (5WG)" },
{ ticket:"S30", value:"GOOG/SGX_S30", caption:"Singapore Land Limited (S30)" },
{ ticket:"5OT", value:"GOOG/SGX_5OT", caption:"Singapore Medical Group Ltd (5OT)" },
{ ticket:"S08", value:"GOOG/SGX_S08", caption:"Singapore Post Limited (S08)" },
{ ticket:"T39", value:"GOOG/SGX_T39", caption:"Singapore Press Holdings Limited (T39)" },
{ ticket:"S49", value:"GOOG/SGX_S49", caption:"Singapore Reinsurance Corporation Ltd. (S49)" },
{ ticket:"S19", value:"GOOG/SGX_S19", caption:"Singapore Shipping Corporation Limited (S19)" },
{ ticket:"S63", value:"GOOG/SGX_S63", caption:"Singapore Technologies Engineering Ltd. (S63)" },
{ ticket:"Z74", value:"GOOG/SGX_Z74", caption:"Singapore Telecommunications Limited (Z74)" },
{ ticket:"Y45", value:"GOOG/SGX_Y45", caption:"Singapore Windsor Holdings Limited (Y45)" },
{ ticket:"S23", value:"GOOG/SGX_S23", caption:"Singapura Finance Limited (S23)" },
{ ticket:"5HH", value:"GOOG/SGX_5HH", caption:"Sinjia Land Ltd (5HH)" },
{ ticket:"F3V", value:"GOOG/SGX_F3V", caption:"Sino Construction Limited (F3V)" },
{ ticket:"JS5", value:"GOOG/SGX_JS5", caption:"Sino Grandness Food Industry Group Ltd (JS5)" },
{ ticket:"C9Q", value:"GOOG/SGX_C9Q", caption:"Sinostar PEC Holdings Limited (C9Q)" },
{ ticket:"D3W", value:"GOOG/SGX_D3W", caption:"Sinotel Technologies Ltd (D3W)" },
{ ticket:"5CN", value:"GOOG/SGX_5CN", caption:"Sinwa Limited (5CN)" },
{ ticket:"5LE", value:"GOOG/SGX_5LE", caption:"Sitra Holdings (International) Ltd (5LE)" },
{ ticket:"5MM", value:"GOOG/SGX_5MM", caption:"Sky One Holdings Limited (5MM)" },
{ ticket:"5RE", value:"GOOG/SGX_5RE", caption:"Smartflex Holdings Ltd. (5RE)" },
{ ticket:"SV3U", value:"GOOG/SGX_SV3U", caption:"Soilbuild Business Space REIT (SV3U)" },
{ ticket:"S7P", value:"GOOG/SGX_S7P", caption:"Soilbuild Construction Group Ltd (S7P)" },
{ ticket:"5MD", value:"GOOG/SGX_5MD", caption:"Soon Lian Holdings Limited (5MD)" },
{ ticket:"E6E", value:"GOOG/SGX_E6E", caption:"Sound Global Ltd (E6E)" },
{ ticket:"5KI", value:"GOOG/SGX_5KI", caption:"Soup Restaurant Group Limited (5KI)" },
{ ticket:"T77", value:"GOOG/SGX_T77", caption:"Southern Packaging Group Limited (T77)" },
{ ticket:"564", value:"GOOG/SGX_564", caption:"Spindex Industries Limited (564)" },
{ ticket:"NC2", value:"GOOG/SGX_NC2", caption:"Sri Trang Agro-Industry PCL (NC2)" },
{ ticket:"5NH", value:"GOOG/SGX_5NH", caption:"St. James Holdings Limited (5NH)" },
{ ticket:"H07", value:"GOOG/SGX_H07", caption:"Stamford Land Corporation Ltd. (H07)" },
{ ticket:"S29", value:"GOOG/SGX_S29", caption:"Stamford Tyres Corp Ltd (S29)" },
{ ticket:"CC3", value:"GOOG/SGX_CC3", caption:"StarHub Ltd. (CC3)" },
{ ticket:"P40U", value:"GOOG/SGX_P40U", caption:"Starhill Global Real Estate Invmt Trust (P40U)" },
{ ticket:"5UA", value:"GOOG/SGX_5UA", caption:"Starland Holdings Ltd (5UA)" },
{ ticket:"S85", value:"GOOG/SGX_S85", caption:"Straco Corporation Ltd (S85)" },
{ ticket:"S73", value:"GOOG/SGX_S73", caption:"Stratech Systems Limited (S73)" },
{ ticket:"A7S", value:"GOOG/SGX_A7S", caption:"SunVic Chemical Holdings Limited (A7S)" },
{ ticket:"5AI", value:"GOOG/SGX_5AI", caption:"Sunlight Group Hldg Ltd (5AI)" },
{ ticket:"F06", value:"GOOG/SGX_F06", caption:"Sunmoon Food Co Ltd (F06)" },
{ ticket:"T35", value:"GOOG/SGX_T35", caption:"Sunningdale Tech Ltd (T35)" },
{ ticket:"5GD", value:"GOOG/SGX_5GD", caption:"Sunpower (5GD)" },
{ ticket:"S71", value:"GOOG/SGX_S71", caption:"Sunright Limited (S71)" },
{ ticket:"CZ3", value:"GOOG/SGX_CZ3", caption:"Suntar Eco-City Ltd (CZ3)" },
{ ticket:"T82U", value:"GOOG/SGX_T82U", caption:"Suntec Real Estate Investment Trust (T82U)" },
{ ticket:"S10", value:"GOOG/SGX_S10", caption:"Super Group Ltd. (S10)" },
{ ticket:"S48", value:"GOOG/SGX_S48", caption:"Superbowl Holdings Limited (S48)" },
{ ticket:"S47", value:"GOOG/SGX_S47", caption:"Superior Multi-Packaging Limited (S47)" },
{ ticket:"Q7Q", value:"GOOG/SGX_Q7Q", caption:"Surface Mount Technology (Holdings) Ltd. (Q7Q)" },
{ ticket:"QF6", value:"GOOG/SGX_QF6", caption:"Swee Hong Ltd (QF6)" },
{ ticket:"AK3", value:"GOOG/SGX_AK3", caption:"Swiber Holdings Limited (AK3)" },
{ ticket:"O2F", value:"GOOG/SGX_O2F", caption:"Swing Media Technology Group Ltd (O2F)" },
{ ticket:"5FD", value:"GOOG/SGX_5FD", caption:"Swissco Holdings Ltd (5FD)" },
{ ticket:"Z75", value:"GOOG/SGX_Z75", caption:"Synear Food Holdings Limited (Z75)" },
{ ticket:"5UO", value:"GOOG/SGX_5UO", caption:"Sysma Holdings Ltd (5UO)" },
{ ticket:"K1Q", value:"GOOG/SGX_K1Q", caption:"T T J Holdings Ltd (K1Q)" },
{ ticket:"PA3", value:"GOOG/SGX_PA3", caption:"TA Corporation Ltd (PA3)" },
{ ticket:"M1Z", value:"GOOG/SGX_M1Z", caption:"TEE International Ltd (M1Z)" },
{ ticket:"S9B", value:"GOOG/SGX_S9B", caption:"TEE Land Ltd (S9B)" },
{ ticket:"K2P", value:"GOOG/SGX_K2P", caption:"TIONG SENG HOLDINGS LIMITED (K2P)" },
{ ticket:"586", value:"GOOG/SGX_586", caption:"TMC Education Corporation Ltd. (586)" },
{ ticket:"T18", value:"GOOG/SGX_T18", caption:"TPV Technology Ltd. (T18)" },
{ ticket:"574", value:"GOOG/SGX_574", caption:"TSH Corporation Limited (574)" },
{ ticket:"T09", value:"GOOG/SGX_T09", caption:"TT International Limited (T09)" },
{ ticket:"500", value:"GOOG/SGX_500", caption:"Tai Sin Electric Ltd (500)" },
{ ticket:"T15", value:"GOOG/SGX_T15", caption:"Tan Chong International Ltd. (T15)" },
{ ticket:"T03", value:"GOOG/SGX_T03", caption:"Tat Hong Holdings Limited (T03)" },
{ ticket:"T12", value:"GOOG/SGX_T12", caption:"Tat Seng Packaging Group Ltd. (T12)" },
{ ticket:"T43", value:"GOOG/SGX_T43", caption:"Techcomp (Holdings) Limited (T43)" },
{ ticket:"5CQ", value:"GOOG/SGX_5CQ", caption:"Technics Oil &amp; Gas Limited (5CQ)" },
{ ticket:"561", value:"GOOG/SGX_561", caption:"Teckwah Industrial Corporation Limited (561)" },
{ ticket:"5OQ", value:"GOOG/SGX_5OQ", caption:"Teho International Inc Ltd (5OQ)" },
{ ticket:"T41", value:"GOOG/SGX_T41", caption:"TeleChoice International Ltd. (T41)" },
{ ticket:"T28", value:"GOOG/SGX_T28", caption:"Teledata (Singapore) Ltd (T28)" },
{ ticket:"AI1", value:"GOOG/SGX_AI1", caption:"Texchem-Pack Holdings (S) Pte Ltd (AI1)" },
{ ticket:"Y92", value:"GOOG/SGX_Y92", caption:"Thai Beverage Public Company Limited (Y92)" },
{ ticket:"596", value:"GOOG/SGX_596", caption:"Thai Village Holdings Ltd. (596)" },
{ ticket:"T04", value:"GOOG/SGX_T04", caption:"Thakral Corporation Ltd. (T04)" },
{ ticket:"S20", value:"GOOG/SGX_S20", caption:"The Straits Trading Company Limited (S20)" },
{ ticket:"T14", value:"GOOG/SGX_T14", caption:"Tianjin Zhongxin Phrmctl Gp Cp Ltd (T14)" },
{ ticket:"J7X", value:"GOOG/SGX_J7X", caption:"Tiger Airways Holdings Limited (J7X)" },
{ ticket:"T06", value:"GOOG/SGX_T06", caption:"Tiong Woon Corp. Holdings Ltd. (T06)" },
{ ticket:"519", value:"GOOG/SGX_519", caption:"Top Global Limited (519)" },
{ ticket:"S2D", value:"GOOG/SGX_S2D", caption:"Tosei 100 (S2D)" },
{ ticket:"B2W", value:"GOOG/SGX_B2W", caption:"Total Access Communication Public Co Ltd (B2W)" },
{ ticket:"E15", value:"GOOG/SGX_E15", caption:"Transcu Group Limited (E15)" },
{ ticket:"570", value:"GOOG/SGX_570", caption:"Transit-Mixed Concrete Ltd (570)" },
{ ticket:"T55", value:"GOOG/SGX_T55", caption:"Transpac Industrial Holdings Limited (T55)" },
{ ticket:"T19", value:"GOOG/SGX_T19", caption:"Transview Holdings Ltd. (T19)" },
{ ticket:"5KH", value:"GOOG/SGX_5KH", caption:"Travelite Holdings Limited (5KH)" },
{ ticket:"5AB", value:"GOOG/SGX_5AB", caption:"Trek 2000 International Ltd. (5AB)" },
{ ticket:"5NL", value:"GOOG/SGX_5NL", caption:"Tritech Group Limited (5NL)" },
{ ticket:"RC5", value:"GOOG/SGX_RC5", caption:"Triyards Holdings Ltd (RC5)" },
{ ticket:"T26", value:"GOOG/SGX_T26", caption:"Tsit Wing International Holdings Ltd. (T26)" },
{ ticket:"T24", value:"GOOG/SGX_T24", caption:"Tuan Sing Holdings Limited (T24)" },
{ ticket:"540", value:"GOOG/SGX_540", caption:"Tung Lok Restaurants (2000) Ltd. (540)" },
{ ticket:"T08", value:"GOOG/SGX_T08", caption:"Tye Soon Ltd (T08)" },
{ ticket:"NI3", value:"GOOG/SGX_NI3", caption:"UE E&amp;C Ltd (NI3)" },
{ ticket:"JK8", value:"GOOG/SGX_JK8", caption:"UETF SSE50China100 (JK8)" },
{ ticket:"558", value:"GOOG/SGX_558", caption:"UMS Holdings Limited (558)" },
{ ticket:"U10", value:"GOOG/SGX_U10", caption:"UOB-Kay Hian Holdings Limited (U10)" },
{ ticket:"U14", value:"GOOG/SGX_U14", caption:"UOL Group Limited (U14)" },
{ ticket:"U09", value:"GOOG/SGX_U09", caption:"UPP Holdings Limited (U09)" },
{ ticket:"C3T", value:"GOOG/SGX_C3T", caption:"Uni-Asia Holdings Ltd (C3T)" },
{ ticket:"U18", value:"GOOG/SGX_U18", caption:"Unified Communications Holdings Ltd. (U18)" },
{ ticket:"V69", value:"GOOG/SGX_V69", caption:"Union Steel Hldgs Ltd. (V69)" },
{ ticket:"A6F", value:"GOOG/SGX_A6F", caption:"Unionmet (Singapore) Limited (A6F)" },
{ ticket:"U04", value:"GOOG/SGX_U04", caption:"United Engineers Limited (U04)" },
{ ticket:"U05", value:"GOOG/SGX_U05", caption:"United Engineers Limited (U05)" },
{ ticket:"U19", value:"GOOG/SGX_U19", caption:"United Envirotech Ltd (U19)" },
{ ticket:"P30", value:"GOOG/SGX_P30", caption:"United Fiber Systems Limited (P30)" },
{ ticket:"U01", value:"GOOG/SGX_U01", caption:"United Food Holdings Limited (U01)" },
{ ticket:"U06", value:"GOOG/SGX_U06", caption:"United Industrial Corporation Ltd (U06)" },
{ ticket:"U07", value:"GOOG/SGX_U07", caption:"United International Securities Limited (U07)" },
{ ticket:"GL8", value:"GOOG/SGX_GL8", caption:"United Overseas Bank Ltd (GL8)" },
{ ticket:"U11", value:"GOOG/SGX_U11", caption:"United Overseas Bank Ltd (U11)" },
{ ticket:"U13", value:"GOOG/SGX_U13", caption:"United Overseas Insurance Limited (U13)" },
{ ticket:"W81", value:"GOOG/SGX_W81", caption:"Universal Res (W81)" },
{ ticket:"EH5", value:"GOOG/SGX_EH5", caption:"UtdOAus (EH5)" },
{ ticket:"PH0", value:"GOOG/SGX_PH0", caption:"VGO Corp Ltd (PH0)" },
{ ticket:"V01", value:"GOOG/SGX_V01", caption:"VICOM Limited (V01)" },
{ ticket:"545", value:"GOOG/SGX_545", caption:"Vallianz Holdings Ltd (545)" },
{ ticket:"T6I", value:"GOOG/SGX_T6I", caption:"Valuemax Group Ltd (T6I)" },
{ ticket:"BN2", value:"GOOG/SGX_BN2", caption:"Valuetronics Holdings Limited (BN2)" },
{ ticket:"MS7", value:"GOOG/SGX_MS7", caption:"Vard Holdings Ltd (MS7)" },
{ ticket:"V03", value:"GOOG/SGX_V03", caption:"Venture Corporation Ltd. (V03)" },
{ ticket:"F01", value:"GOOG/SGX_F01", caption:"Vibrant Group Ltd (F01)" },
{ ticket:"535", value:"GOOG/SGX_535", caption:"VibroPower Corporation Limited (535)" },
{ ticket:"569", value:"GOOG/SGX_569", caption:"Vicplas International Limited (569)" },
{ ticket:"557", value:"GOOG/SGX_557", caption:"Viking Offshore And Marine Ltd (557)" },
{ ticket:"T8B", value:"GOOG/SGX_T8B", caption:"Viva Ind Tr (T8B)" },
{ ticket:"L5J", value:"GOOG/SGX_L5J", caption:"Viz Branz Limited (L5J)" },
{ ticket:"OJ4", value:"GOOG/SGX_OJ4", caption:"W Corporation Ltd (OJ4)" },
{ ticket:"W01", value:"GOOG/SGX_W01", caption:"WBL Corporation Ltd (W01)" },
{ ticket:"5RJ", value:"GOOG/SGX_5RJ", caption:"WE Holdings Ltd (5RJ)" },
{ ticket:"E3B", value:"GOOG/SGX_E3B", caption:"Wee Hur Holdings Ltd. (E3B)" },
{ ticket:"ON7", value:"GOOG/SGX_ON7", caption:"Weiye Holdings Ltd (ON7)" },
{ ticket:"5OF", value:"GOOG/SGX_5OF", caption:"Westminster Travel Ltd (5OF)" },
{ ticket:"M35", value:"GOOG/SGX_M35", caption:"Wheelock Properties (Singapore) Ltd. (M35)" },
{ ticket:"W12", value:"GOOG/SGX_W12", caption:"Willas-Array Electronics (Holdings) Ltd (W12)" },
{ ticket:"F34", value:"GOOG/SGX_F34", caption:"Wilmar International Limited (F34)" },
{ ticket:"W05", value:"GOOG/SGX_W05", caption:"Wing Tai Holdings Limited (W05)" },
{ ticket:"M9F", value:"GOOG/SGX_M9F", caption:"XMH Holdings Ltd (M9F)" },
{ ticket:"MN5", value:"GOOG/SGX_MN5", caption:"XinRen Aluminum Holdings Ltd (MN5)" },
{ ticket:"I04", value:"GOOG/SGX_I04", caption:"Xpress Holdings Ltd. (I04)" },
{ ticket:"5WR", value:"GOOG/SGX_5WR", caption:"Xyec Holdings Co Ltd (5WR)" },
{ ticket:"Y08", value:"GOOG/SGX_Y08", caption:"YHI International Ltd. (Y08)" },
{ ticket:"MC7", value:"GOOG/SGX_MC7", caption:"Yamada Green Resources Ltd (MC7)" },
{ ticket:"BS6", value:"GOOG/SGX_BS6", caption:"Yangzijiang Shipbuilding Holdings Ltd (BS6)" },
{ ticket:"Z25", value:"GOOG/SGX_Z25", caption:"Yanlord Land Group Limited (Z25)" },
{ ticket:"R4A", value:"GOOG/SGX_R4A", caption:"Yeo HS 1 (R4A)" },
{ ticket:"Y03", value:"GOOG/SGX_Y03", caption:"Yeo Hiap Seng Ltd (Y03)" },
{ ticket:"5DM", value:"GOOG/SGX_5DM", caption:"Ying Li International Real Estate Ltd. (5DM)" },
{ ticket:"Z59", value:"GOOG/SGX_Z59", caption:"Yoma Strategic Holdings Ltd. (Z59)" },
{ ticket:"E6A", value:"GOOG/SGX_E6A", caption:"Yongmao Holdings Limited (E6A)" },
{ ticket:"Y02", value:"GOOG/SGX_Y02", caption:"Yongnam Holdings Limited (Y02)" },
{ ticket:"CX5", value:"GOOG/SGX_CX5", caption:"Yongxin International Holdings Ltd. (CX5)" },
{ ticket:"Y06", value:"GOOG/SGX_Y06", caption:"Youyue International Ltd (Y06)" },
{ ticket:"G10", value:"GOOG/SGX_G10", caption:"Yuexiu Prop 2k (G10)" },
{ ticket:"D5N", value:"GOOG/SGX_D5N", caption:"Z-Obee (D5N)" },
{ ticket:"Z01", value:"GOOG/SGX_Z01", caption:"Zagro Asia Ltd (Z01)" },
{ ticket:"5SR", value:"GOOG/SGX_5SR", caption:"Zhongmin Baihui Retail Group Ltd (5SR)" },
{ ticket:"5EG", value:"GOOG/SGX_5EG", caption:"Zhongxin Fruit and Juice Ltd (5EG)" },
{ ticket:"I9T", value:"GOOG/SGX_I9T", caption:"Ziwo Holdings Ltd (I9T)" },
{ ticket:"A05", value:"GOOG/SGX_A05", caption:"a AVJennings A$ (A05)" },
{ ticket:"O02", value:"GOOG/SGX_O02", caption:"a OGL Resources A$ (O02)" },
{ ticket:"5CT", value:"GOOG/SGX_5CT", caption:"ecoWise Holdings Limited (5CT)" },
{ ticket:"5VT", value:"GOOG/SGX_5VT", caption:"euNetworks Group Ltd (5VT)" },
{ ticket:"A27", value:"GOOG/SGX_A27", caption:"mDR LIMITED (A27)" },
{ ticket:"K3HD", value:"GOOG/SGX_K3HD", caption:"u ACH ADR 10US$ (K3HD)" },
{ ticket:"K3SD", value:"GOOG/SGX_K3SD", caption:"u BIDU ADR 10US$+ (K3SD)" },
{ ticket:"K3CD", value:"GOOG/SGX_K3CD", caption:"u CEA ADR 10US$ (K3CD)" },
{ ticket:"K3ED", value:"GOOG/SGX_K3ED", caption:"u CHA ADR 10US$ (K3ED)" },
{ ticket:"K3PD", value:"GOOG/SGX_K3PD", caption:"u CHL ADR 10US$ (K3PD)" },
{ ticket:"K3ID", value:"GOOG/SGX_K3ID", caption:"u CHU ADR 10US$ (K3ID)" },
{ ticket:"K3RD", value:"GOOG/SGX_K3RD", caption:"u CTRP ADR 10US$+ (K3RD)" },
{ ticket:"K3JD", value:"GOOG/SGX_K3JD", caption:"u CYOU ADR 10US$+ (K3JD)" },
{ ticket:"N6ED", value:"GOOG/SGX_N6ED", caption:"u DCM ADR 10US$ (N6ED)" },
{ ticket:"PU6D", value:"GOOG/SGX_PU6D", caption:"u HBC ADR 10US$ (PU6D)" },
{ ticket:"K3UD", value:"GOOG/SGX_K3UD", caption:"u HMIN ADR 10US$+ (K3UD)" },
{ ticket:"K3FD", value:"GOOG/SGX_K3FD", caption:"u HNP ADR 10US$ (K3FD)" },
{ ticket:"N6DD", value:"GOOG/SGX_N6DD", caption:"u MFG ADR 10US$ (N6DD)" },
{ ticket:"N5YD", value:"GOOG/SGX_N5YD", caption:"u MTU ADR 10US$ (N5YD)" },
{ ticket:"K3MD", value:"GOOG/SGX_K3MD", caption:"u NTES ADR 10US$+ (K3MD)" },
{ ticket:"K3OD", value:"GOOG/SGX_K3OD", caption:"u PTR ADR 10US$ (K3OD)" },
{ ticket:"K3DD", value:"GOOG/SGX_K3DD", caption:"u SHI ADR 10US$ (K3DD)" },
{ ticket:"K3ND", value:"GOOG/SGX_K3ND", caption:"u STP ADR 10US$+ (K3ND)" },
{ ticket:"K3KD", value:"GOOG/SGX_K3KD", caption:"u TSL ADR 10 US$+ (K3KD)" },
{ ticket:"K3GD", value:"GOOG/SGX_K3GD", caption:"u YZC ADR 10US$ (K3GD)" },
{ ticket:"K3TD", value:"GOOG/SGX_K3TD", caption:"u ZNH ADR 10US$ (K3TD)" }
]

GoogleSingapure.getTickets = function(){
  return tickets;
}

export default GoogleSingapure
