
const GoogleLisbon = {};

const tickets = [
  { ticket:"ALNOR", value:"GOOG/ELI_ALNOR", caption:"NEXPONOR SICAFI SA (ALNOR)" },
  { ticket:"ALTR", value:"GOOG/ELI_ALTR", caption:"Altri SGPS SA (ALTR)" },
  { ticket:"BANIF", value:"GOOG/ELI_BANIF", caption:"Banif Banco Internacional do Funchal SA (BANIF)" },
  { ticket:"BCP", value:"GOOG/ELI_BCP", caption:"Banco Comercial Portugues SA (BCP)" },
  { ticket:"BES", value:"GOOG/ELI_BES", caption:"Banco Espirito Santo SA (BES)" },
  { ticket:"BNF", value:"GOOG/ELI_BNF", caption:"Banif Banco Internacional do Funchal SA (BNF)" },
  { ticket:"BPE", value:"GOOG/ELI_BPE", caption:"BANCO POP.ESPANOL (BPE)" },
  { ticket:"BPI", value:"GOOG/ELI_BPI", caption:"Banco BPI SA (BPI)" },
  { ticket:"BRI", value:"GOOG/ELI_BRI", caption:"Brisa - Auto-Estradas de Portugal SA (BRI)" },
  { ticket:"CDU", value:"GOOG/ELI_CDU", caption:"Conduril Construtora Duriense S.A. (CDU)" },
  { ticket:"CFN", value:"GOOG/ELI_CFN", caption:"Cofina SGPS SA (CFN)" },
  { ticket:"COMAE", value:"GOOG/ELI_COMAE", caption:"COMPTA Equipamentos e Servicos Inform SA (COMAE)" },
  { ticket:"COR", value:"GOOG/ELI_COR", caption:"Corticeira Amorim SGPS SA (COR)" },
  { ticket:"CPA", value:"GOOG/ELI_CPA", caption:"Copam Companhia Portuguesa de Amidos SA (CPA)" },
  { ticket:"CPN", value:"GOOG/ELI_CPN", caption:"CIPAN - Cia Ind Prom de Ant SA (CPN)" },
  { ticket:"CPR", value:"GOOG/ELI_CPR", caption:"CIMPOR - Cimentos de Portugal SGPS SA (CPR)" },
  { ticket:"CUR", value:"GOOG/ELI_CUR", caption:"Sociedade Das Aguas Da Curia SA (CUR)" },
  { ticket:"EDP", value:"GOOG/ELI_EDP", caption:"EDP - Energias de Portugal SA (EDP)" },
  { ticket:"EDPR", value:"GOOG/ELI_EDPR", caption:"EDP Renovaveis SA (EDPR)" },
  { ticket:"EGL", value:"GOOG/ELI_EGL", caption:"Mota-Engil SGPS SA (EGL)" },
  { ticket:"ESF", value:"GOOG/ELI_ESF", caption:"E.SANTO FINANCIAL (ESF)" },
  { ticket:"ESFN", value:"GOOG/ELI_ESFN", caption:"E.SANTO FIN.NOM (ESFN)" },
  { ticket:"ESO", value:"GOOG/ELI_ESO", caption:"Estoril Sol SGPS SA (ESO)" },
  { ticket:"FCP", value:"GOOG/ELI_FCP", caption:"Futebol Clube do Porto Futebol SAD (FCP)" },
  { ticket:"FEN", value:"GOOG/ELI_FEN", caption:"Fenalu - Gestao de Investimentos e P. SA (FEN)" },
  { ticket:"GALP", value:"GOOG/ELI_GALP", caption:"Galp Energia SGPS SA (GALP)" },
  { ticket:"GLINT", value:"GOOG/ELI_GLINT", caption:"Glintt Global Intelligent Technologes SA (GLINT)" },
  { ticket:"GPA", value:"GOOG/ELI_GPA", caption:"Imobiliaria Construtora Grao-Para SA (GPA)" },
  { ticket:"IBER", value:"GOOG/ELI_IBER", caption:"ESAF Iberian ETF (IBER)" },
  { ticket:"IBS", value:"GOOG/ELI_IBS", caption:"Ibersol SGPS SA (IBS)" },
  { ticket:"INA", value:"GOOG/ELI_INA", caption:"Inapa - Investimentos Particip Gestao SA (INA)" },
  { ticket:"INAP", value:"GOOG/ELI_INAP", caption:"INAPA-PREF S/ VOTO (INAP)" },
  { ticket:"IPR", value:"GOOG/ELI_IPR", caption:"Impresa SGPS SA (IPR)" },
  { ticket:"JMT", value:"GOOG/ELI_JMT", caption:"Jeronimo Martins SGPS SA (JMT)" },
  { ticket:"LIG", value:"GOOG/ELI_LIG", caption:"Lisgrafica Impressao e Artes Graficas SA (LIG)" },
  { ticket:"LIT", value:"GOOG/ELI_LIT", caption:"Litho Formas Portuguesa (LIT)" },
  { ticket:"MAR", value:"GOOG/ELI_MAR", caption:"Martifer SGPS SA (MAR)" },
  { ticket:"MCP", value:"GOOG/ELI_MCP", caption:"Grupo Media Capital SGPS SA (MCP)" },
  { ticket:"NBA", value:"GOOG/ELI_NBA", caption:"Novabase SGPS SA (NBA)" },
  { ticket:"ORE", value:"GOOG/ELI_ORE", caption:"Sociedade Comercial Orey Antunes SA (ORE)" },
  { ticket:"PP2", value:"GOOG/ELI_PP2", caption:"ComStage PSI20 LEV (PP2)" },
  { ticket:"PPP", value:"GOOG/ELI_PPP", caption:"ComStage PSI20 (PPP)" },
  { ticket:"PTC", value:"GOOG/ELI_PTC", caption:"Portugal Telecom SGPS SA (PTC)" },
  { ticket:"PTI", value:"GOOG/ELI_PTI", caption:"Portucel SA (PTI)" },
  { ticket:"RAM", value:"GOOG/ELI_RAM", caption:"F Ramada - Investimentos SGPS SA (RAM)" },
  { ticket:"RED", value:"GOOG/ELI_RED", caption:"Reditus - SGPS SA (RED)" },
  { ticket:"RENE", value:"GOOG/ELI_RENE", caption:"REN Redes Energeticas Nacionais SGPS SA (RENE)" },
  { ticket:"SANT", value:"GOOG/ELI_SANT", caption:"BANCO SANTANDER (SANT)" },
  { ticket:"SCB", value:"GOOG/ELI_SCB", caption:"Sporting Clube de Braga - Futebol SAD (SCB)" },
  { ticket:"SCOAE", value:"GOOG/ELI_SCOAE", caption:"Grupo Soares da Costa SGPS SA (SCOAE)" },
  { ticket:"SCP", value:"GOOG/ELI_SCP", caption:"Sporting Clube de Portugal Futebol SAD (SCP)" },
  { ticket:"SCT", value:"GOOG/ELI_SCT", caption:"Toyota Caetano Portugal SA (SCT)" },
  { ticket:"SEM", value:"GOOG/ELI_SEM", caption:"Semapa - Sociedade Invest Gestao SGPS SA (SEM)" },
  { ticket:"SLBEN", value:"GOOG/ELI_SLBEN", caption:"Sport Lisboa e Benfica Futebol SAD (SLBEN)" },
  { ticket:"SNC", value:"GOOG/ELI_SNC", caption:"Sonaecom (SNC)" },
  { ticket:"SNG", value:"GOOG/ELI_SNG", caption:"Sonagi SGPS SA (SNG)" },
  { ticket:"SON", value:"GOOG/ELI_SON", caption:"Sonae SGPS SA (SON)" },
  { ticket:"SONC", value:"GOOG/ELI_SONC", caption:"Sonae Capital SGPS SA (SONC)" },
  { ticket:"SONI", value:"GOOG/ELI_SONI", caption:"Sonae Industria SGPS SA (SONI)" },
  { ticket:"SUCO", value:"GOOG/ELI_SUCO", caption:"Sumol+Compal SA (SUCO)" },
  { ticket:"SVA", value:"GOOG/ELI_SVA", caption:"SAG GEST - Solucoes Automovel Globais SA (SVA)" },
  { ticket:"TDSA", value:"GOOG/ELI_TDSA", caption:"Teixeira Duarte SA (TDSA)" },
  { ticket:"TRAAP", value:"GOOG/ELI_TRAAP", caption:"Transinsular - Transportes Mar Ins SA (TRAAP)" },
  { ticket:"VAF", value:"GOOG/ELI_VAF", caption:"VAA Vista Alegre Atlantis SGPS SA (VAF)" },
  { ticket:"VAFK", value:"GOOG/ELI_VAFK", caption:"VAA-V.ALEGRE-FUSAO (VAFK)" },
  { ticket:"ZONOP", value:"GOOG/ELI_ZONOP", caption:"Zon Optimus SGPS SA (ZONOP)" }
]

GoogleLisbon.getTickets = function(){
  return tickets;
}

export default GoogleLisbon
